package me.quyen.entities.fakadata;

import java.util.concurrent.ThreadLocalRandom;

public class AuthorData {
    public static String authorName(){
        return namesAndCodesAndEmailsAndUrls()[0];
    }
    public static String authorCode(){
        return namesAndCodesAndEmailsAndUrls()[1];
    }
    public static String authorEmail(){
        return namesAndCodesAndEmailsAndUrls()[2];
    }
    public static String authorUrl(){
        return namesAndCodesAndEmailsAndUrls()[3];
    }
    public static String[] namesAndCodesAndEmailsAndUrls(){
        int cInt = Math.min(authorNames().length,authorCodes().length);
        int rInt = ThreadLocalRandom.current().nextInt(0,cInt);
        String protocol = "https://www.";
        String[] domainTails = new String[]{".com",".net",".org",".me"};
        String[] mailTails
                = new String[]{"@gmail.com","@outlook.com","@live.com","@hotmail.com"
                ,"@msn.com","@yahoo.com", "@email.me"};
        String name = authorNames()[rInt];
        String code = authorCodes()[rInt];
        String url = protocol.concat(name.toLowerCase().replace(" ","-").trim())
                .concat(domainTails[ThreadLocalRandom.current().nextInt(0, domainTails.length)])
                .concat("/");
        String email = name.toLowerCase().trim().replace(" ",".")
                .concat(code.toLowerCase().replace("-",""))
                .concat(mailTails[ThreadLocalRandom.current().nextInt(0, mailTails.length)]);
        return new String[]{name, code, email, url};
    }
    public static String[] authorNames(){
        return new String[]{
                "Alex Alexander CIrvine",
                "Alexandria MarzanoLesnevich",
                "Thakazhi Sivasankara Pillai",
                "William Makepeace Thackeray",
                "Bankim Chandra Chatterjee",
                "Ritu Menon  Kamla Bhasin",
                "Tara Sankar Bandyopadhyay",
                "Sarat Chandra Chatterjee",
                "Maulana Abdul Kalam Azad",
                "William Browning Spencer",
                "William Burton McCormick",
                "Stan and Jan Berenstain",
                "Tressie McMillan Cottom",
                "Shirley Rousseau Murphy",
                "Major HPSAhluwalia",
                "Alexander Gordon Smith",
                "Alexander McCall Smith",
                "Shirley Russak Wachtel",
                "Bhagwan Shri Rajneesh",
                "Vijaya Raje Schindhia",
                "Alexandria Bellefleur",
                "Barbara Copperthwaite",
                "Zacharias Tanee Fomum",
                "Taffy BrodesserAkner",
                "Teresa Babcock Lassen",
                "Erle Stanley Gardner",
                "Edgar Rice Burroughs",
                "DrSRadhakrishnan",
                "Brigadier JPDalvi",
                "NChandrababu Naidu",
                "Maithili Sharan Gupt",
                "Bhabani Bhattacharya",
                "Alexandra Villasante",
                "Bianca SierraLuebke",
                "Zakiya Dalila Harris",
                "William Kent Krueger",
                "William Knoedelseder",
                "William Peter Blatty",
                "William Peter Grasso",
                "William SBurroughs",
                "Yudhanjaya Wijeratne",
                "Yvonne Battle Felton",
                "Tamara Ireland Stone",
                "Tara MStringfellow",
                "Terah Shelton Harris",
                "Terese Marie Mailhot",
                "William Shakespeare",
                "Maithili Saran Gupt",
                "Rabindranath Tagore",
                "Sri Aurobindo Ghosh",
                "Bal Gangadhar Tilak",
                "Manjula Padmanabhan",
                "Upamanyu Chatterjee",
                "Barbara Bartholomew",
                "Brenda Bevan Remmes",
                "Bruce Robert Coffin",
                "Yrsa Sigurdardottir",
                "Tanuja Desai Hidier",
                "Taylor Jenkins Reid",
                "Terri Anne Browning",
                "Thornton WBurgess",
                "Tola Rotimi Abraham",
                "Tracy Fredrychowski",
                "Trenton Lee Stewart",
                "Sandra West Prowell",
                "Gérard de Villiers",
                "Frank GSlaughter",
                "Mary Higgins Clark",
                "Nirad CChaudhuri",
                "Khwaja Ahmad Abbas",
                "APJAbdul Kalam",
                "Jai Shankar Prasad",
                "Sri Aurbindo Ghosh",
                "Alexandra Benedict",
                "Alexandra Sokoloff",
                "Alexandra Stoddard",
                "Barbara Jean Hicks",
                "Barbara Josselsohn",
                "Barbara Kingsolver",
                "Zora Neale Hurston",
                "William Kotzwinkle",
                "William L Myers Jr",
                "William McIlvanney",
                "Tembe DentonHurst",
                "Tennessee Williams",
                "Tiffany DJackson",
                "Tricia Levenseller",
                "Sandra Scoppettone",
                "Alexander Pushkin",
                "Masashi Kishimoto",
                "Kyotaro Nishimura",
                "Catherine Cookson",
                "James AMichener",
                "Patricia Cornwell",
                "Kazi Nazrul Islam",
                "Manohar Malgonkar",
                "Sisir Kumar Ghosh",
                "Uma Shankar Joshi",
                "LtGen KSBrar",
                "Munshi Prem Chand",
                "Maharishi Valmiki",
                "Pranab Mukherjee",
                "Alexandra Andrews",
                "Alexandra Bracken",
                "Alexandra Christo",
                "Alexandra Hawkins",
                "Alexandra Rowland",
                "Alexandria Clarke",
                "Alison Littlewood",
                "Balli Kaur Jaswal",
                "Brendan O’Carroll",
                "Wade Albert White",
                "Walter DEdmonds",
                "William Bernhardt",
                "William Kamkwamba",
                "William LShirer",
                "William Nicholson",
                "William Patterson",
                "William Sarabande",
                "Yuval Noah Harari",
                "Tania Anne Crosse",
                "Tanya Anne Crosby",
                "Tara Taylor Quinn",
                "Tatiana De Rosnay",
                "Terrence McCauley",
                "Terry CJohnston",
                "Tiffany Patterson",
                "Trixie Silvertale",
                "Shannon Messenger",
                "Shirley Damsgaard",
                "Barbara Cartland",
                "JRRTolkien",
                "Rumiko Takahashi",
                "Alistair MacLean",
                "Koyoharu Gotouge",
                "Michael Crichton",
                "Andrew Neiderman",
                "Roger Hargreaves",
                "Erskine Caldwell",
                "Seiichi Morimura",
                "Jawaharlal Nehru",
                "SRadhakrishnan",
                "PtRavi Shankar",
                "DrRaja Ramanna",
                "Alexandra Coutts",
                "Alexandra Ripley",
                "Alexandra Warren",
                "Alexandria House",
                "Alexis Henderson",
                "Alexis Schaitkin",
                "Barbara Bourland",
                "Barbara Cleverly",
                "Barbara Delinsky",
                "Beverly Swerling",
                "Bianca Sparacino",
                "Brandy LRivers",
                "Brenda KDavies",
                "Bryan Washington",
                "Zack Loran Clark",
                "Zecharia Sitchin",
                "Wensley Clarkson",
                "Whitley Strieber",
                "Whitney Cummings",
                "William Kowalski",
                "William Le Queux",
                "William PYoung",
                "William SCohen",
                "Xóchitl González",
                "Yotam Ottolenghi",
                "Tanehisi Coates",
                "Tamera Alexander",
                "Tehlor Kay Mejia",
                "Tera Lynn Childs",
                "Teresa JReasor",
                "Teresa Southwick",
                "Terri Blackstock",
                "Tiffany McDaniel",
                "Tiffany Rosenhan",
                "Trang Thanh Tran",
                "Travis STaylor",
                "Trisha RThomas",
                "Sandrone Dazieri",
                "Santa Montefiore",
                "Saundra Mitchell",
                "Shanora Williams",
                "Shirley MacLaine",
                "Agatha Christie",
                "Georges Simenon",
                "James Patterson",
                "Mickey Spillane",
                "Astrid Lindgren",
                "Debbie Macomber",
                "Stephenie Meyer",
                "Norman Bridwell",
                "Nicholas Sparks",
                "Eleanor Hibbert",
                "Terry Pratchett",
                "Chetan Bhagat",
                "Janardan Thakur",
                "Khushwant Singh",
                "Swami Sivananda",
                "Chandra Shekhar",
                "Rajmohan Gandhi",
                "Vijay Tendulkar",
                "DrKaran Singh",
                "Rajendra Prasad",
                "NAPalkhivala",
                "SHVatsayayan",
                "Bibhuti Bhushan",
                "Khushwant Singh",
                "Alexandra Brown",
                "Alexandra Chang",
                "Alexandra Moody",
                "Alexandra Silva",
                "Alexandra Walsh",
                "Alexandre Dumas",
                "Alexey Osadchuk",
                "Alice Blanchard",
                "Alice Borchardt",
                "Alison Ragsdale",
                "Alison Sherlock",
                "Alistair Moffat",
                "Allan Mallinson",
                "Allan WEckert",
                "Allan Yoskowitz",
                "Allen MSteele",
                "Barbara Bretton",
                "Barbara Cameron",
                "Barbara D’Amato",
                "Barbara Erskine",
                "Barbara Fradkin",
                "Barbara Freethy",
                "Barbara Holland",
                "Barbara Longley",
                "Bharti Kirchner",
                "Bill Konigsberg",
                "Bill Willingham",
                "Breanne Randall",
                "Breeana Shields",
                "Brenda Buchanan",
                "Brenda Janowitz",
                "Brendan Mathews",
                "Brendan Slocumb",
                "Bruce Holsinger",
                "Bryan Stevenson",
                "Bryan WAlaspa",
                "Bryce Courtenay",
                "Zane Michaelson",
                "Zenna Henderson",
                "Zoe Hana Mikuta",
                "Zoraida Córdova",
                "Wallace Stegner",
                "Wallace Swenson",
                "Walter Isaacson",
                "Whoopi Goldberg",
                "William Brodick",
                "William Lashner",
                "William Shatner",
                "Yukito Ayatsuji",
                "Tanya RTaylor",
                "TaraShea Nesbit",
                "Tariq Ashkanani",
                "Tasha Alexander",
                "Taylor Anderson",
                "Taylor Caldwell",
                "Terence Faherty",
                "Teresa Driscoll",
                "Teresa Medeiros",
                "Terri LAustin",
                "Thornton Wilder",
                "Tiffany Roberts",
                "Tiffany Schmidt",
                "Tina TMClark",
                "Tochi Onyebuchi",
                "Tracy LHigley",
                "Trevor Ferguson",
                "Tricia O’Malley",
                "Trish Williford",
                "Tristina Wright",
                "Sandra Bretting",
                "Sandra Cisneros",
                "Sandra Fletcher",
                "Sandra Magsamen",
                "Sandra Parshall",
                "Sanjena Sathian",
                "Santino Hassell",
                "Sapphire Knight",
                "Shannon Richard",
                "Shannon Schuren",
                "Shantel Tessier",
                "Shirleen Davies",
                "Shirlene Obuobi",
                "Shirley Dickson",
                "Shirley Jackson",
                "Shirley Tallman",
                "Quintin Jardine",
                "Danielle Steel",
                "Harold Robbins",
                "Sidney Sheldon",
                "Gilbert Patten",
                "Akira Toriyama",
                "Jackie Collins",
                "Jeffrey Archer",
                "Irving Wallace",
                "Mitsuru Adachi",
                "Beatrix Potter",
                "Richard Scarry",
                "Eiji Yoshikawa",
                "Hajime Isayama",
                "David Baldacci",
                "Hirohiko Araki",
                "HSVatsyayan",
                "Amit Chaudhuri",
                "Sarojini Naidu",
                "Mulk Raj Anand",
                "Mahatma Gandhi",
                "Sunil Gavaskar",
                "Gurucharan Das",
                "SNihal Singh",
                "RVenkatraman",
                "GRNarayanan",
                "Harsha Vardhan",
                "Vikram Chandra",
                "Girraj Kishore",
                "Mahadevi Verma",
                "Alexandra Diaz",
                "Alexandra Joel",
                "Alfred Lansing",
                "Alison Cochrun",
                "Alison Croggon",
                "Alison Goodman",
                "Alissa Johnson",
                "Alissa Nutting",
                "Alix EHarrow",
                "Aliya Whiteley",
                "Aliza Fogelson",
                "Allan Leverone",
                "Barbara Conrey",
                "Barbara Dunlop",
                "Barbara Graham",
                "Barbara Hambly",
                "Barbara Hinske",
                "Bill Flockhart",
                "Bill Knussmann",
                "Bill Watterson",
                "Billy Connolly",
                "Brandy Colbert",
                "Brenda Chapman",
                "Brenda English",
                "Brenda Jackson",
                "Brenda Rothert",
                "Brendan Dubois",
                "Brendan Reichs",
                "Bruce Sterling",
                "Bryce O’Connor",
                "Budd Schulberg",
                "Zeyn Joukhadar",
                "Zinzi Clemmons",
                "Wadsworth Camp",
                "Wallace Stroby",
                "Whitney Dineen",
                "Wilkie Collins",
                "William Landay",
                "William Martin",
                "William Meikle",
                "William Miller",
                "William Ritter",
                "Xiran Jay Zhao",
                "Taleen Voskuni",
                "Tammara Webber",
                "Tammy Andresen",
                "Tammy LGrace",
                "Tananarive Due",
                "Tanaz Bhathena",
                "Tara KHarper",
                "Tara Laskowski",
                "Tashie Bhuiyan",
                "Taylor Stevens",
                "Terence Strong",
                "Teresa Burrell",
                "Teresa Mummert",
                "Terri Windling",
                "Terry Bolryder",
                "Terry Goodkind",
                "Thrity Umrigar",
                "Tilly Bagshawe",
                "Tim MacGabhann",
                "Tina Wainscott",
                "Tinker Lindsay",
                "Titania Hardie",
                "Toby Neighbors",
                "Todd McCaffrey",
                "Tracy Lorraine",
                "Travis Bagwell",
                "Travis Baldree",
                "Trent Preszler",
                "Trevor Douglas",
                "Sandra Boynton",
                "Sandra Nikolai",
                "Sandra Orchard",
                "Sangu Mandanna",
                "Savannah Rylan",
                "Savannah Scott",
                "Sawyer Bennett",
                "Shannon McNear",
                "Shannon Morgan",
                "Shannon Stacey",
                "Shirlee Busbee",
                "Shirley Conran",
                "Quinta Brunson",
                "JKRowling",
                "Corín Tellado",
                "Horatio Alger",
                "Louis L'Amour",
                "René Goscinny",
                "Edgar Wallace",
                "Robert Ludlum",
                "Frédéric Dard",
                "Ann MMartin",
                "Ryōtarō Shiba",
                "Arthur Hailey",
                "Clive Cussler",
                "Naoki Urasawa",
                "Judith Krantz",
                "Lewis Carroll",
                "Denise Robins",
                "Hermann Hesse",
                "Chetan Bhagat",
                "Balwant Gargi",
                "Satish Gujral",
                "Jaswant Singh",
                "Deepak Chopra",
                "Amrita Pritam",
                "Romila Thapar",
                "Anurag Mathur",
                "Jhumpa Lahiri",
                "Hari Jaisingh",
                "Tavleen Singh",
                "Indira Gandhi",
                "ABVajpayee",
                "Vishnu Sharma",
                "MNSrinivas",
                "Arundhati Roy",
                "Kuldeep Nayar",
                "Shrabani Basu",
                "Alex Davidson",
                "Alex Erickson",
                "Alex Ferguson",
                "Alex Gilvarry",
                "Alex Marshall",
                "Alexander Key",
                "Alexandra Ivy",
                "Alexia Gordon",
                "Alexis Adaire",
                "Alexis Calder",
                "Alexis Morgan",
                "Alexis Winter",
                "Alfred Bester",
                "Ali DJensen",
                "Ali Hazelwood",
                "Alison Gaylin",
                "Alison Golden",
                "Alison Hammer",
                "Alissa Holder",
                "Allan Guthrie",
                "Barbara Davis",
                "Barbara Allan",
                "Barbara Early",
                "Barbara Gowdy",
                "Bianca Blythe",
                "Bianca Marais",
                "Bill Fitzhugh",
                "Bill Loehfelm",
                "Bill O’Reilly",
                "Bill Prentice",
                "Bill Pronzini",
                "Brenda Lozano",
                "Brenda Minton",
                "Brenda Wilbee",
                "Bruce MacBain",
                "Bruno Vincent",
                "Bryan Christy",
                "Bryan Peabody",
                "Bryan Reardon",
                "Bryn Turnbull",
                "Bryony Pearce",
                "Zane Mitchell",
                "Zoulfa Katouh",
                "Walt Browning",
                "Walter Farley",
                "Werner Herzog",
                "Weston Parker",
                "Whitley Green",
                "Wilkie Martin",
                "Will Lavender",
                "Will Peterson",
                "Will Shindler",
                "Willard Price",
                "William Davis",
                "William Evans",
                "William Arden",
                "William Bayer",
                "William Black",
                "William Boyle",
                "William Kelso",
                "William Nolan",
                "Tade Thompson",
                "Talia Hibbert",
                "Tamara Thorne",
                "Tammy Falkner",
                "Tammy Kaehler",
                "Tamora Pierce",
                "Tara Schuster",
                "Tara Westover",
                "Taran Matharu",
                "Tarryn Fisher",
                "Taryn Elliott",
                "Tasmina Perry",
                "Taylor Zajonc",
                "Teagan Brooks",
                "Terri Brisbin",
                "Terri Parlato",
                "Terry Ambrose",
                "Terry Dowling",
                "Tiffany Baton",
                "Tiffany Reisz",
                "Tillie Walden",
                "Tilly Wallace",
                "Tim CTaylor",
                "Tim Hodkinson",
                "Toby Clements",
                "Tracy Gardner",
                "Tracy Hickman",
                "Tricia Fields",
                "Tricia Leedom",
                "Trilina Pucci",
                "Trisha Ashley",
                "Sandra Becker",
                "Sandra Dallas",
                "Sandy Dengler",
                "Satya Nadella",
                "Sharan Newman",
                "Shirlee McCoy",
                "Shirley Wells",
                "Quentin Bates",
                "Eiichiro Oda",
                "Nora Roberts",
                "Stephen King",
                "Paulo Coelho",
                "Jirō Akagawa",
                "Janet Dailey",
                "Osamu Tezuka",
                "John Grisham",
                "Gosho Aoyama",
                "Carter Brown",
                "Wilbur Smith",
                "John Creasey",
                "Yasuo Uchida",
                "Penny Jordan",
                "VSNaipaul",
                "Amitav Ghosh",
                "Preeti Singh",
                "RKNarayan",
                "Satyajit Ray",
                "Annie Besant",
                "Alex Grayson",
                "Alex Grecian",
                "Alex Kershaw",
                "Alex Lukeman",
                "Alex MacLean",
                "Alexi Venice",
                "Alexis Daria",
                "Alexx Andria",
                "Ali McNamara",
                "Ali Standish",
                "Allan Folsom",
                "Allan Martin",
                "Allan Massie",
                "Allen Eskens",
                "Barb Goffman",
                "Barbara Ebel",
                "Bianca D’Arc",
                "Bill Granger",
                "Bill McCurry",
                "Bill Thesken",
                "Bill Wallace",
                "Billie Bloom",
                "Billie Letts",
                "Brenda Hiatt",
                "Brenda Joyce",
                "Brenda Novak",
                "Bruce Sentar",
                "Bruno Krauss",
                "Bruno Miller",
                "Bryan Devore",
                "Bryan Fields",
                "Bryan Gruley",
                "Bryan Mealer",
                "Brynne Asher",
                "Budge Wilson",
                "Burt SLevy",
                "Burt Solomon",
                "Zach Jenkins",
                "Zaina Arafat",
                "Zamil Akhtar",
                "Zan Romanoff",
                "Zeba Shahnaz",
                "Zile Elliven",
                "Zoe Ferraris",
                "Zoe Jane Fox",
                "Zoe Matthews",
                "Zoe Whittall",
                "Wahida Clark",
                "Walker Percy",
                "Walt Whitman",
                "Walter Brown",
                "Wesley Cross",
                "Weston Ochse",
                "Wil McCarthy",
                "Willa Cather",
                "William Boyd",
                "William King",
                "William Kuhn",
                "Yume Kitasei",
                "Yuri Herrera",
                "Yuri Rytkheu",
                "Yūsei Matsui",
                "Yuto Tsukuda",
                "Yuyi Morales",
                "Tabitha King",
                "Tad Williams",
                "Tahereh Mafi",
                "Talbot Mundy",
                "Talia Carner",
                "Tamara Berry",
                "Tami Charles",
                "Tamie Dearen",
                "Tamika Brown",
                "Tan Twan Eng",
                "Tana Collins",
                "Tania Carver",
                "Tanvi Berwah",
                "Tara Conklin",
                "Tarah Benner",
                "Tarquin Hall",
                "Tash Skilton",
                "Tatjana Soli",
                "Tawna Fenske",
                "Tawni O’Dell",
                "Tawny Stokes",
                "Tayari Jones",
                "Tayla Louise",
                "Taylor Adams",
                "Taylor Brown",
                "Taylor Moore",
                "Taylor Rylan",
                "Taylor Smith",
                "TePing Chen",
                "Ted Allbeury",
                "Ted Kosmatka",
                "Tendai Huchu",
                "Terri DuLong",
                "Terri Farley",
                "Terri Osburn",
                "Terry Brooks",
                "Terry Fallis",
                "Thomas Wolfe",
                "Thorne Smith",
                "Tia Williams",
                "Tiana Laveen",
                "Tiffany Snow",
                "Tiffany Tsao",
                "Tim Marshall",
                "Tim Sullivan",
                "Tim Johnston",
                "Tim McGregor",
                "Tina Whittle",
                "Tirzah Price",
                "Tod Goldberg",
                "Todd Herzman",
                "Tom Fletcher",
                "Tom Reynolds",
                "Tracy Lauren",
                "Tracy Sumner",
                "Trae Macklin",
                "Trent Dalton",
                "Trent Jordan",
                "Trevor Negus",
                "Trevor Scott",
                "Tricia Goyer",
                "Trish Doller",
                "Troy Denning",
                "Sandra Balzo",
                "Sandra Brown",
                "Sandra Owens",
                "Sandra Prior",
                "Sandy Barker",
                "Sandy Taylor",
                "Shannon Work",
                "Shannyn Leah",
                "Qiu Xiaolong",
                "Quinn Loftis",
                "Enid Blyton",
                "Leo Tolstoy",
                "Dean Koontz",
                "RLStine",
                "CSLewis",
                "Ken Follett",
                "Evan Hunter",
                "Ian Fleming",
                "LKAdvani",
                "Vikram Seth",
                "Anita Desai",
                "IKGujral",
                "Bana Bhatta",
                "MKGandhi",
                "Kiran Desai",
                "KMMunshi",
                "MVKamath",
                "Ginu Kamani",
                "TNSeshan",
                "Alex Connor",
                "Alex Dryden",
                "Alex Finlay",
                "Alex George",
                "Alex Gerlis",
                "Alex Howard",
                "Alex Howell",
                "Alex Kahler",
                "Alex Lidell",
                "Alex London",
                "Alexis Hall",
                "Alexis Anne",
                "Ali Brandon",
                "Alice Adams",
                "Alison Weir",
                "Allen Drury",
                "Barb Hendee",
                "Bianca Cole",
                "Bill Cotter",
                "Bill Crider",
                "Bill Harlow",
                "Bill Kitson",
                "Bill Madden",
                "Bill Napier",
                "Bill Rivers",
                "Bill Rogers",
                "Bill Runner",
                "Bill Wenham",
                "Brandt Legg",
                "Brea Alepoú",
                "Bree Barton",
                "Brenda Trim",
                "Bryan Davis",
                "Bryan James",
                "Zack Taylor",
                "Zadie Smith",
                "Zain Khalid",
                "Zara Lisbon",
                "Zara Raheem",
                "Zina Abbott",
                "Zoe Fishman",
                "Zoe Markham",
                "Zoey Draven",
                "Wesley King",
                "Wesley Yang",
                "Wil Haygood",
                "Will Carver",
                "Will Jordan",
                "Will Leitch",
                "Will Mackin",
                "Will Thomas",
                "Will Walton",
                "Will Weaver",
                "Xander Jade",
                "Xio Axelrod",
                "Yoon Ha Lee",
                "Yung Pueblo",
                "Tabor Evans",
                "Tamar Myers",
                "Tamar Sloan",
                "Tamara Gill",
                "Tamsyn Muir",
                "Tana French",
                "Tanen Jones",
                "Tania James",
                "Tara Grayce",
                "Tara Janzen",
                "Tara Sue Me",
                "Tara Thomas",
                "Tarah Scott",
                "Taryn Quinn",
                "Tasha Black",
                "Tawny Weber",
                "Taylor Hart",
                "Taylor Ward",
                "Tedd Arnold",
                "Tegan Maher",
                "Tell Cotten",
                "Teri Wilson",
                "Terri Lorah",
                "Terry Deary",
                "Tia Souders",
                "Tif Marcelo",
                "Tigris Eden",
                "Tillie Cole",
                "Tim Ayliffe",
                "Tim Butcher",
                "Tim Collins",
                "Tim Jopling",
                "Tim Maleeny",
                "Tim O’Brien",
                "Todd Ritter",
                "Todd Tucker",
                "Tola Okogwu",
                "Tracy Deonn",
                "Tracy Grant",
                "Tracy Letts",
                "Tracy Weber",
                "Tracy Wolff",
                "Trent Reedy",
                "Trevor Noah",
                "Trevor Wood",
                "Tricia Tusa",
                "Tripp Ellis",
                "Triss Stein",
                "Sandra Hill",
                "Sara Hashem",
                "Saul Bellow",
                "Saul Herzog",
                "Savanna Fox",
                "Tom Clancy",
                "Roald Dahl",
                "Robin Cook",
                "Cao Xueqin",
                "Anne Golon",
                "Gita Mehta",
                "Amar Singh",
                "HPNanda",
                "Prem Chand",
                "Kiran Bedi",
                "Sunny Days",
                "Alex Flinn",
                "Alex Gates",
                "Alex Gilly",
                "Alex Gough",
                "Alex Light",
                "Alexis Coe",
                "Ali Mercer",
                "Ali Parker",
                "Alka Joshi",
                "Bex McLynn",
                "Bill James",
                "Bill Myers",
                "Bree Baker",
                "Brynn Hale",
                "Zara Zenia",
                "Zhang Ling",
                "Zoe Dawson",
                "Zoë Heller",
                "Zoe Saadia",
                "Zoje Stage",
                "Wally Lamb",
                "Walt Gragg",
                "Wendy Webb",
                "Wes DeMott",
                "Wesley Chu",
                "Wiley Cash",
                "Will Adams",
                "Will Gater",
                "Will Hobbs",
                "Will North",
                "Will Wight",
                "Willa Nash",
                "Tace Baker",
                "Taki Drake",
                "Tana Stone",
                "Tanith Lee",
                "Tanya Bird",
                "Tanya Huff",
                "Tara Brown",
                "Tara Ellis",
                "Tara Wyatt",
                "Tasha Suri",
                "Tate James",
                "Tea Cooper",
                "Tea Obreht",
                "Ted Chiang",
                "Ted Dekker",
                "Tee Morris",
                "Teri Woods",
                "Terri Reed",
                "Terri Reid",
                "Tia Louise",
                "Tim Bowler",
                "Tim Cockey",
                "Tim Dorsey",
                "Tim Garvin",
                "Tim LaHaye",
                "Tim Lebbon",
                "Tim McBain",
                "Tim O’Mara",
                "Tiya Miles",
                "Toby Faber",
                "Todd Burpo",
                "Tracy Mack",
                "Tracy Rees",
                "Trevor Eve",
                "Trisha Das",
                "Sandy Hall",
                "Sandy Hill",
                "Saul Black",
                "Sax Rohmer",
                "DrSeuss",
                "Zane Grey",
                "Dan Brown",
                "Anne Rice",
                "Tite Kubo",
                "Rex Stout",
                "Abul Fazl",
                "Kapil Dev",
                "VVGiri",
                "Ved Mehta",
                "Shobha De",
                "Alex Dahl",
                "Alex Gray",
                "Alex Kava",
                "Alex Lake",
                "Ali Rosen",
                "Ali Smith",
                "Bill Noel",
                "Bree Wolf",
                "Zoe Blake",
                "Zoe Chant",
                "Zoe Sharp",
                "Wes Allen",
                "Wes Moore",
                "Whitney G",
                "Will Dean",
                "Will Mara",
                "Yuri Ajin",
                "Tal Bauer",
                "Tami Hoag",
                "Tami Lund",
                "Tara Lush",
                "Tara Moss",
                "Terry Fan",
                "Tim Akers",
                "Tim Downs",
                "Tim Ellis",
                "Tim Green",
                "Tim Kizer",
                "Tim Leach",
                "Tim Mason",
                "Tim Myers",
                "Tim Parks",
                "Tim Peake",
                "Tish Rabe",
                "Tiye Love",
                "TME Walsh",
                "Toby Neal",
                "Todd Borg",
                "Todd Moss",
                "Tom Crewe",
                "Trevanian",
                "Troy Soos",
                "Jin Yong",
                "Karl May",
                "EL James",
                "Kautilya",
                "Jayadeva",
                "Raja Rao",
                "Tulsidas",
                "Ali Land",
                "Ali Lowe",
                "Ali Vali",
                "Ali Wong",
                "Bre Rose",
                "Zara Cox",
                "Zepphora",
                "Zoe Sugg",
                "Zoe York",
                "Zuri Day",
                "Tao Wong",
                "Tara Sim",
                "Ted Bell",
                "Ted Mark",
                "Tim Lees",
                "Tom Ryan",
                "Kalidas",
                "Kalhana",
                "Zen Cho",
                "Zogarth",
                "Tao Lin",
                "Té Russ",
                "Temi Oh",
                "Ghalib",
                "Gulzar",
                "Tijan",
                "Zane"
        };
    }
    public static String[] authorCodes(){
        return new String[]{
                "AACC-7726",
                "AMVR-6353",
                "TSPF-3622",
                "WMTP-7886",
                "BCCQ-5053",
                "RM K-2529",
                "TSBZ-1742",
                "SCCC-5571",
                "MAKA-1241",
                "WBSD-9257",
                "WBMU-2639",
                "SAJB-5902",
                "TMCW-1374",
                "SRMO-7635",
                "MHKU-2380",
                "AGSB-6364",
                "AMSL-6057",
                "SRWV-6562",
                "BSRW-9903",
                "VRSA-4690",
                "ABND-7412",
                "BCJI-6342",
                "ZTFS-8980",
                "TBYP-3763",
                "TBLS-2952",
                "ESGV-8830",
                "ERBF-8444",
                "DMKL-7810",
                "BJQO-4514",
                "NNEL-3578",
                "MSGO-4369",
                "BBFV-3139",
                "AVKV-2128",
                "BSXY-2635",
                "ZDHO-6216",
                "WKKN-3335",
                "WKEO-6815",
                "WPBT-7929",
                "WPGW-1968",
                "WSJX-3349",
                "YWBQ-9462",
                "YBFM-1592",
                "TISE-9770",
                "TMIS-2457",
                "TSHF-7937",
                "TMMW-8823",
                "WSEN-3723",
                "MSGW-3883",
                "RTYF-6562",
                "SAGO-3148",
                "BGTK-7304",
                "MPZR-4220",
                "UCAT-2760",
                "BBFE-6711",
                "BBRX-8205",
                "BRCU-7677",
                "YSXE-2473",
                "TDHE-5358",
                "TJRS-4377",
                "TABN-5678",
                "TWYP-8678",
                "TRAK-4486",
                "TFTV-7413",
                "TLSN-8365",
                "SWPM-3252",
                "GDVV-6832",
                "FGIG-3048",
                "MHCJ-4582",
                "NCOS-3436",
                "KAAK-3183",
                "AKQD-8817",
                "JSPS-1436",
                "SAGI-8702",
                "ABFK-3928",
                "ASQP-7482",
                "ASVV-4195",
                "BJHZ-9585",
                "BJHH-8054",
                "BKMJ-9010",
                "ZNHT-7858",
                "WKFM-5550",
                "WLMJ-5074",
                "WMKJ-7827",
                "TDMV-6014",
                "TWVJ-9959",
                "TDRC-1786",
                "TLVZ-2505",
                "SSZY-2299",
                "APUP-4292",
                "MKYY-4431",
                "KNSQ-3629",
                "CCYQ-9889",
                "JAGR-2768",
                "PCHX-7610",
                "KNIJ-4081",
                "MMRZ-7482",
                "SKGY-8575",
                "USJH-7794",
                "LKLF-2114",
                "MPCO-7398",
                "MVZW-1639",
                "PMZX-9638",
                "AALS-6596",
                "ABAN-5321",
                "ACYM-8963",
                "AHWK-8890",
                "ARUN-8873",
                "ACAJ-5260",
                "ALOQ-2325",
                "BKJU-6517",
                "BOFL-9137",
                "WAWH-8000",
                "WDES-2663",
                "WBBB-8126",
                "WKJU-5119",
                "WLDM-8385",
                "WNFS-9023",
                "WPOB-9205",
                "WSPL-3992",
                "YNHD-4372",
                "TACT-9788",
                "TACM-8448",
                "TTQH-6008",
                "TDRM-7672",
                "TMPL-3194",
                "TCDI-6284",
                "TPMK-6722",
                "TSJE-2122",
                "SMFJ-2678",
                "SDKE-3958",
                "BCXK-9645",
                "JOJM-8085",
                "RTBE-7913",
                "AMHV-6660",
                "KGKM-2612",
                "MCXA-1110",
                "ANSN-1214",
                "RHTQ-2895",
                "ECSL-4946",
                "SMCZ-5782",
                "JNYA-2521",
                "SAKP-2108",
                "PSQN-3281",
                "DROO-3449",
                "ACJK-3104",
                "ARAH-8093",
                "AWBJ-1385",
                "AHSL-8078",
                "AHFQ-4215",
                "ASSY-2132",
                "BBZF-3969",
                "BCHZ-7911",
                "BDEY-6107",
                "BSOP-7703",
                "BSPG-3780",
                "BLNY-4106",
                "BKAO-5423",
                "BWYW-4136",
                "ZLCT-6493",
                "ZSGQ-6750",
                "WCYC-7239",
                "WSNX-9380",
                "WCSN-9175",
                "WKVS-4205",
                "WLQW-6385",
                "WPIZ-6345",
                "WSUM-8964",
                "XGMV-1766",
                "YOTF-4769",
                "TCFY-1585",
                "TAIG-4329",
                "TKMF-1378",
                "TLCO-1191",
                "TJRT-2221",
                "TSAQ-1777",
                "TBKP-8196",
                "TMFH-4541",
                "TRGF-7178",
                "TTTO-6139",
                "TSIT-8753",
                "TRJY-5464",
                "SDKR-6918",
                "SMCV-7893",
                "SMYM-7594",
                "SWNM-9053",
                "SMYR-7874",
                "ACNJ-1379",
                "GSJN-7147",
                "JPYA-9807",
                "MSOZ-4611",
                "ALCT-6240",
                "DMSK-4668",
                "SMTR-7129",
                "NBGW-9725",
                "NSGJ-2535",
                "EHMF-9385",
                "TPPE-3617",
                "CBNX-2374",
                "JTZQ-7906",
                "KSMG-8558",
                "SSDT-9792",
                "CSBZ-8488",
                "RGWJ-1740",
                "VTIP-6110",
                "DSON-6237",
                "RPWJ-1685",
                "NQAD-5253",
                "SQJY-6799",
                "BBWI-2768",
                "KSSU-4375",
                "ABBW-8306",
                "ACSV-6874",
                "AMKE-8808",
                "ASPB-1080",
                "AWML-2736",
                "ADDK-1775",
                "AOZL-4403",
                "ABFY-6911",
                "ABQI-3537",
                "ARAU-4575",
                "ASPV-8913",
                "AMVY-2510",
                "AMMA-8967",
                "AWJI-1803",
                "AYDG-3265",
                "AMDI-8964",
                "BBUK-3497",
                "BCSS-2184",
                "BDIL-2782",
                "BEKV-7656",
                "BFDD-6524",
                "BFXG-9765",
                "BHZL-9140",
                "BLYW-2787",
                "BKGX-3268",
                "BKZW-8820",
                "BWUJ-5695",
                "BRIM-6519",
                "BSVC-2110",
                "BBBS-7503",
                "BJHI-4892",
                "BMHQ-9916",
                "BSIP-5201",
                "BHSM-3248",
                "BSDM-6047",
                "BWYD-9750",
                "BCUU-5252",
                "ZMOI-7309",
                "ZHFA-5182",
                "ZHMH-4644",
                "ZCNJ-8591",
                "WSMF-5196",
                "WSIA-6654",
                "WIGR-1774",
                "WGJT-8547",
                "WBKY-5894",
                "WLBJ-4025",
                "WSFC-1003",
                "YAYO-1309",
                "TRDY-4795",
                "TNBT-1998",
                "TACL-8171",
                "TAIY-1164",
                "TABI-7911",
                "TCUB-7692",
                "TFFA-1219",
                "TDCV-9120",
                "TMCP-4823",
                "TLCG-8308",
                "TWBW-5945",
                "TROC-1874",
                "TSOW-1221",
                "TTDA-9821",
                "TOLP-4356",
                "TLKD-8950",
                "TFTK-1446",
                "TOBJ-5544",
                "TWDA-2441",
                "TWBC-5088",
                "SBNQ-1786",
                "SCWC-6697",
                "SFVI-1865",
                "SMUD-7849",
                "SPKL-4129",
                "SSFU-3552",
                "SHOA-3811",
                "SKYR-5011",
                "SRHZ-9162",
                "SSDG-6587",
                "STKA-8595",
                "SDYU-9518",
                "SOKE-9083",
                "SDGN-5146",
                "SJRP-8635",
                "STYL-2036",
                "QJRM-6564",
                "DSTF-6006",
                "HRAG-5441",
                "SSFU-1940",
                "GPAE-6313",
                "ATWA-6460",
                "JCBE-6686",
                "JATN-5874",
                "IWOX-1989",
                "MAEH-5616",
                "BPMV-9177",
                "RSBK-1565",
                "EYTI-7939",
                "HIYY-5010",
                "DBBT-4976",
                "HAHZ-2148",
                "HUPN-9119",
                "ACIB-7368",
                "SNQH-4945",
                "MRAS-9154",
                "MGZA-6561",
                "SGAX-5773",
                "GDES-3892",
                "SSRH-8099",
                "RBCO-8614",
                "GSOA-2149",
                "HVEH-8450",
                "VCTT-6437",
                "GKUQ-3048",
                "MVCV-5272",
                "ADYL-6957",
                "AJQQ-2496",
                "ALEM-1707",
                "ACFW-2933",
                "ACUQ-4008",
                "AGHW-4090",
                "AJAM-3501",
                "ANDH-2256",
                "AESE-7836",
                "AWCI-9647",
                "AFYH-9394",
                "ALSX-3267",
                "BCZN-5918",
                "BDZZ-8335",
                "BGAR-4950",
                "BHMW-5149",
                "BHPX-2584",
                "BFKD-4120",
                "BKTK-9272",
                "BWYF-1468",
                "BCVN-8484",
                "BCGF-8905",
                "BCET-9350",
                "BEWR-5829",
                "BJYG-5709",
                "BRIJ-9951",
                "BDQH-8404",
                "BROE-3387",
                "BSWU-3773",
                "BOYA-8390",
                "BSBP-1905",
                "ZJOV-9524",
                "ZCHZ-8162",
                "WCOQ-9956",
                "WSUB-9692",
                "WDOV-1570",
                "WCMK-5958",
                "WLZD-7165",
                "WMHO-9289",
                "WMHO-2139",
                "WMUW-9228",
                "WRPC-9745",
                "XJZS-8073",
                "TVJE-2381",
                "TWRV-3714",
                "TAHR-8606",
                "TLZB-6427",
                "TDFY-6639",
                "TBTT-5520",
                "TKNR-1166",
                "TLLJ-7551",
                "TBAK-4451",
                "TSFQ-6349",
                "TSHR-4042",
                "TBPI-1498",
                "TMWV-5712",
                "TWOQ-8858",
                "TBZB-7789",
                "TGKL-1113",
                "TUMD-7125",
                "TBNX-7583",
                "TMJF-4798",
                "TWHE-9983",
                "TLRT-2128",
                "THSR-3076",
                "TNML-6375",
                "TMXI-3488",
                "TLWG-7572",
                "TBYF-2829",
                "TBID-3939",
                "TPTV-6560",
                "TDPF-5454",
                "SBXC-7233",
                "SNAI-5049",
                "SOOA-7936",
                "SMFB-6131",
                "SRGE-2876",
                "SSYY-4676",
                "SBPR-7354",
                "SMNC-2909",
                "SMIL-1012",
                "SSJJ-1274",
                "SBQI-6404",
                "SCOG-1924",
                "QBQM-2009",
                "JWPE-1432",
                "CTBU-8053",
                "HAZY-8989",
                "LLKP-3187",
                "RGEW-9225",
                "EWEG-8004",
                "RLXB-8881",
                "FDGB-3186",
                "AMBC-3378",
                "RSEQ-4170",
                "AHSX-8008",
                "CCVR-8677",
                "NUUN-9212",
                "JKAM-9494",
                "LCXH-6975",
                "DRHM-8712",
                "HHCS-3409",
                "CBFD-2587",
                "BGAD-5992",
                "SGVX-5791",
                "JSLA-9097",
                "DCBU-2466",
                "APFN-4851",
                "RTTU-5780",
                "AMYD-4103",
                "JLQP-1851",
                "HJHK-7225",
                "TSGC-5653",
                "IGTG-7286",
                "AKCK-6198",
                "VSOF-4859",
                "MXDR-2133",
                "ARYT-1443",
                "KNIE-7871",
                "SBNR-2783",
                "ADPB-5704",
                "AEOU-9741",
                "AFTX-1543",
                "AGIK-8145",
                "AMLQ-6194",
                "AKWI-3132",
                "AIAS-1514",
                "AGIP-2149",
                "AAAK-6196",
                "ACMR-7535",
                "AMMQ-6912",
                "AWAO-3318",
                "ABIA-1898",
                "ADSX-3924",
                "AHAQ-4223",
                "AGTY-2408",
                "AGXX-4848",
                "AHOB-1821",
                "AHSN-6285",
                "AGGG-7273",
                "BDTP-3660",
                "BAKP-4838",
                "BENF-1552",
                "BGWB-3762",
                "BBNI-9538",
                "BMOX-5088",
                "BFYM-2145",
                "BLBH-2279",
                "BOFA-3399",
                "BPCK-5177",
                "BPDS-6164",
                "BLDT-3158",
                "BMBW-8746",
                "BWKZ-9840",
                "BMDZ-1811",
                "BVYO-5379",
                "BCHF-2763",
                "BPUO-7552",
                "BROX-1546",
                "BTPM-9843",
                "BPRM-3706",
                "ZMUU-7580",
                "ZKGJ-8640",
                "WBFH-9228",
                "WFHM-7490",
                "WHMK-3227",
                "WPMD-8702",
                "WGYS-8056",
                "WMMP-2319",
                "WLSK-8872",
                "WPXD-3525",
                "WSDK-8321",
                "WPOX-8402",
                "WDRH-8258",
                "WEZB-5563",
                "WAMQ-8394",
                "WBJW-2608",
                "WBAK-2042",
                "WBWX-8733",
                "WKDJ-8181",
                "WNDU-5810",
                "TTHY-4931",
                "THHU-2321",
                "TTXT-5388",
                "TFMA-5557",
                "TKNT-2631",
                "TPQK-9806",
                "TSQL-6924",
                "TWTD-2882",
                "TMDM-9590",
                "TFGB-7977",
                "TEZH-1441",
                "TPMJ-4626",
                "TZSA-3513",
                "TBXT-9738",
                "TBUX-9937",
                "TPDN-1136",
                "TAZU-1908",
                "TDEZ-5238",
                "TBCF-7006",
                "TRXW-2299",
                "TWHX-6543",
                "TWAI-5909",
                "TCSE-3651",
                "THJC-2763",
                "TCUO-9655",
                "TGBW-5207",
                "THUB-5444",
                "TFRT-7357",
                "TLWV-3003",
                "TPCL-5973",
                "TALY-4294",
                "SBCL-5480",
                "SDCL-3577",
                "SDEE-4688",
                "SNEQ-2773",
                "SNMF-5593",
                "SMVX-6871",
                "SWJY-3249",
                "QBLP-6063",
                "EOAD-5250",
                "NRLB-9453",
                "SKKV-5957",
                "PCDS-3662",
                "JARG-2377",
                "JDFU-3244",
                "OTTA-2366",
                "JGAQ-8909",
                "GAAR-3344",
                "CBSA-3179",
                "WSCW-5184",
                "JCFQ-3160",
                "YUYQ-1141",
                "PJIX-6930",
                "VOSB-7537",
                "AGWF-4003",
                "PSQE-5904",
                "ROVZ-4665",
                "SRNQ-6823",
                "ABVY-2534",
                "AGOQ-1417",
                "AGEQ-4193",
                "AKCH-1154",
                "ALVQ-4214",
                "AMVG-7768",
                "AVJB-8767",
                "ADGE-9257",
                "AAZD-3865",
                "AMFR-7464",
                "ASPY-7439",
                "AFEQ-5573",
                "AMSJ-8067",
                "AMED-5346",
                "AEXY-3202",
                "BGEC-6931",
                "BEMM-8537",
                "BDZO-3359",
                "BGQV-2403",
                "BMEO-6321",
                "BTOA-5703",
                "BWZN-4839",
                "BBHA-8212",
                "BLGF-6097",
                "BHID-7854",
                "BJRL-2406",
                "BNZL-2117",
                "BSEX-8458",
                "BKDV-5512",
                "BMXH-4543",
                "BDOX-9975",
                "BFUH-1650",
                "BGRR-9036",
                "BMLN-4627",
                "BAVO-1946",
                "BWBT-7695",
                "BSWL-6747",
                "BSKZ-2244",
                "ZJTL-6102",
                "ZAJQ-8167",
                "ZALS-1955",
                "ZRQH-7643",
                "ZSWS-7058",
                "ZEGA-2963",
                "ZFZQ-7871",
                "ZJFC-3853",
                "ZMIW-7195",
                "ZWRI-1334",
                "WCHC-8852",
                "WPSM-1197",
                "WWCM-8005",
                "WBIS-4100",
                "WCJE-2005",
                "WOSP-6018",
                "WMON-6315",
                "WCQE-4692",
                "WBHX-4595",
                "WKFH-8873",
                "WKQR-5538",
                "YKHU-8913",
                "YHXR-1076",
                "YRDD-9772",
                "YMYS-8337",
                "YTUG-6206",
                "YMGI-9609",
                "TKCY-3033",
                "TWDW-2462",
                "TMJN-8251",
                "TMBC-7139",
                "TCEW-2114",
                "TBFR-2531",
                "TCSU-2764",
                "TDQG-4176",
                "TBDC-8800",
                "TTEG-6027",
                "TCSY-1832",
                "TCFE-4168",
                "TBCM-2214",
                "TCWV-8198",
                "TBOS-2735",
                "THHZ-1643",
                "TSJT-3087",
                "TSZK-1257",
                "TFCG-3849",
                "TOYA-9091",
                "TSRH-9923",
                "TJZP-6673",
                "TLEC-8938",
                "TAZX-8253",
                "TBVQ-5909",
                "TMGC-3343",
                "TREX-5805",
                "TSMP-2797",
                "TCLH-1035",
                "TAYL-5139",
                "TKRD-5422",
                "THBD-7263",
                "TDOH-5651",
                "TFPR-6372",
                "TOUM-6903",
                "TBKE-4645",
                "TFMB-8866",
                "TWSL-1150",
                "TSPS-4328",
                "TWEQ-1996",
                "TLAP-9211",
                "TSKJ-3321",
                "TTBX-2929",
                "TMME-8172",
                "TSPB-3470",
                "TJNS-8144",
                "TMEL-4208",
                "TWRH-1263",
                "TPYB-4044",
                "TGHS-6984",
                "THTT-7382",
                "TFYP-3843",
                "TRTC-6765",
                "TLSW-5017",
                "TSFO-9284",
                "TMKV-1913",
                "TDWZ-6957",
                "TJCT-1328",
                "TNIG-9069",
                "TSSW-9554",
                "TGTU-4672",
                "TDYA-7148",
                "TDLK-4152",
                "SBXF-3065",
                "SBTB-8445",
                "SONE-2450",
                "SPKV-4958",
                "SBUW-5212",
                "STTF-8269",
                "SWEH-8976",
                "SLUE-5790",
                "QXQL-1295",
                "QLWJ-2071",
                "EBMC-9785",
                "LTGI-5819",
                "DKAK-2866",
                "ROJY-8320",
                "CHVJ-7399",
                "KFLH-1436",
                "EHNA-9857",
                "IFEQ-3247",
                "LFEU-2563",
                "VSYZ-3390",
                "ADWJ-4858",
                "IUBQ-1370",
                "BBLZ-1052",
                "MYYL-9055",
                "KDNP-4391",
                "KMXY-2571",
                "MLRW-8480",
                "GKHA-8321",
                "TOEW-6599",
                "ACGE-3319",
                "ADHN-6307",
                "AFHS-3937",
                "AGPO-8242",
                "AGNL-9012",
                "AHBC-4271",
                "AHNF-2485",
                "AKCT-7573",
                "ALMK-9710",
                "ALJZ-1284",
                "AHCN-8409",
                "AAFV-4870",
                "ABUS-9032",
                "AAAT-9526",
                "AWQM-4612",
                "ADHR-6976",
                "BHBN-6671",
                "BCBF-7462",
                "BCBT-2312",
                "BCBE-2044",
                "BHNI-2646",
                "BKEK-5476",
                "BMUE-2210",
                "BNIW-6850",
                "BRVX-7931",
                "BREJ-1956",
                "BRDE-2752",
                "BWBZ-6757",
                "BLHL-6743",
                "BAWZ-2287",
                "BBEQ-5758",
                "BTFE-4432",
                "BDLH-9200",
                "BJUB-9834",
                "ZTJZ-5003",
                "ZSJQ-4375",
                "ZKXD-2299",
                "ZLVI-2220",
                "ZRFC-2242",
                "ZASG-4886",
                "ZFTE-3314",
                "ZMCA-3087",
                "ZDDX-5087",
                "WKTL-6848",
                "WYEE-4192",
                "WHYP-1802",
                "WCPA-3784",
                "WJZI-2403",
                "WLHL-8857",
                "WMFZ-8141",
                "WTLQ-3250",
                "WWAA-4194",
                "WWZB-3539",
                "XJES-8448",
                "XAFI-8690",
                "YHLU-7741",
                "YPAA-3311",
                "TEHA-6065",
                "TMFF-7084",
                "TSYT-9594",
                "TGUB-2802",
                "TMWN-3373",
                "TFZZ-8738",
                "TJGA-7235",
                "TJSI-9594",
                "TGQF-9511",
                "TJYJ-7738",
                "TSMW-6174",
                "TTGG-4505",
                "TSHA-1048",
                "TQJV-6220",
                "TBYN-8876",
                "TWRZ-4568",
                "THMT-3317",
                "TWOG-1069",
                "TAKD-4544",
                "TMMI-8274",
                "TCUR-2453",
                "TWQO-9285",
                "TLNA-7728",
                "TDSJ-1926",
                "TSKW-7562",
                "TMWF-9434",
                "TEFL-4057",
                "TCWZ-9525",
                "TAQS-1438",
                "TBKK-2467",
                "TCLS-3729",
                "TJHP-3525",
                "TMPB-6334",
                "TOMO-4398",
                "TRPJ-9124",
                "TTDB-1197",
                "TOON-1249",
                "TDSD-4886",
                "TGJD-6122",
                "TLFK-1483",
                "TWLF-4284",
                "TWZX-2141",
                "TRMN-2329",
                "TNIJ-4258",
                "TWSB-2313",
                "TTNM-4249",
                "TEIT-4716",
                "TSVE-5426",
                "SHQS-4203",
                "SHVX-5738",
                "SBFH-9214",
                "SHTK-4053",
                "SFPK-1597",
                "TCGJ-9483",
                "RDHR-8822",
                "RCNA-3772",
                "CXGK-9675",
                "AGGI-2118",
                "GMQC-8099",
                "ASLG-9145",
                "HQHP-5898",
                "PCJH-7788",
                "KBKV-4102",
                "SDBS-9470",
                "AFAN-5152",
                "AGBI-4517",
                "AGKK-8964",
                "AGTU-7499",
                "ALIQ-7765",
                "ACAI-5585",
                "AMKS-3871",
                "APEH-1073",
                "AJTF-1088",
                "BMZZ-2312",
                "BJIB-5483",
                "BMUT-5590",
                "BBJX-6056",
                "BHFK-4937",
                "ZZMM-1264",
                "ZLBT-6736",
                "ZDJL-5376",
                "ZHDC-3245",
                "ZSZE-5989",
                "ZSOX-9419",
                "WLUH-8301",
                "WGLL-6229",
                "WWNW-1797",
                "WDOQ-4233",
                "WCMW-7103",
                "WCST-9119",
                "WALD-4628",
                "WGJY-3610",
                "WHZI-2200",
                "WNQN-7250",
                "WWLV-5152",
                "WNSS-8032",
                "TBGS-8488",
                "TDXB-8531",
                "TSPQ-7122",
                "TLKQ-2564",
                "TBVY-8056",
                "THOD-5753",
                "TBUF-6785",
                "TEVA-7123",
                "TWSN-8492",
                "TSEH-5680",
                "TJDF-9862",
                "TCDT-4893",
                "TOJL-1321",
                "TCBI-2959",
                "TDRA-3593",
                "TMTC-5215",
                "TWAJ-6471",
                "TRCC-3338",
                "TRPB-8523",
                "TLAQ-4860",
                "TBOV-9898",
                "TCFL-7729",
                "TDEQ-1718",
                "TGEH-2500",
                "TLJN-5317",
                "TLBY-1915",
                "TMTS-9296",
                "TOBO-7549",
                "TMMK-8293",
                "TFXC-7923",
                "TBEB-7920",
                "TMDO-1011",
                "TRYV-6178",
                "TECK-9188",
                "TDZI-7760",
                "SHSP-3102",
                "SHNQ-2304",
                "SBST-4337",
                "SRPY-7829",
                "DHGP-2504",
                "ZGXD-9274",
                "DBNK-4261",
                "ARFS-2013",
                "TKWG-2792",
                "RSHZ-9073",
                "AFUX-5340",
                "KDVQ-6191",
                "VWOW-3079",
                "VMAR-2382",
                "SDMN-8522",
                "ADIF-8995",
                "AGCC-7959",
                "AKIH-8232",
                "ALUQ-4385",
                "ARFR-5308",
                "ASLJ-2920",
                "BNMN-5986",
                "BWDU-8810",
                "ZBJR-1410",
                "ZCIF-7861",
                "ZSTV-6712",
                "WAGN-2315",
                "WMDO-5668",
                "WGBL-8123",
                "WDGN-9833",
                "WMSA-6036",
                "YAQT-5637",
                "TBIP-3406",
                "THKV-5373",
                "TLWU-9868",
                "TLTW-8833",
                "TMNG-5319",
                "TFRB-9605",
                "TAEJ-6527",
                "TDGD-4437",
                "TEUK-8932",
                "TGDV-9975",
                "TKKY-1591",
                "TLDE-5756",
                "TMFA-8313",
                "TMDV-9721",
                "TPKH-6415",
                "TPWM-2642",
                "TREY-2655",
                "TLCG-4936",
                "TWXD-1261",
                "TNWT-9025",
                "TBGI-9344",
                "TMNU-6389",
                "TCHY-6662",
                "TEWN-2301",
                "TSGI-6963",
                "JYXQ-5201",
                "KMTE-9650",
                "EJYY-1249",
                "KZCW-4319",
                "JIHG-6946",
                "RRJX-8051",
                "TEGA-4124",
                "ALEB-9316",
                "ALJD-2977",
                "AVYO-2363",
                "AWWL-9892",
                "BRKG-8430",
                "ZCTS-9216",
                "ZSNF-9552",
                "ZSNJ-3858",
                "ZYGY-9242",
                "ZDFJ-7304",
                "TWHI-8098",
                "TSHI-3083",
                "TBGE-6049",
                "TMJS-9858",
                "TLDN-7157",
                "TRMV-3566",
                "KQMO-5614",
                "KQEP-8785",
                "ZCXA-8964",
                "ZXQA-2067",
                "TLYP-5028",
                "TRYL-3108",
                "TOKA-1252",
                "GLHJ-1619",
                "GVUC-9926",
                "TVWB-1501",
                "ZKUO-3266"
        };
    }
}
