package me.quyen.entities.fakadata;

import java.util.concurrent.ThreadLocalRandom;

public class CourseData {
    public static String courseName(){
        return namesAndCodes()[0];
    }
    public static String courseCode(){
        return namesAndCodes()[1];
    }
    public static String[] namesAndCodes(){
        int chosenInt = Math.min(courseCodes().length, courseNames().length);
        int rInt = ThreadLocalRandom.current().nextInt(0, chosenInt);
        return new String[]{courseNames()[rInt],courseCodes()[rInt]};
    }
    public static String[] courseNames(){
        return new String[]{
                "Advanced Security",
                "Algorithmic Foundations of Collective Decision Making",
                "Algorithms and Data Structures",
                "Artificial Intelligence",
                "Categories, Proofs and Processes",
                "Combinatorial Optimisation",
                "Compilers",
                "Computational Biology",
                "Computational Complexity",
                "Computational Game Theory",
                "Computational Learning Theory",
                "Computational Medicine",
                "Computer Architecture",
                "Computer Graphics",
                "Computer Security",
                "Computer Vision",
                "Computer-Aided Formal Verification",
                "Concurrent Algorithms and Data Structures",
                "Concurrent Programming",
                "Continuous Mathematics",
                "Data Visualisation",
                "Database Systems Implementation",
                "Databases",
                "Deep Learning in Healthcare",
                "Design and Analysis of Algorithms",
                "Digital Systems",
                "Discrete Mathematics",
                "Distributed Processes, Types and Programming",
                "Foundations of Self-Programming Agents",
                "Functional Programming",
                "Geometric Deep Learning",
                "Geometric Modelling",
                "Graph Representation Learning",
                "Group Design Practical",
                "Imperative Programming",
                "Introduction to Proof Systems",
                "Knowledge Representation & Reasoning",
                "Lambda Calculus and Types",
                "Law and Computer Science",
                "Linear Algebra",
                "Logic and Proof",
                "Machine Learning",
                "Mathematics for Computer Science and Philosophy",
                "Models of Computation",
                "Practicals",
                "Principles of Programming Languages",
                "Probabilistic Model Checking",
                "Probability and Computing",
                "Projects",
                "Quantum Information",
                "Quantum Processes and Computation",
                "Quantum Software",
                "Aeronautics and Astronautics",
                "Aerospace Studies",
                "Anthropology",
                "Architecture",
                "Biological Engineering",
                "Biology",
                "Brain and Cognitive Sciences",
                "Chemical Engineering",
                "Chemistry",
                "Civil and Environmental Engineering",
                "Comparative Media Studies / Writing",
                "Computational and Systems Biology",
                "Computational Science and Engineering",
                "Concourse",
                "Data, Systems, and Society",
                "Earth, Atmospheric, and Planetary Sciences",
                "Economics",
                "Edgerton Center",
                "Electrical Engineering and Computer Science",
                "Engineering Management",
                "Experimental Study Group",
                "Global Languages",
                "Health Sciences and Technology",
                "History",
                "Humanities",
                "Linguistics and Philosophy",
                "Literature",
                "Management",
                "Materials Science and Engineering",
                "Mathematics",
                "Mechanical Engineering",
                "Media Arts and Sciences",
                "Military Science",
                "Music and Theater Arts",
                "Naval Science",
                "Nuclear Science and Engineering",
                "Physics",
                "Political Science",
                "Science, Technology, and Society",
                "Supply Chain Management",
                "Urban Studies and Planning",
                "Women's and Gender Studies",
                "Biology of Cells",
                "Evolution and Behaviour",
                "Mathematical Biology",
                "Physiology of Organisms",
                "Biochemistry Molecular Biology",
                "Biology of Disease",
                "Cell Developmental Biology",
                "Ecology, Evolution Conservation",
                "Evolution Animal Diversity",
                "Experimental Psychology",
                "Mathematical Computational Biology",
                "Neurobiology",
                "Pharmacology",
                "Physiology",
                "Plant Microbial Sciences",
                "Biochemistry",
                "Genetics",
                "Pathology",
                "Physiology, Development Neuroscience",
                "Plant Sciences",
                "Psychology",
                "Zoology",
                "Biological Biomedical Sciences",
                "Systems Biology",
                "African American Studies",
                "African Studies",
                "American Studies",
                "Applied and Computational Mathematics",
                "Architecture and Engineering",
                "Art and Archaeology",
                "Asian American Studies",
                "Astrophysical Sciences",
                "Atmospheric and Oceanic Sciences",
                "Bioengineering",
                "Biophysics",
                "Chemical and Biological Engineering",
                "Chinese Language",
                "Classical Philosophy",
                "Classics",
                "Climate Science",
                "Cognitive Science",
                "Comparative Literature",
                "Computer Science",
                "Contemporary European Politics and Society",
                "Creative Writing",
                "Dance",
                "East Asian Studies",
                "Ecology and Evolutionary Biology",
                "Electrical and Computer Engineering",
                "Engineering Biology",
                "Engineering Physics",
                "English",
                "Entrepreneurship",
                "Environmental Studies",
                "European Cultural Studies",
                "Finance",
                "French and Italian",
                "Gender and Sexuality Studies",
                "Geological Engineering",
                "Geosciences",
                "German",
                "Global Health and Health Policy",
                "Health and Health Policy",
                "Hellenic Studies",
                "History and the Practice of Diplomacy",
                "History of Science",
                "History of Science, Technology and Medicine",
                "Humanistic Studies",
                "Interdisciplinary Humanities",
                "Italian Studies",
                "Japanese Language",
                "Journalism",
                "Judaic Studies",
                "Korean Language",
                "Language and Culture",
                "Latin American Studies",
                "Latino Studies",
                "Linguistics",
                "Mechanical and Aerospace Engineering",
                "Media and Modernity",
                "Medieval Studies",
                "Molecular Biology",
                "Music",
                "Music Composition",
                "Music Performance",
                "Musicology",
                "Near Eastern Studies",
                "Neuroscience",
                "Operations Research and Financial Engineering",
                "Optimization and Quantitative Decision Science",
                "Philosophy",
                "Planets and Life",
                "Plasma Physics",
                "Politics",
                "Population Studies",
                "Public Policy and International Affairs",
                "Quantitative and Computational Biology",
                "Quantitative Economics",
                "Religion",
                "Robotics and Intelligent Systems",
                "Russian, East European and Eurasian Studies",
                "Science, Technology and Environmental Policy",
                "Slavic Languages and Literatures",
                "Social Policy",
                "Sociology",
                "South Asian Studies",
                "Spanish and Portuguese",
                "Statistics and Machine Learning",
                "Sustainable Energy",
                "Teacher Preparation",
                "Technology and Society",
                "Theater and Music Theater",
                "Translation and Intercultural Communication",
                "Urban Policy",
                "Urban Studies",
                "Values and Public Life",
                "Visual Arts",
                "History and Economics",
                "History and English",
                "History and Modern Languages",
                "History and Politics",
                "History of Art",
                "Human Sciences",
                "Earth Sciences (Geology)",
                "Economics and Management",
                "Engineering Science",
                "English Language and Literature",
                "English and Modern Languages",
                "European and Middle Eastern Languages",
                "Classical Archaeology and Ancient History",
                "Classics and Asian and Middle Eastern Studies",
                "Classics and English",
                "Classics and Modern Languages",
                "Computer Science and Philosophy",
                "Materials Science",
                "Mathematics and Computer Science",
                "Mathematics and Philosophy",
                "Mathematics and Statistics",
                "Medicine",
                "Medicine (graduate entry)",
                "Modern Languages",
                "Modern Languages and Linguistics",
                "Philosophy and Modern Languages",
                "Philosophy, Politics and Economics (PPE)",
                "Philosophy and Theology",
                "Physics and Philosophy",
                "Psychology (Experimental)",
                "Psychology, Philosophy and Linguistics",
                "Adult Emergency Care",
                "Advanced Clinical Decision Making",
                "Advanced Communication and Supportive Relationships",
                "Advanced Health Promotion",
                "Advanced History Taking and Assessment",
                "Advanced Research Design",
                "Advancing Professional Practice",
                "Care at the End of Life",
                "Care of Deteriorating or Acutely Unwell Adult",
                "Children's Emergency Care",
                "Coaching and Mentoring in Health and Social Care",
                "Communicable Diseases and Public health",
                "Community Empowerment and Advocacy",
                "Data Analysis and Interpretation",
                "Diagnostic Reasoning in Practice",
                "Epidemiology",
                "Epidemiology and Research Methods",
                "Evidence Based Practice",
                "Fundamentals of Human Nutrition",
                "Foundations in Public Health",
                "Health Promotion",
                "Leadership in Health and Social Care",
                "Mastering Professional Practice",
                "Operational Management in Health and Social Care",
                "Organisational Resource Management in Health Social Care",
                "Planning and Managing Clinical Trials",
                "Practice Educator Professional Standards PEPS Stage 1",
                "Practice Educator Professional Standards PEPS Stage 2",
                "Psychosocial Care of Children, Adolescents and their Families",
                "Public Health Leadership",
                "Public Health Policy",
                "Risk and the protection of children",
                "SACT Administration and Patient Care - Postgraduate",
                "Simulation Based Education",
                "Ancient Egyptian Art and Archaeology",
                "An Architectural Exploration",
                "Develop a Creative Practice",
                "Drawing the Realistic Figure",
                "Painting from Observation",
                "Create and Produce Your Own Podcast",
                "Beginning Drawing",
                "Exploring the Dynamic Relationship between Artists and AI",
                "Drawing the Human Face",
                "Creativity in the Age of AI",
                "Strategies and Skills for Excellence",
                "For Fractional and Full-Time Founders",
                "Aligning Skills to Opportunities",
                "Aim High and Achieve Impact",
                "The Key to Successful Innovation",
                "Building People-Centric Organizations",
                "Essential Skills to Lead and Influence",
                "Clarity and Action in Business Decisions",
                "The Essentials of Wealth Management",
                "Social Media, SEO, Content, and Advertising",
                "Achieve Outstanding Results and Relationships",
                "Financial Basics for Business Management",
                "Learn from Experienced Silicon Valley Practitioners",
                "Learning to Think Three Steps Ahead",
                "Architect, Navigator, Data Scientist",
                "Creating a Frictionless Customer Experience",
                "Introduction to Project Management",
                "Intellectual Property in the AI Era",
                "Connecting Data Analytics with Managerial Success",
                "Fundamentals of Product Management",
                "Building and Maintaining Wealth",
                "From Antigone to Oedipus at Colonus",
                "Life, Death, and Afterlife of a Roman City",
                "Medicine in the Ancient Western World",
                "Owning Your Truth",
                "Writing about Small Things in Big Ways",
                "Storytelling and Imagery",
                "Take the Next Steps",
                "Taking Inspiration from the Masters",
                "A Ticket to the Truth",
                "Techniques and Secrets",
                "An Experiential Workshop",
                "Accent Reduction for Non-Native English Speakers",
                "An Improviser’s Guide to Business and Communication",
                "The Science of Being Memorable and Influencing Decisions",
                "Design for Maximum Impact",
                "The Power of Body Language and Voice",
                "Become an Empowered and Confident Communicator",
                "The Art and Craft of Literary Journalism",
                "Create Your Style",
                "Establishing a Creative Writing Practice",
                "A One-Week Intensive",
                "Taking Risks, Bending Rules",
                "Mastering Subplot in Novels and Memoirs",
                "Pitch Your Essays and Articles",
                "Introduction to Hip Hop Dance",
                "From Inspiration to Implementation",
                "Preserving Summer's Harvest",
                "Style, Dialogue, and Point of View",
                "The Past Is Never Past",
                "Crafting Unforgettable Short Fiction",
                "The Beginning, the End, and Everything in Between",
                "Five Stories in Five Weeks",
                "The Birth of a Golden Age",
                "Films Critics Missed but Viewers Loved",
                "Politics, Culture, and the Power of Documentary Filmmaking",
                "Part I",
                "The History of Fascism",
                "The World’s Most Powerful and Extraordinary Books",
                "Eleanor Roosevelt and Her World",
                "Policy Perspectives on the Psychedelic Renaissance",
                "George Eliot’s Middlemarch",
                "Literary Voices of Ukraine",
                "A Practical Introduction to Music Theory and Harmony",
                "Application to the Memoir Writing Certificate Program",
                "Novel Writing for Absolute Beginners",
                "Plot and Structure",
                "Capturing the YA Voice",
                "Application to the Novel Writing Certificate Program",
                "Novel",
                "A Philosophical Exploration of AI and Consciousness",
                "Historical and Contemporary Perspectives",
                "Around the Corner and Around the World",
                "Using Your Smartphone to Make Extraordinary Images",
                "Beginning Digital Photography",
                "Finding Inspiration in Life’s Contradictions",
                "Poetry as Play",
                "An Overview of Modern Psychotherapy Approaches",
                "The Neuroscience of Emotions and Regulation",
                "Recent Developments in Research and Treatment",
                "Exploring the Science of Aging",
                "Exercise Theory and Design for Health and Fitness",
                "Revolutionary Ideas about Our Planet's Past, Present, and Future",
                "Exploring the Thorax",
                "From Peri to Post",
                "Sports Management and Leadership in the Changing World of College Athletics",
                "Stanford Distinguished Faculty Lecture Series",
                "Building Your First Robot",
                "Statistics for AI, Machine Learning, and Data Science",
                "A Crash Course in AI",
                "Large Language Models for Business with Python",
                "A Practical Introduction to Python",
                "User-Centered Design for AI Applications",
                "Storing, Tracking, and Collaborating on Software Projects",
                "Early Insights from the Stanford Institute for Human-Centered Artificial Intelligence",
                "Applied AI Essentials",
                "From Script to Final Cut",
                "Build Habits to Serve Your Late-Life Brain",
                "A Journey to Everyday Confidence, Calm, and Connection",
                "Embracing Improvisation and Storytelling on the Stanford Campus",
                "A Practical and Evidence-Based Approach",
                "Science-Based Strategies for Boosting Positive Emotions",
                "A Creative Approach to End-of-Life Planning",
                "British Economic Development",
                "Command Economies",
                "Comparative Economic Systems",
                "Corporate Finance",
                "Development Economics",
                "Econometrics",
                "Economic Statistics",
                "Economics of Development (specify)",
                "Economics of the European Union",
                "Economics of Health Care",
                "Economics of Industry",
                "Economics of the Monarchy",
                "Free Market Economics",
                "Game Theory Economics",
                "Industrial Managerial Economics",
                "International Finance",
                "International Economic Relations",
                "International Industrial Organization",
                "International Macroeconomics",
                "International Trade Finance",
                "International Trade",
                "International Trade Macroeconomics",
                "Introductory Econometrics",
                "Macroeconomics",
                "Managerial Economics",
                "Microeconomics",
                "Monetary Economics",
                "Arthurian Literature",
                "Arthurian Literature Poetry",
                "British and Irish Poetry",
                "British Colonialist Literature",
                "British Drama (specify period)",
                "British Modernist Literature",
                "British Novel",
                "British Poetry (specify)",
                "British Post-War Drama",
                "Brontes",
                "C S Lewis",
                "C17th Lyric Poetry",
                "C17th Religious Writers",
                "C18th 19th British Novels",
                "C19th 20th British Poetry",
                "C19th English Fiction",
                "C19th Narrative Fiction",
                "C19th Novel",
                "C20th Autobiography",
                "C20th British Literature",
                "C20th British Novel",
                "C20th British Poetry",
                "C20th Catholic Writers",
                "C20th English Novel",
                "C20th Irish Literature",
                "C20th Literature",
                "C20th Novelists",
                "C20th Writing",
                "Canterbury Tales",
                "Chaucer",
                "Chaucer’s Canterbury Tales",
                "Children’s Literature",
                "Classic 19th C Novels",
                "Classical Narrative",
                "Contemporary British Irish Poetry",
                "Contemporary British Drama",
                "Contemporary Fiction",
                "Contemporary Modernist Fiction",
                "Contemporary British Novel",
                "Contemporary British Poets",
                "Contemporary Literary Theory",
                "Contemporary Novel Theory",
                "Creative Writing (Poetry)",
                "Creative Writing (Prose)",
                "Crime Fiction",
                "Critical Theory and its Application",
                "Critical Theory",
                "D H Lawrence",
                "Dante’s Divine Comedy",
                "Dickens",
                "Dryden",
                "E M Forster",
                "Early Milton Poetry Paradise Lost",
                "Early Modern British Fiction",
                "Eliot Hardy",
                "Eliot and Yeats",
                "Elizabethan Poetry",
                "English Literature 1640-1850",
                "English Literature 1890-1930",
                "English Novel (specify period, authors)",
                "English Poetry (specify period, authors)",
                "English Renaissance Literature",
                "English Romantic Literature",
                "English Romantic Poetry",
                "Fiction 19th C (specify authors)",
                "Fiction of C S Lewis",
                "George Orwell",
                "James Joyce",
                "James Joyce Dylan Thomas",
                "Jane Austen",
                "Jane Austen The Brontes",
                "John Donne",
                "Joyce’s Ulysses",
                "Late 19th C British Drama Prose",
                "Literary Analysis",
                "Literary Critical Theory",
                "Literary Theory",
                "Medieval Arthurian Literature",
                "Medieval non-Chaucerian Literature",
                "Milton",
                "Modern British Literature",
                "Modern British Novel",
                "Modern British Drama",
                "Modern Novel",
                "Modern Short Story",
                "Modern Irish Drama",
                "Modernism in English Literature",
                "Modernist Fiction",
                "Modernist Novel",
                "Oscar Wilde Bernard Shaw",
                "Paradise Lost",
                "Play Reading Creative Writing",
                "Poetic Analysis",
                "Poetry Analysis Creative Writing",
                "Poetry of John Donne",
                "Post 1830 English Literature",
                "Post Colonial Literature in England",
                "Post Modern Theory Novel",
                "Rebellion Restoration",
                "in English Literature",
                "Reformation in Europe",
                "Renaissance Literature",
                "Restoration Drama",
                "Rhetoric of 19th 20th C Fiction",
                "Shakespeare (specify)",
                "Shakespeare Characterization",
                "Shakespeare the Roman World",
                "Shakespeare’s Comedies",
                "Shakespeare’s Last Plays",
                "Shakespeare’s Tragedies",
                "Shaw Ibsen",
                "Short Story",
                "Short Story Analysis Writing",
                "Short Story C20th",
                "Sonnet and English Poetry",
                "T S Eliot Other Poets",
                "Thomas Hardy Dickens",
                "Time in 20th C Literature",
                "TS Eliot Related Poets",
                "Victorian Fiction",
                "Victorian Literature",
                "Virginia Woolf",
                "William Wordsworth Anne Finch",
                "Woolf",
                "Woolf, Joyce Lawrence",
                "Abnormal Psychology",
                "Animal Behaviour",
                "Behavioural Disorders",
                "Brain and Behaviour",
                "Clinical Psychology (specify)",
                "Cognitive Neuroscience (specify)",
                "Cognitive Psychology (specify)",
                "Developmental Psychology",
                "Educational Psychology",
                "Experimental Analysis (specify)",
                "Gender Differences in Psychology",
                "Gender Issues in the Third World",
                "Human Evolution",
                "Human Information Processing",
                "Immune System",
                "Individual Differences",
                "Perspectives of Childhood",
                "(specify discipline)",
                "Psychiatric Disorders (specify)",
                "Psychological Therapies (specify)",
                "Psychology of Adolescence",
                "Psychological Disorders",
                "Psychology of Gender",
                "Psychology of Personality",
                "Social Behaviour",
                "Social Psychology",
                "Social Psychology Behaviour",
                "Treatment of Psychological Disorder",
                "Environmental Change and Problems",
                "Environmental Geography",
                "Environmental Issues",
                "Geographical Environment",
                "Human Urban Geography (specify)",
                "Principles of Social Geography",
                "Social Geography",
                "Urban Geography",
                "Ancient Near Eastern History",
                "Anglo-American Relations 1914-60",
                "Anglo-Irish Relations 1880-1922",
                "Anglo-Saxon England",
                "Arthur: Historical Background",
                "Arthur: Medieval to Modern",
                "Britain America in the 18th C",
                "Britain the Cold War",
                "British Empire 1800-1947",
                "British History 400-1330",
                "British History 1850-1940",
                "British History 1900-1950",
                "British History Since 1870",
                "British Imperial History (specify)",
                "British Imperialism Decolonization",
                "British Imperialism (specify)",
                "British India to Independence",
                "British Political History (specify)",
                "British Political History Since 1945",
                "British Post-War History",
                "British View of WW ll",
                "C18th Culture Society",
                "C18th English History",
                "C18th 19th British Social History",
                "C19th British India",
                "C19th French Social History",
                "C19th Socialist Radical Thought",
                "C19th 20th British Political History",
                "C20th Social Change in Britian",
                "C20th British History",
                "C20th European History",
                "Colonialism Nationalism in India",
                "Church Govt Society C16th England",
                "Culture Society in 18th C England",
                "Early Modern British History",
                "Early Modern Women’s History Eastern Europe Since 1945",
                "Edwardian History",
                "Elizabethan History",
                "English Civil War Background",
                "English History 1066-1275",
                "European History 1500-1900",
                "European History Post 1945",
                "French History Politics 1870-1914",
                "French History 1789-1848",
                "French Revolution",
                "History of East Europe 1945-Present",
                "History of World War 2",
                "Hitler Fascism",
                "Holocaust",
                "International History 1882-1939",
                "Interwar Fascism",
                "Irish History 1880-1922",
                "Late 19th C Japan",
                "Modern European Politics History",
                "Modern History (specify)",
                "Modern British Social History",
                "Mussolini Italian Fascism",
                "Origins of Industrial Revolution",
                "Post 1945 Britain",
                "Post 1945 State Welfare in the UK",
                "Social Class in Britain",
                "The Crusades",
                "Third Reich",
                "Thirty Years’ War",
                "Tudor History",
                "Tudor Early Stuart England",
                "Tudor Stuart History",
                "Tudor Stuart Social History",
                "Victorian Edwardian History",
                "Victorian Britain",
                "Victorian British Women’s History",
                "Victorian Social History",
                "Wales in Tudor England",
                "War, Peace Social Change in Britain (specify period)",
                "Wars Since 1945",
                "Women’s History (specify)",
                "Women in 16th C England",
                "Women in the Middle Ages",
                "World War I",
                "World War II",
                "WW II Anglo – American Relations",
                "African Politics (specify countries or area)",
                "Arab – Israeli Relations",
                "Britain the European Union (specify discipline: politics or economics)",
                "Cold War Diplomacy",
                "East European Politics Economics",
                "East West Relations Since 1945",
                "Eclipse of GB as a World Power",
                "Economic History of Europe 1918-39",
                "Economics of Eastern Europe",
                "European Union",
                "European Union Law",
                "Europe Economic Integration",
                "European Economic Community",
                "European Integration",
                "European Interwar Thought (specify)",
                "European Modernism",
                "European Monetary Integration",
                "European Reformation",
                "Industrial Relations in the EU",
                "International Relations (specify countries)",
                "International Relations During WW2",
                "International Relations Since 1945",
                "Middle Eastern Politics",
                "Politics of the European Union",
                "Politics Govt of Israel",
                "Politics of Modern India",
                "Soviet Post Soviet Politics (specify)",
                "Soviet Union 1917-1991",
                "State in Early Modern Europe",
                "War Diplomacy in Europe",
                "Warfare in Europe (specify period)",
                "Warsaw Pact NATO",
                "Ancient Greek Philosophy",
                "Ancient Logic",
                "Aristotle",
                "British Empiricists",
                "British Political Philosophy (specify)",
                "C17th 18th Philosophy",
                "C18th Political Theory",
                "C19th German Philosophers",
                "C19th Philosophy",
                "Contemporary Aesthetics",
                "Descartes to Kant",
                "Descartes’ Meditations",
                "Epistemology Metaphysics",
                "Ethical Theory",
                "Ethics",
                "Existentialism",
                "Freud, Nietzsche Existentialism",
                "German Philosophy",
                "Greek Drama Philosophy",
                "Greek Philosophy",
                "Heiddegger, Sartre Derrida",
                "History of Philosophy",
                "Jean-Paul Sartre",
                "Kant and the German Idealists",
                "Locke, Hobbes Rousseau",
                "Logic",
                "Marx Hegel",
                "Marxism",
                "Metaphysics",
                "Modern Philosophy (specify)",
                "Moral Philosophy (specify)",
                "Nietzsche",
                "Perspectives on Morality",
                "Philosophy of Hegel",
                "Philosophy of Human Nature",
                "Philosophy of Kant",
                "Philosophy of Language",
                "Philosophy of Law",
                "Philosophy of Mind Psychology",
                "Philosophy of Perception",
                "Philosophy of Personal Identity",
                "Philosophy of Religion",
                "Philosophy of Science",
                "Philosophy of Wittgenstein Plato",
                "Plato and Aristotle",
                "Plato’s Republic",
                "Political Philosophy (specify)",
                "Political Theory and Thought",
                "Political Thought C17th 18th",
                "Post Kantian German Philosophy",
                "Schopenhauer Nietzsche",
                "Studies in Logical Theory",
                "Studies in Wittgenstein",
                "British Domestic Politics WW2",
                "British Foreign Policy Since 1945",
                "British Govt Politics Since 1880",
                "British Politics Govt Since 1945",
                "British Politics 1970-1999",
                "Classical Political Theory",
                "Classical Political Thought",
                "Comparative Government",
                "Comparative Labour Economics",
                "Contemporary Political Thought",
                "European Union Politics Govt",
                "Game Theory of Politics",
                "History of W Political Thought",
                "Machiavelli – Rousseau",
                "Modern British Government",
                "Modern British Govt Politics",
                "Political Fiction of Cold War",
                "Political Movements (specify)",
                "Post War Changes in E Europe",
                "Biochemisty",
                "Cardio-Vascular Physiology",
                "Cell Biology (specify)",
                "Developmental Biology",
                "Genetics Biology",
                "Molecular Immunology",
                "Organic Chemistry",
                "Pharmacology (specify)",
                "Probability Statistics",
                "Proofs in Abstract Mathematics",
                "Pure Applied Algebra",
                "Statistical Survey Method",
                "British Women Writers (specify period)",
                "C20th Feminist Theory",
                "C20th Women Writers",
                "English Women Writers (specify period)",
                "Feminist Post Colonial Theory",
                "Feminist Issues (specify)",
                "Feminist Literature",
                "Feminist Theory",
                "Feminist Theory Criticism",
                "Feminist Theory for the 21st C",
                "Feminist Thought",
                "Feminist Writers in the UK",
                "Jane Austen Charlotte Bronte",
                "Medieval Women Writers",
                "Modern Women’s Writing: The Novel",
                "Post Colonial Feminist Theory",
                "Readings in British Feminism",
                "Renaissance Women Writers",
                "Shakespeare Feminist Theory Women in Changing Society",
                "Women in Shakespeare",
                "Women in the Bible",
                "Women Victorian Poets",
                "Women’s Experience in the Novel",
                "Women’s Literature (specify)",
                "Women’s Literature From 1640",
                "Women’s Writing C20th",
                "Anglo-Saxon Archaeology",
                "British Health Care System",
                "Buddhism",
                "C19th 20th German Literature",
                "C19th English Architecture",
                "C19th Russian Literature",
                "Chinese Religion",
                "Comparative Health Policy",
                "Comparative Religion",
                "Comparative UK US Law",
                "Constitutionalism",
                "Contemporary SE Asia",
                "Criminology Deviant Behaviour",
                "Cultural Issues Weimar Germany",
                "Differential Equations",
                "Early Church",
                "Early Islamic History",
                "Economics Theology of the Early Church",
                "Elements of Critical Theory",
                "Ethnomusicology",
                "European Literature Cinema",
                "French Art : Late 19th C",
                "German Expressionist Painting",
                "German Language Linguistics",
                "German Literature Post 1945",
                "Greek Grammar",
                "Greek Intellectual History",
                "Greek: Language Literature",
                "Henry James",
                "Hinduism",
                "History Architecture of Oxford",
                "History of Art: Impressionism",
                "History of Art: Renaissance",
                "History of Economic Thought (specify)",
                "History of English Language",
                "History of European Community",
                "History of India (specify)",
                "History of Modern China (specify)",
                "History of Modern Economic Ideas (specify)",
                "History of Music (specify)",
                "History of Philosophy (specify)",
                "History of Political Thought",
                "History of the Early Church",
                "History of the Monarchy",
                "History of the Soviet Union",
                "History of the Warsaw Pact NATO",
                "History of Victorian London",
                "Homer Greek Mythology",
                "How The Rabbis Read The Bible",
                "Human Ecology",
                "Images of Jesus",
                "Intellectual History of Feminism",
                "Introduction to Criminology",
                "Introduction to English Law",
                "Introduction to Literary Theory",
                "Jurisprudence (specify)",
                "Latin: Language Literature",
                "Legal Issues in Free Speech",
                "Leonardo Da Vinci",
                "Literary Theory Philosophy",
                "Making of the American",
                "Constitution",
                "Medieval Archaeology",
                "Medieval Art Architecture",
                "Medieval Counterpoint",
                "Medieval English Drama",
                "Medieval Theology",
                "Middle English Language",
                "Modern Chinese Economic History",
                "Modern Chinese Politics",
                "Modern Drama",
                "Modern History of Africa",
                "Modern Islam",
                "Modern Jewish Literature",
                "Modernist Art",
                "Music of West Africa",
                "Mythology (specify)",
                "Mythology and Art History",
                "Mythology in Literary Texts",
                "Natural Health Care Systems",
                "Nelson Mandela and S African Politics",
                "Polish History Literature",
                "Polish Literature 1918-1990",
                "Post Modernism and the Visual Arts",
                "Post Modernism: Theory and Fiction",
                "Post Structuralism",
                "Post Structuralist Theory",
                "Pre- Raphaelite Art",
                "Pre- Raphaelite Movement",
                "Public International Law",
                "Reading in Augustine’s Confessions",
                "Renaissance Art",
                "Representations of the Holocaust",
                "Roman Elegy",
                "Russian Literature (specify)",
                "Social Change in Europe 1914-1942",
                "Social Hist Anthropology of India",
                "Socialism Capitalism",
                "Sociology of Health",
                "South Asian Politics",
                "St Augustine",
                "St Augustine: Theology Thought",
                "Talmud in Translation",
                "Theology of St Paul",
                "Theories Problems of Nationalism",
                "Ulysses",
                "Urban Anthropology",
                "Victorian Art Architecture",
                "Victorian Design",
                "Victorian England",
                "War Culture 1450-1620",
                "Zionist Thought History"
        };
    }
    public static String[] courseCodes(){
        return new String[]{
                "ASF-779",
                "AFA-772",
                "AAV-441",
                "AIQ-195",
                "CPV-855",
                "COM-178",
                "CEN-314",
                "CBP-108",
                "CCF-386",
                "CGI-652",
                "CLA-142",
                "CMW-449",
                "CAG-560",
                "CGI-303",
                "CSL-733",
                "CVH-377",
                "CFN-752",
                "CAX-244",
                "CPO-328",
                "CME-822",
                "DVZ-580",
                "DSM-542",
                "DLX-523",
                "DLL-327",
                "DAS-323",
                "DSN-797",
                "DMJ-470",
                "DPQ-873",
                "FOA-184",
                "FPG-867",
                "GDG-219",
                "GMA-572",
                "GRY-527",
                "GDL-559",
                "IPR-173",
                "ITQ-553",
                "KRJ-473",
                "LCS-675",
                "LAX-699",
                "LAD-572",
                "LAH-475",
                "MLH-701",
                "MFU-309",
                "MOK-167",
                "PCW-766",
                "POT-444",
                "PMP-195",
                "PAK-925",
                "PJB-410",
                "QIP-596",
                "QPC-524",
                "QSL-609",
                "AAR-760",
                "ASY-227",
                "AQD-730",
                "AMN-972",
                "BEV-781",
                "BHT-445",
                "BAA-579",
                "CEG-906",
                "CXL-253",
                "CAP-116",
                "CMB-808",
                "CAM-211",
                "CSQ-308",
                "CLD-974",
                "DSR-157",
                "EAW-705",
                "EYK-493",
                "ECH-428",
                "EER-772",
                "EMF-581",
                "ESF-719",
                "GLI-105",
                "HSX-202",
                "HHR-344",
                "HWG-692",
                "LAX-216",
                "LRD-529",
                "MPR-591",
                "MSE-126",
                "MPR-932",
                "MEP-939",
                "MAD-446",
                "MSU-725",
                "MAO-275",
                "NSM-706",
                "NSE-719",
                "PUU-956",
                "PSE-162",
                "STI-732",
                "SCO-967",
                "USN-849",
                "WAP-865",
                "BOW-931",
                "EAX-716",
                "MBD-673",
                "POQ-767",
                "BMF-205",
                "BOC-569",
                "CDX-534",
                "EEJ-229",
                "EAT-995",
                "EPW-542",
                "MCQ-867",
                "NAN-992",
                "PDW-919",
                "PVR-207",
                "PMR-278",
                "BPI-631",
                "GRG-362",
                "PLZ-940",
                "PDV-294",
                "PSD-129",
                "PMT-334",
                "ZFV-408",
                "BBZ-605",
                "SBR-874",
                "AAF-647",
                "ASO-451",
                "ASE-234",
                "AAP-816",
                "AAY-741",
                "AAE-682",
                "AAE-740",
                "ASO-928",
                "AAS-186",
                "BNL-743",
                "BIB-901",
                "CAK-644",
                "CLZ-179",
                "CPL-960",
                "CQP-420",
                "CSD-113",
                "CSK-350",
                "CLZ-920",
                "CSP-346",
                "CEM-749",
                "CWE-156",
                "DQL-260",
                "EAW-144",
                "EAL-259",
                "EAH-340",
                "EBD-329",
                "EPM-517",
                "EXO-704",
                "EOB-785",
                "ESE-945",
                "ECT-248",
                "FXN-603",
                "FAU-395",
                "GAD-973",
                "GEP-335",
                "GDR-124",
                "GGK-103",
                "GHG-553",
                "HAQ-425",
                "HSL-417",
                "HAB-127",
                "HOW-765",
                "HOR-338",
                "HSM-535",
                "IHO-240",
                "ISO-398",
                "JLN-357",
                "JBG-209",
                "JSB-759",
                "KLB-757",
                "LAX-933",
                "LAQ-767",
                "LSA-623",
                "LND-469",
                "MAE-317",
                "MAN-670",
                "MSB-243",
                "MBZ-944",
                "MKI-474",
                "MCL-345",
                "MPW-319",
                "MJX-572",
                "NED-785",
                "NOI-879",
                "ORQ-736",
                "OAC-117",
                "PCQ-564",
                "PAB-328",
                "PPE-199",
                "PZD-206",
                "PSF-816",
                "PPP-309",
                "QAZ-355",
                "QED-808",
                "RVD-518",
                "RAJ-112",
                "REX-558",
                "STQ-818",
                "SLZ-856",
                "SPR-871",
                "SDO-283",
                "SAG-206",
                "SAB-996",
                "SAA-199",
                "SEB-209",
                "TPR-285",
                "TAS-649",
                "TAJ-798",
                "TAL-543",
                "UPP-795",
                "USN-254",
                "VAM-837",
                "VAY-857",
                "HAB-345",
                "HAB-689",
                "HAT-157",
                "HAT-332",
                "HOH-274",
                "HSA-636",
                "ESP-650",
                "EAO-503",
                "ESE-817",
                "ELD-952",
                "EAH-634",
                "EAK-623",
                "CAW-562",
                "CAI-434",
                "CAM-622",
                "CAN-269",
                "CSG-705",
                "MSY-522",
                "MAS-679",
                "MAT-222",
                "MAD-492",
                "MKY-485",
                "M(W-990",
                "MLQ-889",
                "MLH-940",
                "PAS-217",
                "PPN-470",
                "PAZ-897",
                "PAE-996",
                "P(Y-940",
                "PPO-511",
                "AER-446",
                "ACV-276",
                "ACC-318",
                "AHB-147",
                "AHC-450",
                "ARJ-985",
                "APM-391",
                "CAZ-374",
                "COG-659",
                "CEA-523",
                "CAH-996",
                "CDW-714",
                "CEE-839",
                "DAG-938",
                "DRC-929",
                "ELF-465",
                "EAN-731",
                "EBU-243",
                "FON-771",
                "FIK-334",
                "HPX-733",
                "LIO-635",
                "MPW-487",
                "OMG-958",
                "ORH-219",
                "PAU-112",
                "PEA-353",
                "PEA-269",
                "PCZ-778",
                "PHD-743",
                "PHK-427",
                "RAI-419",
                "SAI-165",
                "SBR-738",
                "AEX-466",
                "AAY-776",
                "DAO-526",
                "DTQ-864",
                "PFC-871",
                "CAS-302",
                "BDH-587",
                "ETJ-272",
                "DTP-228",
                "CIN-311",
                "SAW-327",
                "FFQ-679",
                "ASO-822",
                "AHL-844",
                "TKZ-395",
                "BPZ-690",
                "ESP-534",
                "CAW-275",
                "TEJ-342",
                "SMI-903",
                "AOK-232",
                "FBI-910",
                "LFY-114",
                "LTW-624",
                "ANI-248",
                "CAT-143",
                "ITV-933",
                "IPA-540",
                "CDI-393",
                "FOU-833",
                "BAR-118",
                "FAB-318",
                "LDY-569",
                "MIK-164",
                "OYO-545",
                "WAN-588",
                "SAK-399",
                "TTG-361",
                "TIC-378",
                "ATF-832",
                "TAN-831",
                "AEK-541",
                "ARV-777",
                "AIE-289",
                "TSN-537",
                "DFH-139",
                "TPB-325",
                "BAS-560",
                "TAT-820",
                "CYA-741",
                "EAC-922",
                "AOV-741",
                "TRT-840",
                "MSW-656",
                "PYH-396",
                "ITT-859",
                "FID-420",
                "PSM-871",
                "SDZ-748",
                "TPO-387",
                "CUA-440",
                "TBN-588",
                "FSX-221",
                "TBO-617",
                "FCI-865",
                "PCD-208",
                "PIB-529",
                "THQ-739",
                "TWE-392",
                "ERS-651",
                "PPI-804",
                "GEP-706",
                "LVQ-123",
                "APQ-509",
                "ATU-317",
                "NWU-264",
                "PAK-556",
                "CTQ-492",
                "ATD-154",
                "NPY-431",
                "APA-776",
                "HAS-421",
                "ATY-238",
                "UYI-196",
                "BDU-763",
                "FIX-742",
                "PAY-164",
                "AOK-776",
                "TNW-846",
                "RDE-568",
                "ETI-268",
                "ETO-830",
                "RIL-754",
                "ETI-742",
                "FPZ-794",
                "SMY-946",
                "SDT-187",
                "BYL-808",
                "SFS-504",
                "ACH-234",
                "LLQ-462",
                "APT-139",
                "UDE-344",
                "STT-515",
                "EIG-866",
                "AAO-980",
                "FSN-757",
                "BHT-348",
                "AJS-648",
                "EIJ-100",
                "APW-888",
                "SSQ-923",
                "ACU-721",
                "BEI-272",
                "CET-306",
                "CEE-369",
                "CFU-217",
                "DEK-702",
                "EVO-616",
                "ESA-672",
                "EOW-349",
                "EOF-883",
                "EOD-715",
                "EOB-623",
                "EOY-836",
                "FMG-452",
                "GTP-711",
                "IMT-895",
                "IFB-996",
                "IEQ-851",
                "IIW-490",
                "IMN-228",
                "ITJ-848",
                "ITS-504",
                "ITS-463",
                "IEW-251",
                "MCQ-977",
                "MER-269",
                "MTD-374",
                "MEV-628",
                "ALT-920",
                "ALS-603",
                "BAB-852",
                "BCI-595",
                "BDD-395",
                "BMU-831",
                "BNP-490",
                "BPI-799",
                "BPP-345",
                "BQQ-496",
                "CSA-926",
                "CLB-118",
                "CRE-904",
                "C1K-651",
                "C2D-644",
                "CEE-160",
                "CNM-599",
                "CNM-216",
                "CAH-599",
                "CBG-772",
                "CBZ-472",
                "CBE-251",
                "CCR-804",
                "CET-178",
                "CII-588",
                "CLV-919",
                "CNP-743",
                "CWN-252",
                "CTQ-534",
                "CNG-249",
                "CCF-956",
                "CLY-633",
                "C1X-470",
                "CNQ-499",
                "CBH-724",
                "CBG-886",
                "CFV-720",
                "CMT-349",
                "CBR-829",
                "CBM-930",
                "CLC-432",
                "CNU-165",
                "CWQ-545",
                "CWX-683",
                "CFC-515",
                "CTG-931",
                "CTX-511",
                "DHR-169",
                "DDN-682",
                "DAH-692",
                "DHB-824",
                "EMH-805",
                "EMC-206",
                "EME-845",
                "EHD-781",
                "EAS-340",
                "EPV-666",
                "ELQ-700",
                "ELF-727",
                "ENW-659",
                "EPK-199",
                "ERW-995",
                "ERT-568",
                "ERV-885",
                "F1Q-326",
                "FOJ-425",
                "GOO-104",
                "JJL-409",
                "JJN-570",
                "JAS-570",
                "JAP-188",
                "JDH-570",
                "JUP-699",
                "L1H-719",
                "LAD-837",
                "LCD-772",
                "LTR-773",
                "MAN-643",
                "MNB-921",
                "MDM-617",
                "MBX-129",
                "MBK-263",
                "MBT-166",
                "MNJ-584",
                "MSJ-950",
                "MII-683",
                "MII-513",
                "MFB-185",
                "MNE-783",
                "OWG-783",
                "PLI-408",
                "PRW-629",
                "PAQ-848",
                "PAX-525",
                "POZ-959",
                "P1J-598",
                "PCU-948",
                "PMD-188",
                "RRN-283",
                "iEF-196",
                "RIC-235",
                "RLD-304",
                "RDD-544",
                "ROB-712",
                "S(N-333",
                "SCT-573",
                "STM-817",
                "SCH-367",
                "SLS-542",
                "STM-759",
                "SIV-507",
                "SSX-139",
                "SSZ-412",
                "SSR-442",
                "SAD-759",
                "TSR-490",
                "THM-126",
                "TIH-460",
                "TEI-193",
                "VFU-712",
                "VLQ-970",
                "VWD-707",
                "WWU-839",
                "WSC-758",
                "WJG-890",
                "APB-544",
                "ABW-673",
                "BDA-472",
                "BAZ-601",
                "CPZ-238",
                "CNG-926",
                "CPR-241",
                "DPB-526",
                "EPM-972",
                "EAX-403",
                "GDL-612",
                "GIH-600",
                "HET-429",
                "HII-897",
                "ISF-314",
                "IDW-704",
                "POM-100",
                "(DQ-843",
                "PDD-626",
                "PTO-885",
                "PON-990",
                "PDM-410",
                "POI-414",
                "POG-283",
                "SBB-100",
                "SPL-568",
                "SPT-207",
                "TOA-934",
                "ECH-979",
                "EGM-624",
                "EIX-629",
                "GED-833",
                "HUA-425",
                "POU-112",
                "SGX-636",
                "UGS-232",
                "ANH-480",
                "ARD-530",
                "ARL-285",
                "AEA-861",
                "AHF-532",
                "AMU-920",
                "BAD-111",
                "BTE-663",
                "BEK-478",
                "BHB-500",
                "BHM-995",
                "BHI-736",
                "BHY-733",
                "BIU-840",
                "BIT-974",
                "BIC-260",
                "BIS-592",
                "BPD-727",
                "BPF-534",
                "BPP-943",
                "BVS-829",
                "CCI-901",
                "CEK-226",
                "C1U-928",
                "CBY-101",
                "CFE-899",
                "CSM-279",
                "C2D-644",
                "CSF-113",
                "CBG-107",
                "CEP-960",
                "CNC-480",
                "CGG-166",
                "CSX-488",
                "EMO-167",
                "EMX-193",
                "EHP-495",
                "EHE-179",
                "ECI-635",
                "EHB-378",
                "EHN-156",
                "EHK-265",
                "FHT-537",
                "FHC-896",
                "FRA-439",
                "HOW-811",
                "HOZ-932",
                "HFX-448",
                "HDK-301",
                "IHW-258",
                "IFA-544",
                "IHF-416",
                "L1U-191",
                "MER-265",
                "MHF-233",
                "MBC-421",
                "MIP-822",
                "OOJ-186",
                "P1N-461",
                "P1Y-829",
                "SCU-996",
                "TCN-644",
                "TRR-572",
                "TYR-454",
                "THC-417",
                "TEC-974",
                "TSX-645",
                "TSV-891",
                "VEV-609",
                "VBW-117",
                "VBW-126",
                "VSU-337",
                "WIV-578",
                "WPE-962",
                "WSY-399",
                "WHG-699",
                "WIG-828",
                "WIP-651",
                "WWX-988",
                "WWP-126",
                "WIC-389",
                "APX-628",
                "A–W-135",
                "BTV-999",
                "CWD-894",
                "EEZ-380",
                "EWW-491",
                "EOE-640",
                "EHF-231",
                "EOZ-181",
                "EUE-642",
                "EUC-669",
                "EEB-274",
                "EEH-381",
                "EIX-445",
                "EIA-466",
                "EMW-479",
                "EMZ-828",
                "ERP-125",
                "IRC-855",
                "IRA-110",
                "IRM-121",
                "IRZ-326",
                "MEC-924",
                "POD-223",
                "PGE-916",
                "POD-494",
                "SPS-174",
                "SUJ-524",
                "SIE-179",
                "WDX-334",
                "WIS-745",
                "WPU-832",
                "AGZ-416",
                "ALW-987",
                "AVY-869",
                "BEP-997",
                "BPB-259",
                "C1G-566",
                "CPK-582",
                "CGQ-442",
                "CPS-848",
                "CAW-126",
                "DTY-427",
                "DMB-433",
                "EMB-651",
                "ETH-991",
                "EGC-897",
                "EGK-593",
                "FND-346",
                "GPS-530",
                "GDW-943",
                "GPC-949",
                "HSV-232",
                "HOX-628",
                "JSI-371",
                "KAL-277",
                "LHM-453",
                "LTO-937",
                "MHP-969",
                "MFU-608",
                "MHY-972",
                "MPX-490",
                "MPF-112",
                "NES-623",
                "POZ-853",
                "POG-604",
                "POF-135",
                "POR-176",
                "POB-190",
                "POT-135",
                "POF-392",
                "POI-531",
                "POU-916",
                "PON-695",
                "POM-671",
                "POZ-345",
                "PAQ-102",
                "PRK-472",
                "PPV-194",
                "PTN-899",
                "PTQ-158",
                "PKL-675",
                "SND-495",
                "SIS-510",
                "SIO-310",
                "BDN-869",
                "BFW-271",
                "BGR-604",
                "BPY-970",
                "BPF-190",
                "CPA-754",
                "CPE-533",
                "CGA-393",
                "CLH-459",
                "CPO-293",
                "EUQ-687",
                "GTV-621",
                "HOM-539",
                "M–C-943",
                "MBR-534",
                "MBV-457",
                "PFK-490",
                "PML-977",
                "PWH-389",
                "BMS-513",
                "CPC-253",
                "CBM-306",
                "DBW-934",
                "GBV-541",
                "MIZ-905",
                "OCP-682",
                "P(L-871",
                "PSV-475",
                "PID-738",
                "PAR-546",
                "SSB-962",
                "BWJ-207",
                "CFS-988",
                "CWF-705",
                "EWN-878",
                "FPZ-145",
                "FIJ-727",
                "FLP-638",
                "FTQ-810",
                "FTC-237",
                "FTM-996",
                "FTO-594",
                "FWP-287",
                "JAL-329",
                "MWP-406",
                "MWF-806",
                "PCA-782",
                "RIS-156",
                "RWN-269",
                "SFM-998",
                "WIQ-416",
                "WIY-567",
                "WVI-434",
                "WED-256",
                "WLF-272",
                "WLJ-230",
                "WWU-239",
                "AAA-742",
                "BHT-856",
                "BWW-927",
                "C2Z-136",
                "CEC-501",
                "CRT-773",
                "CRD-210",
                "CHZ-587",
                "CRY-314",
                "CUL-383",
                "CRS-555",
                "CSL-548",
                "CDR-337",
                "CIA-780",
                "DEX-777",
                "ECE-625",
                "EIQ-683",
                "ETR-411",
                "EOS-429",
                "ENM-731",
                "ELV-627",
                "FAR-573",
                "GEP-859",
                "GLD-108",
                "GLA-950",
                "GGP-355",
                "GIV-805",
                "GLM-955",
                "HJA-339",
                "HRA-701",
                "HAN-927",
                "HOX-224",
                "HOG-583",
                "HOU-718",
                "HOZ-877",
                "HOD-973",
                "HOE-450",
                "HOS-712",
                "HOK-742",
                "HOA-546",
                "HOD-524",
                "HOH-572",
                "HON-417",
                "HOL-331",
                "HOQ-521",
                "HOW-627",
                "HOQ-619",
                "HGP-505",
                "HTK-303",
                "HED-327",
                "IOW-709",
                "IHC-636",
                "ITX-999",
                "ITD-337",
                "ITV-958",
                "J(J-127",
                "LLZ-903",
                "LIL-176",
                "LDW-263",
                "LTP-154",
                "MOX-343",
                "CJV-504",
                "MAG-683",
                "MAQ-573",
                "MCQ-487",
                "MEO-885",
                "MTU-411",
                "MEM-240",
                "MCY-367",
                "MCF-364",
                "MDO-796",
                "MHQ-643",
                "MIM-635",
                "MJM-983",
                "MAW-634",
                "MOY-516",
                "M(S-953",
                "MAY-902",
                "MIB-714",
                "NHY-188",
                "NMF-551",
                "PHJ-677",
                "PLI-163",
                "PML-555",
                "PMR-430",
                "PSB-625",
                "PSA-323",
                "PRO-745",
                "PRD-364",
                "PIC-971",
                "RIL-715",
                "RAK-678",
                "ROH-695",
                "REI-337",
                "RLE-642",
                "SCB-342",
                "SHU-635",
                "SCF-246",
                "SOS-315",
                "SAL-135",
                "SAT-847",
                "SAR-171",
                "TIJ-263",
                "TOM-803",
                "TPS-211",
                "UDU-679",
                "UAC-493",
                "VAE-984",
                "VDG-473",
                "VEJ-932",
                "WCJ-168",
                "ZTZ-338"
        };
    }
}
