package me.quyen.entities.fakadata;

import java.util.concurrent.ThreadLocalRandom;

public class DepartmentData {
    public static String departmentName(){
        return namesAndCodes()[0];
    }
    public static String departmentCode(){
        return namesAndCodes()[1];
    }
    public static String[] namesAndCodes(){
        int chosenInt = Math.min(departmentCodes().length, departmentNames().length);
        int rInt = ThreadLocalRandom.current().nextInt(0,chosenInt);
        return new String[]{departmentNames()[rInt],departmentCodes()[rInt]};
    }
    public static String[] departmentNames(){
        return new String[]{
                "UK Climate Impacts Programme",
                "Libraries",
                "Mythology",
                "Innovation",
                "Shakespeare",
                "Cell Biology",
                "Pharmacology",
                "English Novel",
                "Jurisprudence",
                "English Poetry",
                "Fiction 19th C",
                "Modern History",
                "Women’s History",
                "Feminist Issues",
                "Modern Languages",
                "Creative Writing",
                "Creative Writing",
                "African Politics",
                "Moral Philosophy",
                "History of India",
                "History of Music",
                "Public Programmes",
                "Warfare in Europe",
                "Modern Philosophy",
                "Middle East Centre",
                "Women’s Literature",
                "Russian Literature",
                "Clinical Psychology",
                "British Imperialism",
                "Political Movements",
                "Asian Studies Centre",
                "Cognitive Psychology",
                "Political Philosophy",
                "Education, Continuing",
                "Queen Elizabeth House",
                "Experimental Analysis",
                "Psychiatric Disorders",
                "Human Urban Geography",
                "British Women Writers",
                "English Women Writers",
                "History of Philosophy",
                "Cognitive Neuroscience",
                "European Studies Centre",
                "Psychological Therapies",
                "International Relations",
                "History of Modern China",
                "Doctoral Training Centre",
                "Doctoral Training Centre",
                "International Programmes",
                "Press, Oxford University",
                "Institute of Archaeology",
                "British Imperial History",
                "British Political History",
                "European Interwar Thought",
                "Britain the European Union",
                "Brain Network Dynamics Unit",
                "Clinical Trial Service Unit",
                "Soviet Post Soviet Politics",
                "History of Economic Thought",
                "Online and Distance Learning",
                "British Political Philosophy",
                "Supercomputing Centre, Oxford",
                "History of Modern Economic Ideas",
                "Russian and Eurasian Studies Centre",
                "Wildlife Conservation Research Unit",
                "War, Peace Social Change in Britain",
                "Technology-Assisted Lifelong Learning",
                "Lifelong Learning, Technology-Assisted",
                "International Development, Department of",
                "Development, International, Department of",
                "Continuing Professional Development Centre",
                "Professional Development, Continuing, Centre",
                "Physical and Theoretical Chemistry Laboratory",
                "Quantum Mathematics and Computation, Centre for",
                "Diabetes, Endocrinology and Metabolism, Oxford Centre for",
                "Epidemiological Studies Unit, Clinical Trial Service Unit",
                "Skills, Knowledge and Organisational Performance, Centre for",
                "Accelerator Science, John Adams Institute for",
                "Advanced Research Computing",
                "African Economies, Centre for the Study of",
                "African Studies Centre",
                "Ageing, Population, Oxford Institute of",
                "American Institute, Rothermere",
                "Anaesthetics, Nuffield Department of",
                "Analysis of Resource-Rich Economies, Oxford Centre for the",
                "Anatomical Neuropharmacology Unit, MRC",
                "Anatomy and Genetics, Department of Physiology",
                "Ancient Documents, Centre for the Study of",
                "Ancient History and Classical Archaeology, Sub-faculty of",
                "Anthropology and Museum Ethnography, School of",
                "Anthropology, Institute of Social and Cultural",
                "Arabic",
                "Archaeology and the History of Art, Research Laboratory for",
                "Archaeology, Classical and Ancient History, Sub-faculty of",
                "Archaeology, Institute of",
                "Archaeology, School of",
                "Archive of Performances of Greek and Roman Drama",
                "Archives, Oxford University",
                "Area Studies, Oxford School of Global and",
                "Art and Material Culture of the Middle East, Khalili Research Centre for the",
                "Art, History of, Department",
                "Art, Ruskin School of",
                "Ashmolean Museum of Art and Archaeology",
                "Asian and Middle Eastern Studies, Faculty of",
                "Asian Languages",
                "Astrophysics, Sub-department of",
                "Atmospheric, Oceanic, and Planetary Physics, Sub-department of",
                "Atomic and Laser Physics, Sub-department of",
                "Beazley Archive",
                "Begbroke Science Park",
                "Biochemistry, Department of",
                "Biology, Department of",
                "Biomedical Engineering, Oxford Institute of",
                "Blavatnik School of Government",
                "Botanic Garden",
                "Botnar Research Centre",
                "Brazilian Studies Programme",
                "Business Economics Programme, Oxford University",
                "Business School, Saïd",
                "Business Taxation, Centre for",
                "Byzantine Studies",
                "Cancer Epidemiology Unit",
                "Carbon and Energy Reduction in Transport, Institute for",
                "Cardiovascular Medicine, Division of",
                "Careers Service",
                "Catalan",
                "Cellular and Molecular Physiology, Centre for",
                "Celtic",
                "Changing Character of War, Programme on the",
                "Chemical Biology, Laboratory",
                "Chemical Crystallography Laboratory",
                "Chemistry, Department of",
                "China Studies Programme, Contemporary",
                "China Centre",
                "Classical and Byzantine Studies, Ioannou Centre for",
                "Classical Archaeology and Ancient History, Sub-faculty of",
                "Classical Languages and Literature, Sub-faculty of",
                "Classics, Faculty of",
                "Clinical Laboratory Sciences, Nuffield Division of",
                "Clinical Medicine, Nuffield Department of",
                "Clinical Neurology, Department of",
                "Clinical Neurosciences, Nuffield Department of",
                "Clinical Vaccinology and Tropical Medicine, Centre for",
                "Comparative Media Law and Policy, Programme in",
                "COMPAS - Centre on Migration, Policy and Society",
                "Computational Biology Group",
                "Computer Science, Department of",
                "Computing, Advanced Research",
                "Condensed Matter Physics, Sub-department of",
                "Contemporary China Studies Programme",
                "Continuing Education, Department for",
                "Counselling Service",
                "Criminology, Centre for",
                "Crystallography, Chemical, Laboratory",
                "Czech",
                "Diabetes Research Laboratories",
                "Diabetes Trials Unit",
                "Distance and Online Learning",
                "Dunn School of Pathology, Sir William",
                "E-Research Centre, Oxford",
                "Earth Sciences, Department of",
                "Economic Governance Programme, Global",
                "Economics, Department of",
                "Economies, African, Centre for the Study of",
                "Economies, Resource-Rich, Oxford Centre for the Analysis of",
                "Education, Department of",
                "Edward Grey Institute of Field Ornithology",
                "Emerging Infections, Institute for",
                "Engineering Science, Department of",
                "Engineering, Biomedical, Oxford Institute of",
                "English Language and Literature, Faculty of",
                "Enterprise and the Environment, Smith School for",
                "Entrepreneurship, Social, Skoll Centre for",
                "Environment, School of Geography and the",
                "Environment, Smith School for Enterprise and the",
                "Environmental Change Institute",
                "Epidemiology Unit, Cancer Research UK",
                "Epidemiology, Health-Care, Unit of",
                "Epidemiology, National Perinatal Unit of",
                "Ethics, Institute for Science and",
                "Ethics, Law and Armed Conflict, Oxford Institute for",
                "Ethox Centre",
                "European and Comparative Law, Institute of",
                "European Humanities Research Centre",
                "European Languages",
                "Evidence-Based Medicine, Centre for",
                "Executive Education Centre",
                "Experimental Psychology, Department of",
                "Field Ornithology, Edward Grey Institute of",
                "Foreign Service Programme",
                "French, Sub-Faculty of",
                "Functional Magnetic Resonance Imaging of the Brain, Oxford Centre for - FMRIB",
                "Future of the Mind, Institute for the",
                "Galician",
                "Gender Studies Centre, International",
                "Genetics Unit",
                "Genetics, Department of Physiology, Anatomy and",
                "Genetics, Human, Wellcome Trust Centre for",
                "Geography and the Environment, School of",
                "German, Sub-Faculty of",
                "Global and Area Studies, Oxford School of",
                "Global Economic Governance Programme",
                "Global Health, Centre for Tropical Medicine and",
                "Global Leaders Fellowship Programme, Oxford-Princeton",
                "Glycobiology Institute",
                "Government, Blavatnik School of",
                "Greek and Roman Drama, Archive of Performances of",
                "Greek Personal Names, Lexicon of",
                "Greek, Medieval and Modern, Sub-faculty of",
                "Griffith Institute",
                "Health Economics Research Centre",
                "Health Services Research Unit",
                "Health-Care Epidemiology, Unit of",
                "Hindi",
                "History of Art Department",
                "History of Art, Research Laboratory for Archaeology and the",
                "History of Medicine Library",
                "History of Science, Medicine, and Technology, Oxford Centre for the",
                "History of Science Museum",
                "History, Ancient, and Classical Archaeology, Sub-faculty of",
                "History, Faculty of",
                "Human Genetics, Wellcome Trust Centre for",
                "Human Sciences, Institute of",
                "Humanities Research Centre, European",
                "Ian Ramsey Centre for Science and Religion",
                "Industrial and Applied Mathematics, Oxford Centre for - OCIAM",
                "Instituto Camões Centre for Portuguese Language",
                "Integrative Systems Biology Centre, Oxford",
                "Intellectual Property Research Centre, Oxford",
                "International Gender Studies Centre",
                "International Relations, Department of Politics and",
                "International Studies, Centre for",
                "Internet Institute, Oxford",
                "Investigative Medicine Division",
                "Ioannou Centre for Classical and Byzantine Studies",
                "Italian, Sub-Faculty of",
                "Japanese Studies, Nissan Institute of",
                "Japanese",
                "John Adams Institute for Accelerator Science",
                "Journalism, Reuters Institute for the Study of",
                "Kennedy Institute",
                "Khalili Research Centre for the Art and Material Culture of the Middle East",
                "Korean Studies",
                "Language Centre",
                "Languages, Asian",
                "Languages, European",
                "Languages, Middle Eastern",
                "Languages, Oriental",
                "Latin American Centre",
                "Law, Faculty of",
                "Law, Institute of European and Comparative",
                "Learning Institute, Oxford",
                "Lexicon of Greek Personal Names",
                "Life Sciences Doctoral Training Centre",
                "Linguistics and Philology, Centre for",
                "Linguistics, Philology and Phonetics, Faculty of",
                "Management, Faculty of",
                "Martin School, Oxford",
                "Materials, Department of",
                "Mathematical Biology, Centre for",
                "Mathematical Institute",
                "Mathematics, Oxford Centre for Industrial and Applied - OCIAM",
                "Medical Oncology",
                "Medical School",
                "Medical Sciences Doctoral Teaching Centre",
                "Medical Sciences Teaching Centre",
                "Medicine, Clinical, Nuffield Department of",
                "Medicine, Molecular, Weatherall Institute of",
                "Medicine, Radcliffe Department of",
                "Medieval and Modern Languages, Faculty of",
                "Middle Eastern Studies, Faculty of Asian and",
                "Migration, Policy and Society, Centre on - COMPAS",
                "Molecular Medicine, Weatherall Institute of",
                "MRC Brain Network Dynamics Unit",
                "Musculoskeletal Sciences, Institute of",
                "Music, Faculty of",
                "Nanoscience for Medicine, Institute of",
                "National Perinatal Epidemiology, Unit of",
                "Natural History, Oxford University Museum of",
                "Neurology, Clinical, Department of",
                "Neurosciences, Clinical, Nuffield Department of",
                "Nissan Institute of Japanese Studies",
                "Nuffield Department of Anaesthetics",
                "Nuffield Department of Clinical Medicine",
                "Nuffield Department of Clinical Neurosciences",
                "Nuffield Department of Orthopaedics, Rheumatology and Musculoskeletal Sciences",
                "Nuffield Department of Population Health",
                "Nuffield Department of Surgical Sciences",
                "Nuffield Department of Women's and Reproductive Health",
                "Nuffield Division of Clinical Laboratory Sciences",
                "Nuffield Laboratory of Ophthalmology",
                "Occupational Health Service, University",
                "Oncology, Department of",
                "Ophthalmology, Nuffield Laboratory of",
                "Oriental Institute, SeeFaculty of Asian and Middle Eastern Studies",
                "Ornithology, Edward Grey Institute of Field",
                "Orthopaedics, Rheumatology and Musculoskeletal Sciences, Nuffield Department of",
                "Oxford Martin School",
                "Oxford School of Global and Area Studies",
                "Oxford University Innovation",
                "Oxford University Press",
                "Oxford-Man Institute of Quantitative Finance",
                "Oxford-Princeton Global Leaders Fellowship Programme",
                "Oxyrhynchus Papyri Project",
                "Paediatrics, Department of",
                "Pain Relief Unit",
                "Parks, University",
                "Particle Physics, Sub-department of",
                "Pathogen Research, Peter Medawar Building for",
                "Pathology, Sir William Dunn School of",
                "Performances of Greek and Roman Drama, Archive of",
                "Perinatal Epidemiology, National Unit of",
                "Persian",
                "Peter Medawar Building for Pathogen Research",
                "Pharmacology, Department of",
                "Philology, and Phonetics; Faculty of Linguistics,",
                "Philology, Centre for Linguistics and",
                "Philosophy Centre",
                "Philosophy, Faculty of",
                "Phonetics Laboratory",
                "Phonetics; Faculty of Linguistics, Philology and",
                "Physical and Theoretical Chemistry Laboratory",
                "Physics, Department of",
                "Physiology, Anatomy and Genetics, Department of",
                "Physiology, Centre for Cellular and Molecular",
                "Pitt Rivers Museum",
                "Plant Sciences is now theDepartment of Biology",
                "Polish",
                "Politics and International Relations, Department of",
                "Population Ageing, Oxford Institute of",
                "Population Health, Nuffield Department of",
                "Portuguese Language, Instituto Camões Centre for",
                "Portuguese, Sub-Faculty of",
                "Poverty and Human Development Initiative, Oxford",
                "Practical Ethics, Oxford Uehiro Centre for",
                "Primary Care Health Sciences, Nuffield Department of",
                "Professional Service Firms, Centre for",
                "Project to Investigate Memory and Ageing, The Oxford - OPTIMA",
                "Psychiatry, Department of",
                "Psychology, Experimental, Department of",
                "Quantitative Finance, Oxford-Man Institute of",
                "Radcliffe Department of Medicine",
                "Radiation Oncology and Biology, Gray Institute fo",
                "Ramsey, Ian, Centre for Science and Religion",
                "Refugee Studies Centre",
                "Religion, Faculty of Theology and",
                "Resource-Rich Economies, Oxford Centre for the Analysis of",
                "Reuters Institute for the Study of Journalism",
                "Rothermere American Institute",
                "Ruskin School of Art",
                "Russian and East European Studies",
                "Sanskrit",
                "Saïd Business School",
                "Science and Religion, Ian Ramsey Centre for",
                "Science, Innovation and Society, Institute for",
                "Science, Medicine, and Technology, Oxford Centre for the History of",
                "Science, Museum of the History of",
                "Sciences Po Research Group, Oxford-",
                "Simulation Centre, Oxford",
                "Sir William Dunn School of Pathology",
                "Skoll Centre for Social Entrepreneurship",
                "Smith School of Enterprise and the Environment",
                "Social and Cultural Anthropology, Institute of",
                "Social Entrepreneurship, Skoll Centre for",
                "Social Justice, Centre for the Study of",
                "Social Policy and Intervention, Department of",
                "Socio-Legal Studies, Centre for",
                "Sociology, Department of",
                "Software Engineering Programme",
                "South Asian Studies",
                "Spanish, Sub-Faculty of",
                "Sport, Oxford University Sport",
                "Statistics, Department of",
                "Stem Cell Institute, Oxford",
                "Stroke Prevention Research Unit",
                "Structural Biology, Division of",
                "Structural Genomics Consortium",
                "Study of African Economies, Centre for the",
                "Study of Ancient Documents, Centre for the",
                "Study of Journalism, Reuters Institute for the",
                "Study of Social Justice, Centre for the",
                "Study of the Book, Centre for",
                "Surgical Sciences, Nuffield Department of",
                "Taxation, Centre for Business",
                "Theology and Religion, Faculty of",
                "Theoretical Physics, Rudolf Peierls Centre for",
                "Transport Studies Unit",
                "Transport, Institute for Carbon and Energy Reduction in",
                "Tropical Medicine and Global Health, Centre for",
                "Turkish",
                "Uehiro Centre for Practical Ethics, Oxford",
                "UK Climate Impacts Programme",
                "Urdu",
                "Visual Studies, Centre for",
                "Voltaire Foundation",
                "War, Oxford Leverhulme Programme on the Changing Character of",
                "Weatherall Institute of Molecular Medicine",
                "Wellcome Trust Centre for Human Genetics",
                "Women's and Reproductive Health, Nuffield Department of",
                "Big Data Institute",
                "Department of Biochemistry, University of Oxford",
                "Biodiversity Institute",
                "University of Oxford Botanic Garden",
                "BT Centre for Major Programme Management",
                "Campaign for Oxford",
                "Centre for Quantum Computation",
                "Centre for the Study of African Economies",
                "Chemical Biology Laboratory",
                "Department of Chemistry, University of Oxford",
                "Chemistry Research Laboratory, University of Oxford",
                "Churchill Hospital",
                "Faculty of Classics, University of Oxford",
                "Clinical Trial Service Unit",
                "Department of Computer Science, University of Oxford",
                "Oxford University Computing Services",
                "Oxford University Department for Continuing Education",
                "Department of Biology, University of Oxford",
                "Dyson Perrins Laboratory",
                "Department of Earth Sciences, University of Oxford",
                "Department of Economics, University of Oxford",
                "Department of Engineering Science, University of Oxford",
                "Centre for Evidence-Based Medicine",
                "Faculty of Asian and Middle Eastern Studies",
                "Faculty of Linguistics, Philology and Phonetics, University of Oxford",
                "Faculty of Philosophy, University of Oxford",
                "Future of Humanity Institute",
                "Harcourt Arboretum",
                "Faculty of History, University of Oxford",
                "Indian Institute",
                "Inorganic Chemistry Laboratory",
                "Institute for Emerging Infections",
                "Institute of Commonwealth Studies, Oxford",
                "International Migration Institute",
                "Oxford Internet Institute",
                "Oxford Centre for Islamic Studies",
                "Jenner Institute",
                "John Radcliffe Hospital",
                "Faculty of Law, University of Oxford",
                "Department of Materials, University of Oxford",
                "Mathematical Institute, University of Oxford",
                "McDonald Centre",
                "Faculty of Medieval and Modern Languages, University of Oxford",
                "Nuclear Physics Laboratory",
                "Nuffield Department of Medicine",
                "Numerical Analysis Group",
                "Department of Oncology, University of Oxford",
                "Oxford Centre for Gene Function",
                "Oxford Centre for Hebrew and Jewish Studies",
                "Oxford Department of International Development",
                "Oxford Poverty and Human Development Initiative",
                "Oxford University Medical School",
                "Oxford University Phonetics Lab",
                "Department of Physics, University of Oxford",
                "Department of Plant Sciences, University of Oxford",
                "Department of Politics and International Relations, University of Oxford",
                "Programming Research Group",
                "Radcliffe Infirmary",
                "Radcliffe Observatory",
                "Research Laboratory for Archaeology and the History of Art",
                "Rhodes House",
                "Said Business School",
                "School of Archaeology, University of Oxford",
                "School of Geography and the Environment, University of Oxford",
                "Department of Social Policy and Intervention",
                "Taylor Institution",
                "Faculty of Theology and Religion, University of Oxford",
                "Wellcome Centre for Human Genetics",
                "WildCRU",
                "Department of Zoology, University of Oxfor",
                "C20th Literature",
                "C20th Novelists",
                "C20th Writing",
                "Canterbury Tales",
                "Chaucer",
                "Chaucer’s Canterbury Tales",
                "Children’s Literature",
                "Classic 19th C Novels",
                "Classical Narrative",
                "Contemporary British Irish Poetry",
                "Contemporary British Drama",
                "Contemporary Fiction",
                "Contemporary Modernist Fiction",
                "Contemporary British Novel",
                "Contemporary British Poets",
                "Contemporary Literary Theory",
                "Contemporary Novel Theory",
                "Crime Fiction",
                "Critical Theory and its Application",
                "Critical Theory",
                "D H Lawrence",
                "Dante’s Divine Comedy",
                "Dickens",
                "Dryden",
                "E M Forster",
                "Early Milton Poetry Paradise Lost",
                "Early Modern British Fiction",
                "Eliot Hardy",
                "Eliot and Yeats",
                "Elizabethan Poetry",
                "English Literature 1640-1850",
                "English Literature 1890-1930",
                "English Renaissance Literature",
                "English Romantic Literature",
                "English Romantic Poetry",
                "Fiction of C S Lewis",
                "George Orwell",
                "James Joyce",
                "James Joyce Dylan Thomas",
                "Jane Austen",
                "Jane Austen The Brontes",
                "John Donne",
                "Joyce’s Ulysses",
                "Late 19th C British Drama Prose",
                "Literary Analysis",
                "Literary Critical Theory",
                "Literary Theory",
                "Medieval Arthurian Literature",
                "Medieval non-Chaucerian Literature",
                "Milton",
                "Modern British Literature",
                "Modern British Novel",
                "Modern British Drama",
                "Modern Novel",
                "Modern Short Story",
                "Modern Irish Drama",
                "Modernism in English Literature",
                "Modernist Fiction",
                "Modernist Novel",
                "Oscar Wilde Bernard Shaw",
                "Paradise Lost",
                "Play Reading Creative Writing",
                "Poetic Analysis",
                "Poetry Analysis Creative Writing",
                "Poetry of John Donne",
                "Post 1830 English Literature",
                "Post Colonial Literature in England",
                "Post Modern Theory Novel",
                "Rebellion Restoration",
                "in English Literature",
                "Reformation in Europe",
                "Renaissance Literature",
                "Restoration Drama",
                "Rhetoric of 19th 20th C Fiction",
                "Shakespeare Characterization",
                "Shakespeare the Roman World",
                "Shakespeare’s Comedies",
                "Shakespeare’s Last Plays",
                "Shakespeare’s Tragedies",
                "Shaw Ibsen",
                "Short Story",
                "Short Story Analysis Writing",
                "Short Story C20th",
                "Sonnet and English Poetry",
                "T S Eliot Other Poets",
                "Thomas Hardy Dickens",
                "Time in 20th C Literature",
                "TS Eliot Related Poets",
                "Victorian Fiction",
                "Victorian Literature",
                "Virginia Woolf",
                "William Wordsworth Anne Finch",
                "Woolf",
                "Woolf, Joyce Lawrence",
                "Abnormal Psychology",
                "Animal Behaviour",
                "Behavioural Disorders",
                "Brain and Behaviour",
                "Developmental Psychology",
                "Educational Psychology",
                "Gender Differences in Psychology",
                "Gender Issues in the Third World",
                "Human Evolution",
                "Human Information Processing",
                "Immune System",
                "Individual Differences",
                "Perspectives of Childhood",
                "Psychology of Adolescence",
                "Psychological Disorders",
                "Psychology of Gender",
                "Psychology of Personality",
                "Social Behaviour",
                "Social Psychology",
                "Social Psychology Behaviour",
                "Treatment of Psychological Disorder",
                "Environmental Change and Problems",
                "Environmental Geography",
                "Environmental Issues",
                "Geographical Environment",
                "Principles of Social Geography",
                "Social Geography",
                "Urban Geography",
                "Ancient Near Eastern History",
                "Anglo-American Relations 1914-60",
                "Anglo-Irish Relations 1880-1922",
                "Anglo-Saxon England",
                "Arthur: Historical Background",
                "Arthur: Medieval to Modern",
                "Britain America in the 18th C",
                "Britain the Cold War",
                "British Empire 1800-1947",
                "British History 400-1330",
                "British History 1850-1940",
                "British History 1900-1950",
                "British History Since 1870",
                "British Imperialism Decolonization",
                "British India to Independence",
                "British Political History Since 1945",
                "British Post-War History",
                "British View of WW ll",
                "C18th Culture Society",
                "C18th English History",
                "C18th 19th British Social History",
                "C19th British India",
                "C19th French Social History",
                "C19th Socialist Radical Thought",
                "C19th 20th British Political History",
                "C20th Social Change in Britian",
                "C20th British History",
                "C20th European History",
                "Colonialism Nationalism in India",
                "Church Govt Society C16th England",
                "Culture Society in 18th C England",
                "Early Modern British History",
                "Early Modern Women’s History Eastern Europe Since 1945",
                "Edwardian History",
                "Elizabethan History",
                "English Civil War Background",
                "English History 1066-1275",
                "European History 1500-1900",
                "European History Post 1945",
                "French History Politics 1870-1914",
                "French History 1789-1848",
                "French Revolution",
                "History of East Europe 1945-Present",
                "History of World War 2",
                "Hitler Fascism",
                "Holocaust",
                "International History 1882-1939",
                "Interwar Fascism",
                "Irish History 1880-1922",
                "Late 19th C Japan",
                "Modern European Politics History",
                "Modern British Social History",
                "Mussolini Italian Fascism",
                "Origins of Industrial Revolution",
                "Post 1945 Britain",
                "Post 1945 State Welfare in the UK",
                "Social Class in Britain",
                "The Crusades",
                "Third Reich",
                "Thirty Years’ War",
                "Tudor History",
                "Tudor Early Stuart England",
                "Tudor Stuart History",
                "Tudor Stuart Social History",
                "Victorian Edwardian History",
                "Victorian Britain",
                "Victorian British Women’s History",
                "Victorian Social History",
                "Wales in Tudor England",
                "Wars Since 1945",
                "Women in 16th C England",
                "Women in the Middle Ages",
                "World War I",
                "World War II",
                "WW II Anglo – American Relations",
                "Arab – Israeli Relations",
                "Cold War Diplomacy",
                "East European Politics Economics",
                "East West Relations Since 1945",
                "Eclipse of GB as a World Power",
                "Economic History of Europe 1918-39",
                "Economics of Eastern Europe",
                "European Union",
                "European Union Law",
                "Europe Economic Integration",
                "European Economic Community",
                "European Integration",
                "European Modernism",
                "European Monetary Integration",
                "European Reformation",
                "Industrial Relations in the EU",
                "International Relations During WW2",
                "International Relations Since 1945",
                "Middle Eastern Politics",
                "Politics of the European Union",
                "Politics Govt of Israel",
                "Politics of Modern India",
                "Soviet Union 1917-1991",
                "State in Early Modern Europe",
                "War Diplomacy in Europe",
                "Warsaw Pact NATO",
                "Ancient Greek Philosophy",
                "Ancient Logic",
                "Aristotle",
                "British Empiricists",
                "C17th 18th Philosophy",
                "C18th Political Theory",
                "C19th German Philosophers",
                "C19th Philosophy",
                "Contemporary Aesthetics",
                "Descartes to Kant",
                "Descartes’ Meditations",
                "Epistemology Metaphysics",
                "Ethical Theory",
                "Ethics",
                "Existentialism",
                "Freud, Nietzsche Existentialism",
                "German Philosophy",
                "Greek Drama Philosophy",
                "Greek Philosophy",
                "Heiddegger, Sartre Derrida",
                "History of Philosophy",
                "Jean-Paul Sartre",
                "Kant and the German Idealists",
                "Locke, Hobbes Rousseau",
                "Logic",
                "Marx Hegel",
                "Marxism",
                "Metaphysics",
                "Nietzsche",
                "Perspectives on Morality",
                "Philosophy of Hegel",
                "Philosophy of Human Nature",
                "Philosophy of Kant",
                "Philosophy of Language",
                "Philosophy of Law",
                "Philosophy of Mind Psychology",
                "Philosophy of Perception",
                "Philosophy of Personal Identity",
                "Philosophy of Religion",
                "Philosophy of Science",
                "Philosophy of Wittgenstein Plato",
                "Plato and Aristotle",
                "Plato’s Republic",
                "Political Theory and Thought",
                "Political Thought C17th 18th",
                "Post Kantian German Philosophy",
                "Schopenhauer Nietzsche",
                "Studies in Logical Theory",
                "Studies in Wittgenstein",
                "British Domestic Politics WW2",
                "British Foreign Policy Since 1945",
                "British Govt Politics Since 1880",
                "British Politics Govt Since 1945",
                "British Politics 1970-1999",
                "Classical Political Theory",
                "Classical Political Thought",
                "Comparative Government",
                "Comparative Labour Economics",
                "Contemporary Political Thought",
                "European Union Politics Govt",
                "Game Theory of Politics",
                "History of W Political Thought",
                "Machiavelli – Rousseau",
                "Modern British Government",
                "Modern British Govt Politics",
                "Political Fiction of Cold War",
                "Post War Changes in E Europe",
                "Biochemisty",
                "Cardio-Vascular Physiology",
                "Developmental Biology",
                "Genetics Biology",
                "Molecular Immunology",
                "Organic Chemistry",
                "Probability Statistics",
                "Proofs in Abstract Mathematics",
                "Pure Applied Algebra",
                "Statistical Survey Method",
                "C20th Feminist Theory",
                "C20th Women Writers",
                "Feminist Post Colonial Theory",
                "Feminist Literature",
                "Feminist Theory",
                "Feminist Theory Criticism",
                "Feminist Theory for the 21st C",
                "Feminist Thought",
                "Feminist Writers in the UK",
                "Jane Austen Charlotte Bronte",
                "Medieval Women Writers",
                "Modern Women’s Writing: The Novel",
                "Post Colonial Feminist Theory",
                "Readings in British Feminism",
                "Renaissance Women Writers",
                "Shakespeare Feminist Theory Women in Changing Society",
                "Women in Shakespeare",
                "Women in the Bible",
                "Women Victorian Poets",
                "Women’s Experience in the Novel",
                "Women’s Literature From 1640",
                "Women’s Writing C20th",
                "Anglo-Saxon Archaeology",
                "British Health Care System",
                "Buddhism",
                "C19th 20th German Literature",
                "C19th English Architecture",
                "C19th Russian Literature",
                "Chinese Religion",
                "Comparative Health Policy",
                "Comparative Religion",
                "Comparative UK US Law",
                "Constitutionalism",
                "Contemporary SE Asia",
                "Criminology Deviant Behaviour",
                "Cultural Issues Weimar Germany",
                "Differential Equations",
                "Early Church",
                "Early Islamic History",
                "Economics Theology of the Early Church",
                "Elements of Critical Theory",
                "Ethnomusicology",
                "European Literature Cinema",
                "French Art : Late 19th C",
                "German Expressionist Painting",
                "German Language Linguistics",
                "German Literature Post 1945",
                "Greek Grammar",
                "Greek Intellectual History",
                "Greek: Language Literature",
                "Henry James",
                "Hinduism",
                "History Architecture of Oxford",
                "History of Art: Impressionism",
                "History of Art: Renaissance",
                "History of English Language",
                "History of European Community",
                "History of Political Thought",
                "History of the Early Church",
                "History of the Monarchy",
                "History of the Soviet Union",
                "History of the Warsaw Pact NATO",
                "History of Victorian London",
                "Homer Greek Mythology",
                "How The Rabbis Read The Bible",
                "Human Ecology",
                "Images of Jesus",
                "Intellectual History of Feminism",
                "Introduction to Criminology",
                "Introduction to English Law",
                "Introduction to Literary Theory",
                "Latin: Language Literature",
                "Legal Issues in Free Speech",
                "Leonardo Da Vinci",
                "Literary Theory Philosophy",
                "Making of the American",
                "Constitution",
                "Medieval Archaeology",
                "Medieval Art Architecture",
                "Medieval Counterpoint",
                "Medieval English Drama",
                "Medieval Theology",
                "Middle English Language",
                "Modern Chinese Economic History",
                "Modern Chinese Politics",
                "Modern Drama",
                "Modern History of Africa",
                "Modern Islam",
                "Modern Jewish Literature",
                "Modernist Art",
                "Music of West Africa",
                "Mythology and Art History",
                "Mythology in Literary Texts",
                "Natural Health Care Systems",
                "Nelson Mandela and S African Politics",
                "Polish History Literature",
                "Polish Literature 1918-1990",
                "Post Modernism and the Visual Arts",
                "Post Modernism: Theory and Fiction",
                "Post Structuralism",
                "Post Structuralist Theory",
                "Pre- Raphaelite Art",
                "Pre- Raphaelite Movement",
                "Public International Law",
                "Reading in Augustine’s Confessions",
                "Renaissance Art",
                "Representations of the Holocaust",
                "Roman Elegy",
                "Social Change in Europe 1914-1942",
                "Social Hist Anthropology of India",
                "Socialism Capitalism",
                "Sociology of Health",
                "South Asian Politics",
                "St Augustine",
                "St Augustine: Theology Thought",
                "Talmud in Translation",
                "Theology of St Paul",
                "Theories Problems of Nationalism",
                "Ulysses",
                "Urban Anthropology",
                "Victorian Art Architecture",
                "Victorian Design",
                "Victorian England",
                "War Culture 1450-1620",
                "Zionist Thought Histor"
        };
    }

    public static String[] departmentCodes(){
        return new String[]{
                "UCIP-3605",
                "LSHE-6675",
                "MITG-1936",
                "IRPC-8526",
                "SNEG-9976",
                "CBQK-1811",
                "PBYV-5525",
                "ENQC-9117",
                "JDWT-3329",
                "EPPB-9132",
                "F1CG-9216",
                "MHTK-8081",
                "WHYX-9129",
                "FIZB-6594",
                "MLTW-8574",
                "CWTF-2452",
                "CWUM-7762",
                "APDO-6727",
                "MPZG-1680",
                "HOIA-4410",
                "HOMN-9127",
                "PPWN-3650",
                "WIEP-1793",
                "MPBT-2689",
                "MECB-8711",
                "WLRR-9664",
                "RLHD-1842",
                "CPRB-2897",
                "BIHJ-4545",
                "PMKK-7606",
                "ASCS-3452",
                "CPHD-5812",
                "PPGZ-4714",
                "ECYS-5500",
                "QEHS-4465",
                "EAUR-8604",
                "PDVN-7533",
                "HUGL-8931",
                "BWWB-7756",
                "EWWE-7483",
                "HOPN-1999",
                "CNFC-8118",
                "ESCU-9898",
                "PTTN-6531",
                "IRUF-7771",
                "HOMC-5429",
                "DTCH-7726",
                "DTCN-3356",
                "IPYV-1363",
                "POUA-8885",
                "IOAF-6044",
                "BIHZ-9351",
                "BPHD-7330",
                "EITW-2105",
                "BTEU-2754",
                "BNDU-6670",
                "CTSU-3251",
                "SPSP-5509",
                "HOET-1477",
                "OADL-9278",
                "BPPT-4470",
                "SCOI-2094",
                "HOME-6595",
                "RAES-9456",
                "WCRU-2275",
                "WPSC-8860",
                "TLLQ-8647",
                "LLTQ-1438",
                "IDDO-8596",
                "DIDO-1259",
                "CPDC-7967",
                "PDCC-5993",
                "PATC-6166",
                "QMAC-6934",
                "DEAM-9830",
                "ESUC-7959",
                "SKAO-9335",
                "ASJA-7087",
                "ARCH-7859",
                "AECF-6593",
                "ASCD-3571",
                "APOI-4315",
                "AIRV-9492",
                "ANDO-9235",
                "AORE-4639",
                "ANUM-7964",
                "AAGD-9308",
                "ADCF-3867",
                "AHAC-2440",
                "AAME-8519",
                "AIOS-7044",
                "AHAX-7979",
                "AATH-6475",
                "ACAA-5691",
                "AIOV-2781",
                "ASOG-9199",
                "AOPO-3831",
                "AOUP-1967",
                "ASOS-3211",
                "AAMC-1054",
                "AHOD-3920",
                "ARSO-4469",
                "AMOA-4475",
                "AAME-6801",
                "ALPE-1049",
                "ASOV-6897",
                "AOAP-9817",
                "AALP-1663",
                "BAWE-8383",
                "BSPD-6762",
                "BDOL-3544",
                "BDOX-6962",
                "BEOI-9052",
                "BSOG-5765",
                "BGMJ-1522",
                "BRCE-5192",
                "BSPI-3835",
                "BEPO-3977",
                "BSSX-5794",
                "BTCF-2832",
                "BSJJ-1221",
                "CEUR-6090",
                "CAER-6528",
                "CMDO-3058",
                "CSQP-6328",
                "CRMU-5825",
                "CAMP-8690",
                "CLNQ-7556",
                "CCOW-6880",
                "CBLO-2321",
                "CCLL-8338",
                "CDOK-3997",
                "CSPC-3445",
                "CCMC-5810",
                "CABS-3587",
                "CAAA-3644",
                "CLAL-1970",
                "CFOP-2939",
                "CLSN-2043",
                "CMND-8511",
                "CNDO-4688",
                "CNND-2263",
                "CVAT-6246",
                "CMLA-4693",
                "C-CO-4038",
                "CBGT-4842",
                "CSDO-1755",
                "CARO-1356",
                "CMPS-8716",
                "CCSP-3616",
                "CEDF-5014",
                "CSAL-9793",
                "CCFF-1779",
                "CCLQ-8346",
                "CUSI-8678",
                "DRLT-3591",
                "DTUV-2310",
                "DAOL-5957",
                "DSOP-6423",
                "ECOX-4378",
                "ESDO-4165",
                "EGPG-9993",
                "EDOC-4835",
                "EACF-5611",
                "EROC-6299",
                "EDOE-9905",
                "EGIO-3593",
                "EIIF-1132",
                "ESDO-5507",
                "EBOI-9254",
                "ELAL-4391",
                "EATE-5847",
                "ESSC-7251",
                "ESOG-7273",
                "ESSF-4260",
                "ECIT-6220",
                "EUCR-6865",
                "EHUO-3975",
                "ENPU-2541",
                "EIFS-7017",
                "ELAA-9166",
                "ECQQ-8220",
                "EACL-1289",
                "EHRC-4765",
                "ELKT-5927",
                "EMCF-3502",
                "EECC-2746",
                "EPDO-7307",
                "FOEG-3179",
                "FSPF-3851",
                "FSOY-9064",
                "FMRI-2392",
                "FOTM-3196",
                "GFTJ-5340",
                "GSCI-7453",
                "GURJ-2919",
                "GDOP-7843",
                "GHWT-1851",
                "GATE-7469",
                "GSOZ-8054",
                "GAAS-8861",
                "GEGP-5498",
                "GHCF-7091",
                "GLFP-9818",
                "GIUD-4004",
                "GBSO-3984",
                "GARD-4216",
                "GPNL-1549",
                "GMAM-1768",
                "GIVL-4110",
                "HERC-6723",
                "HSRU-6218",
                "HEUO-3154",
                "HXEQ-2813",
                "HOAD-9472",
                "HOAR-4381",
                "HOML-3330",
                "HOSM-4919",
                "HOSM-8515",
                "HAAC-5907",
                "HFOU-2144",
                "HGWT-9961",
                "HSIO-1166",
                "HRCE-8954",
                "IRCF-9236",
                "IAAM-4336",
                "ICCF-1579",
                "ISBC-1194",
                "IPRC-2134",
                "IGSC-4886",
                "IRDO-8554",
                "ISCF-1206",
                "IIOF-3659",
                "IMDL-1209",
                "ICFC-1077",
                "ISOL-7316",
                "JSNI-3568",
                "JJBN-8859",
                "JAIF-4394",
                "JRIF-3170",
                "KIVF-7787",
                "KRCF-8086",
                "KSTI-9043",
                "LCCJ-9240",
                "LAAY-8283",
                "LENG-8600",
                "LMEZ-5703",
                "LOBU-7624",
                "LACE-3055",
                "LFOA-9639",
                "LIOE-7115",
                "LIOB-8625",
                "LOGP-2068",
                "LSDT-2768",
                "LAPC-8037",
                "LPAP-7403",
                "MFOE-2412",
                "MSOA-2227",
                "MDOD-2399",
                "MBCF-9292",
                "MIPB-4509",
                "MOCF-3893",
                "MOHC-2935",
                "MSVE-7800",
                "MSDT-7112",
                "MSTC-3134",
                "MCND-1077",
                "MMWI-5019",
                "MRDO-8032",
                "MAML-4257",
                "MESF-6896",
                "MPAS-4485",
                "MMWI-9864",
                "MBND-8051",
                "MSIO-5370",
                "MFOY-9421",
                "NFMI-5808",
                "NPEU-5938",
                "NHOU-1705",
                "NCDO-4217",
                "NCND-2122",
                "NIOJ-4809",
                "NDOA-3151",
                "NDOC-2859",
                "NDOC-1855",
                "NDOO-6123",
                "NDOP-9380",
                "NDOS-6575",
                "NDOW-8236",
                "NDOC-9538",
                "NLOO-9379",
                "OHSU-1015",
                "ODOW-9122",
                "ONLO-7221",
                "OISO-2731",
                "OEGI-3009",
                "ORAM-9290",
                "OMSI-3912",
                "OSOG-5039",
                "OUIA-3760",
                "OUPT-2042",
                "OIOQ-4202",
                "OGLF-2102",
                "OPPT-2591",
                "PDOH-9593",
                "PRUS-9378",
                "PUQB-6414",
                "PPSO-2605",
                "PRPM-5616",
                "PSWD-9772",
                "POGA-6619",
                "PENU-1664",
                "PSNR-4061",
                "PMBF-2470",
                "PDOA-7176",
                "PAPF-3051",
                "PCFL-6146",
                "PCPR-3155",
                "PFOF-8024",
                "PLVO-9725",
                "PFOL-9541",
                "PATC-3682",
                "PDOP-3998",
                "PAAG-6291",
                "PCFC-4460",
                "PRMI-1701",
                "PSIN-3557",
                "PJSK-7261",
                "PAIR-1854",
                "PAOI-4292",
                "PHND-7551",
                "PLIC-7219",
                "PSOR-9203",
                "PAHD-7352",
                "PEOU-7144",
                "PCHS-1948",
                "PSFC-6076",
                "PTIM-2262",
                "PDOW-9574",
                "PEDO-1012",
                "QFOI-8175",
                "RDOM-8934",
                "ROAB-5487",
                "RICF-5979",
                "RSCY-7580",
                "RFOT-5397",
                "REOC-6646",
                "RIFT-2379",
                "RAIQ-2329",
                "RSOA-4556",
                "RAEE-5032",
                "SOXT-1036",
                "SBSM-1605",
                "SARI-9924",
                "SIAS-5771",
                "SMAT-8711",
                "SMOT-2998",
                "SPRG-9759",
                "SCOH-5941",
                "SWDS-2501",
                "SCFS-1110",
                "SSOE-9279",
                "SACA-4365",
                "SESC-1013",
                "SJCF-2005",
                "SPAI-4702",
                "SSCF-1506",
                "SDOY-7322",
                "SEPX-8613",
                "SASQ-3823",
                "SSOJ-5123",
                "SOUS-2294",
                "SDOK-6600",
                "SCIO-4391",
                "SPRU-1341",
                "SBDO-8552",
                "SGCM-6845",
                "SOAE-5868",
                "SOAD-6856",
                "SOJR-5926",
                "SOSJ-5986",
                "SOTB-8631",
                "SSND-1118",
                "TCFB-7275",
                "TARF-1987",
                "TPRP-7948",
                "TSUL-5925",
                "TIFC-9528",
                "TMAG-1365",
                "TIIO-3699",
                "UCFP-6105",
                "UCIP-2381",
                "UPLF-3075",
                "VSCF-6485",
                "VFYY-6001",
                "WOLP-2372",
                "WIOM-4773",
                "WTCF-5837",
                "WARH-6864",
                "BDIE-2325",
                "DOBU-9522",
                "BIUY-5436",
                "UOOB-7406",
                "BCFM-7289",
                "CFOS-2674",
                "CFQC-1725",
                "CFTS-9461",
                "CBLA-3225",
                "DOCU-1175",
                "CRLU-4119",
                "CHLW-2463",
                "FOCU-1910",
                "CTSU-3828",
                "DOCS-3230",
                "OUCS-6790",
                "OUDF-4743",
                "DOBU-2767",
                "DPLF-6287",
                "DOES-7435",
                "DOEU-3705",
                "DOES-4483",
                "CFEM-3904",
                "FOAA-5003",
                "FOLP-2477",
                "FOPU-2721",
                "FOHI-9601",
                "HAPQ-9104",
                "FOHU-4899",
                "IIYT-5025",
                "ICLO-3313",
                "IFEI-3328",
                "IOCS-3393",
                "IMIQ-6453",
                "OIIH-2719",
                "OCFI-8278",
                "JIWM-7812",
                "JRHK-3619",
                "FOLU-1390",
                "DOMU-8163",
                "MIUO-5264",
                "MCET-3434",
                "FOMA-1885",
                "NPLB-4663",
                "NDOM-9874",
                "NAGH-2465",
                "DOOU-1504",
                "OCFG-1701",
                "OCFH-3323",
                "ODOI-7757",
                "OPAH-2118",
                "OUMS-8992",
                "OUPL-8911",
                "DOPU-1194",
                "DOPS-7411",
                "DOPA-9199",
                "PRGC-1824",
                "RIBF-5918",
                "ROFM-8735",
                "RLFA-2028",
                "RHXQ-6577",
                "SBSO-7504",
                "SOAU-8267",
                "SOGA-6679",
                "DOSP-6055",
                "TIVX-6600",
                "FOTA-7104",
                "WCFH-2988",
                "WFVQ-8583",
                "DOZU-3484",
                "CLKA-5446",
                "CNRL-4233",
                "CWBZ-1017",
                "CTGG-4226",
                "CFSX-9943",
                "CCTJ-3529",
                "CLAU-4600",
                "C1CN-3075",
                "CNFF-6642",
                "CBIP-1783",
                "CBDJ-4862",
                "CFNP-8079",
                "CMFH-7305",
                "CBNA-8233",
                "CBPJ-4682",
                "CLTQ-4379",
                "CNTP-8045",
                "CFWP-1963",
                "CTAI-8742",
                "CTXU-4237",
                "DHLN-1564",
                "DDCU-7548",
                "DTVR-5956",
                "DWHD-3318",
                "EMFB-1044",
                "EMPP-4736",
                "EMBF-7753",
                "EHXD-2454",
                "EAYF-2376",
                "EPNK-8688",
                "EL1K-2518",
                "EL1V-9701",
                "ERLS-4188",
                "ERLU-6217",
                "ERPZ-4744",
                "FOCS-2592",
                "GOBI-1921",
                "JJDM-4377",
                "JJDT-8002",
                "JAYP-7477",
                "JATB-1534",
                "JDHE-1119",
                "JUTE-5596",
                "L1CB-6858",
                "LAJR-2298",
                "LCTO-4835",
                "LTZG-7367",
                "MALY-9041",
                "MNLH-8157",
                "MYQH-2031",
                "MBLF-6746",
                "MBNN-1250",
                "MBDB-1795",
                "MNVK-9353",
                "MSSW-8189",
                "MIDB-2939",
                "MIEL-3268",
                "MFHK-4759",
                "MNOA-4723",
                "OWBS-1873",
                "PLEF-7940",
                "PRCW-7331",
                "PAQD-8765",
                "PACW-9541",
                "POJD-7619",
                "P1EL-5285",
                "PCLI-4334",
                "PMTN-4257",
                "RRTK-5449",
                "IELG-3120",
                "RIEX-1535",
                "RLAZ-1361",
                "RDKD-2667",
                "RO12-5589",
                "SCBA-7762",
                "STRW-3325",
                "SCWD-2203",
                "SLPZ-2687",
                "STFF-4610",
                "SIZG-3854",
                "SSDA-4802",
                "SSAW-2244",
                "SSCU-1392",
                "SAEP-3487",
                "TSEO-8480",
                "THDP-9637",
                "TI2C-1853",
                "TERP-6789",
                "VFIU-7257",
                "VLKU-3369",
                "VWLE-4243",
                "WWAF-5687",
                "WQBJ-2049",
                "WJLA-3972",
                "APBT-4784",
                "ABSO-1754",
                "BDSV-4589",
                "BABP-1813",
                "DPYC-6459",
                "EPVF-9921",
                "GDIP-6267",
                "GIIT-7347",
                "HEKW-1552",
                "HIPC-8141",
                "ISDK-7034",
                "IDUJ-9235",
                "POCC-2351",
                "POAH-7943",
                "PDSK-8396",
                "POGJ-2915",
                "POPI-9960",
                "SBLS-8715",
                "SPIS-3702",
                "SPBI-3849",
                "TOPD-2738",
                "ECAP-2666",
                "EGRH-7769",
                "EIKU-6545",
                "GELX-9638",
                "POSG-3542",
                "SGEU-3080",
                "UGXN-7941",
                "ANEH-4575",
                "AR1C-9128",
                "AR1A-3097",
                "AEJZ-6871",
                "AHBL-5481",
                "AMTM-1263",
                "BAIT-6872",
                "BTCW-6801",
                "BE1G-7846",
                "BH4T-3386",
                "BH1P-9345",
                "BH1T-6247",
                "BHS1-7848",
                "BIDW-7048",
                "BITI-7998",
                "BPHS-2634",
                "BPHI-1893",
                "BVOW-4937",
                "CCSA-2794",
                "CEHM-9801",
                "C1BS-9146",
                "CBIR-4863",
                "CFSH-6257",
                "CSRT-1507",
                "C2BP-3294",
                "CSCI-5722",
                "CBHX-5324",
                "CEHR-1690",
                "CNII-5094",
                "CGSC-7024",
                "CSI1-5817",
                "EMBH-5918",
                "EMWH-5657",
                "EHBM-1218",
                "EHQF-5553",
                "ECWB-5669",
                "EH1J-7639",
                "EH1B-1444",
                "EHP1-4063",
                "FHP1-5960",
                "FH1Y-3656",
                "FRTW-8572",
                "HOEE-3595",
                "HOWW-1763",
                "HFEC-6987",
                "HCVX-9403",
                "IH1F-4808",
                "IFFL-1978",
                "IH1C-5443",
                "L1CJ-6223",
                "MEPH-2211",
                "MBSH-8454",
                "MIFK-1843",
                "OOIR-6164",
                "P1BS-8250",
                "P1SW-9317",
                "SCIB-7795",
                "TCUS-7003",
                "TRCC-3919",
                "TYWK-9872",
                "THWP-2030",
                "TESE-1638",
                "TSHC-5325",
                "TSSH-3091",
                "VEHU-7609",
                "VBRF-5472",
                "VBWH-3455",
                "VSHA-1177",
                "WITE-3429",
                "WS1M-5343",
                "WI1C-8151",
                "WITM-9784",
                "WWIH-5246",
                "WWIB-4280",
                "WIA–-9555",
                "A–IR-9006",
                "CWDP-1792",
                "EEPE-1558",
                "EWRS-1314",
                "EOGA-2503",
                "EHOE-2373",
                "EOEE-5220",
                "EUZE-8042",
                "EULB-4398",
                "EEIX-3711",
                "EECU-9416",
                "EINZ-4948",
                "EMPS-4300",
                "EMIC-6057",
                "ERBP-1813",
                "IRIT-7957",
                "IRDW-2661",
                "IRS1-2053",
                "MEPA-9312",
                "POTE-2286",
                "PGOI-9915",
                "POMI-7721",
                "SU1U-2131",
                "SIEM-8181",
                "WDIE-7217",
                "WPNA-1976",
                "AGPT-9732",
                "ALHL-3993",
                "ACEG-8981",
                "BEUG-1441",
                "C1PU-9387",
                "CPTU-8397",
                "CGPW-5236",
                "CPDX-2010",
                "CACX-6112",
                "DTKR-8102",
                "DMMX-6824",
                "EMQE-6431",
                "ETYZ-4812",
                "ERVX-4564",
                "ELEY-6369",
                "FNEQ-3064",
                "GPCM-6144",
                "GDPV-1768",
                "GPXI-4113",
                "HSDV-2555",
                "HOPX-4247",
                "JSFW-9307",
                "KATG-5319",
                "LHRO-2114",
                "LYGQ-4120",
                "MHRM-6498",
                "MKJW-3401",
                "MZGK-6435",
                "NOBB-2322",
                "POMT-4486",
                "POHY-6262",
                "POHN-4827",
                "POKX-6907",
                "POLT-4031",
                "POLH-3717",
                "POMP-8240",
                "POPO-1283",
                "POPI-9940",
                "PORX-5254",
                "POSD-5056",
                "POWP-7232",
                "PAAI-7623",
                "PRVQ-5343",
                "PTAT-5181",
                "PTC1-4468",
                "PKGP-9776",
                "SNNG-3258",
                "SILT-1792",
                "SIWU-8680",
                "BDPW-5628",
                "BFPS-6857",
                "BGPS-6312",
                "BPGS-5228",
                "BP1G-5400",
                "CPTY-8115",
                "CPTI-4043",
                "CGNE-8985",
                "CLEN-3235",
                "CPTT-2627",
                "EUPG-3051",
                "GTOP-1356",
                "HOWP-9612",
                "M–RS-8137",
                "MBGE-5940",
                "MBGP-8375",
                "PFOC-3255",
                "PWCI-7918",
                "BCKM-5787",
                "CPMQ-3965",
                "DBTL-4163",
                "GBLO-8421",
                "MITD-6097",
                "OCBG-2855",
                "PSMJ-5445",
                "PIAM-6829",
                "PAAV-8242",
                "SSMH-3362",
                "CFTG-9995",
                "CWWR-5359",
                "FPCT-6192",
                "FLYE-9426",
                "FTPG-4554",
                "FTCF-8348",
                "FTFT-1924",
                "FTWT-6872",
                "FWIT-4426",
                "JACB-6279",
                "MWWB-7796",
                "MWWT-6083",
                "PCFT-1844",
                "RIBF-2128",
                "RWWP-2464",
                "SFTW-8068",
                "WISM-6482",
                "WITB-4941",
                "WVPP-5722",
                "WEIT-6445",
                "WLF1-9217",
                "WWCV-2535",
                "AAID-8934",
                "BHCS-1385",
                "BLGR-6959",
                "C2GL-6579",
                "CEAH-5295",
                "CRLQ-6453",
                "CRBP-1336",
                "CHPN-1362",
                "CRPJ-7120",
                "CUUL-3061",
                "CXFN-1522",
                "CSAH-4293",
                "CDBN-6853",
                "CIWG-7052",
                "DEIN-9878",
                "ECRE-7399",
                "EIHK-2058",
                "ETOT-1144",
                "EOCT-3629",
                "ENJH-6458",
                "ELCC-4518",
                "FA:L-3601",
                "GEPY-2094",
                "GLLI-1815",
                "GLP1-9883",
                "GGZA-4903",
                "GIHJ-2832",
                "GLLW-7555",
                "HJPG-4206",
                "HVWC-8772",
                "HAOO-7463",
                "HOAI-8372",
                "HOAR-5595",
                "HOEL-7436",
                "HOEC-2117",
                "HOPT-9572",
                "HOTE-1426",
                "HOTM-5176",
                "HOTS-7227",
                "HOTW-4891",
                "HOVL-3139",
                "HGMP-1497",
                "HTRR-4475",
                "HEMN-1279",
                "IOJH-9938",
                "IHOF-2951",
                "ITCV-3277",
                "ITEL-5842",
                "ITLT-5416",
                "LLLI-3444",
                "LIIF-2670",
                "LDVS-4313",
                "LTPZ-5211",
                "MOTA-8350",
                "CBYA-5864",
                "MAHS-6630",
                "MAAP-3037",
                "MCHM-4866",
                "MEDZ-9535",
                "MTUA-4641",
                "MELB-5185",
                "MCEH-5869",
                "MCPR-4025",
                "MDHT-1342",
                "MHOA-4958",
                "MIKS-7613",
                "MJLV-3199",
                "MAHN-6143",
                "MOWA-4097",
                "MAAH-1892",
                "MILT-1407",
                "NHCS-7844",
                "NMAS-2012",
                "PHLS-2391",
                "PL1W-4842",
                "PMAT-4195",
                "PMTA-9441",
                "PSRC-3492",
                "PSTG-9898",
                "PRAX-4794",
                "PRMU-1448",
                "PILA-3263",
                "RIAC-9356",
                "RAIG-7750",
                "ROTH-6923",
                "REHS-1438",
                "SCIE-4315",
                "SHAO-1858",
                "SCTV-3286",
                "SOHW-5021",
                "SAPO-6587",
                "SAIJ-3639",
                "SATT-5042",
                "TITW-2642",
                "TOSP-9275",
                "TPON-3655",
                "UGWH-1295",
                "UABN-1486",
                "VAAL-4863",
                "VDPW-9842",
                "VEQO-4419",
                "WC1X-3399",
                "ZTHN-9951"
        };
    }
}
