package me.quyen.entities.fakadata;

import java.util.concurrent.ThreadLocalRandom;

public class FacultyData {
    public static String facultyName(){
        return namesAndCodesOf()[0];
    }
    public static String facultyCode(){
        return namesAndCodesOf()[1];
    }
    public static String[] namesAndCodesOf(){
        int chosenInt = Math.min(facultyNames().length, facultyCodes().length);
        int rInt = ThreadLocalRandom.current().nextInt(0,chosenInt);
        return new String[]{
            facultyNames()[rInt],facultyCodes()[rInt]
        };
    }
    public static String[] facultyNames(){
        return new String[]{
                "Ruskin School of Art",
                "Faculty of Classics",
                "Faculty of English",
                "Faculty of History",
                "History of Art Faculty",
                "Faculty of Linguistics, Philology and Phonetics",
                "Faculty of Medieval and Modern Languages",
                "Faculty of Music",
                "Faculty of Oriental Studies",
                "Faculty of Philosophy",
                "Faculty of Theology and Religion",
                "Faculty of Economics",
                "Faculty of Education",
                "Faculty of Law",
                "Institute of Criminology",
                "Lauterpacht Centre for International Law",
                "Faculty of Earth Sciences and Geography",
                "Faculty of Mathematics",
                "Faculty of Applied Mathematics and Theoretical Physics",
                "Centre for Theoretical Cosmology",
                "Institute of Theoretical Geophysics",
                "Faculty of Physics and Chemistry",
                "Institute of Astronomy",
                "Faculty of Chemistry",
                "Faculty of Materials Science and Metallurgy",
                "Faculty of Physics (Cavendish Laboratory)",
                "Faculty of Engineering",
                "Institute for Manufacturing",
                "Faculty of Business and Management",
                "Judge Business School",
                "Faculty of Computer Science and Technology",
                "Faculty of Chemical Engineering and Biotechnology",
                "School of Medicine faculty",
                "Freeman Spogli Institute faculty",
                "School of Humanities and Sciences faculty",
                "Graduate School of Education faculty",
                "School of Earth Sciences faculty",
                "Graduate School of Business faculty",
                "Law School faculty",
                "School of Engineering faculty",
                "Cardiovascular System and Hematology",
                "Dentistry Dimitrius Tziafas",
                "Gastroenterology and Hepatology",
                "General and Internal Medicine",
                "Genetics and Hereditary",
                "Obstetrics and Reproductive Medicine",
                "Aeronautics and astronautics",
                "Biology/biochemistry/medicine",
                "Chemistry",
                "Graduate School of Business",
                "Communication",
                "Computer science",
                "Economics",
                "Education",
                "Engineering",
                "History",
                "International relations",
                "Law",
                "Linguistics",
                "Literature and arts",
                "Mathematics and statistics",
                "Political science",
                "Philosophy",
                "Physics",
                "Psychology",
                "Coaches",
                "Neural computation in the visual system",
                "Interface between physics and biology",
                "Neuro-immune interactions in brain health and disease",
                "Quantitative and behavioral neurophysiology",
                "Neural dynamics of cognitive control",
                "Neural bases of cognitive control",
                "Reward, learning and decision making, computational psychiatry",
                "Neurovirology",
                "Neural circuits for social behaviors",
                "RNA localization and translational control in dendrite morphogenesis",
                "Learning, memory and olfaction",
                "Neuromechanics and communication",
                "Neurogenesis and hippocampal function",
                "Brain basis of consciousness",
                "Hierarchy of processing timescales and brain-to-brain communication",
                "Neural basis for visual attention, comparative primate electrophysiology",
                "Whole-brain neural dynamics underlying behavior",
                "Molecular and neural basis of behavioral evolution",
                "Neural mechanism of sensorimotor integration and behavior",
                "Molecular mechanisms of aging",
                "Learning and decision making, computational psychiatry",
                "Cognitive neuroscience of learning and memory",
                "Jonathan Pillow - Neural information processing, machine learning, and statistical modeling of neural data",
                "Structure and function of neural circuits",
                "Neural and behavioral dynamics in simple organisms",
                "eural circuit dynamics",
                "Motor control and learning",
                "Cognitive neuroscience of social cognition and behavior",
                "Dynamics and learning in neural circuits",
                "Neural circuits underlying reward",
                "Business policy and strategy",
                "Indigenous business management",
                "Business ethics",
                "Tribal sovereignty and enterprises",
                "Knowledge management systems",
                "Data analytics",
                "Research methods",
                "Financial and managerial accounting",
                "Financial and managerial auditing",
                "Financial reporting",
                "Auditing",
                "Benford’s Law",
                "Corporate consolidation and IFRS",
                "Data science and analytics",
                "Predictive modeling",
                "Optimization operations research",
                "Simulation",
                "Applied probability and statistical modeling",
                "Business analytics",
                "Operations research",
                "Supply chain management",
                "Quantitative analysis in sports",
                "Entrepreneurship",
                "New ventures",
                "Small business",
                "Small technology firms",
                "Leadership",
                "Principles of Management",
                "Accounting Information Systems",
                "Certified Public Accounting",
                "Managerial Accounting",
                "Venture capital funding",
                "Corporate control",
                "Corporate governance",
                "Entrepreneurial finance",
                "Capital budgeting and risk",
                "Financial institutions",
                "Banking systems and cost structures",
                "Industrial organization",
                "Labor economics",
                "Microeconomics",
                "Game Theory and Behavioral Economics",
                "Regional Economics",
                "Environmental Economics",
                "Applied Econometrics",
                "Economic Development",
                "Corporate social responsibility",
                "Corporate communication",
                "School-business partnerships",
                "Cross-cultural management",
                "Organizational behavior",
                "Hospitality management",
                "Sustainable tourism",
                "Travel motivations and behavior",
                "Austrian economics",
                "Evolution of Economic Thought",
                "Microeconomic Theory",
                "Public Choice/Public Sector Economics",
                "Veterinary Diagnostic Pathology",
                "Materials Science and Metallurgy",
                "Intellectual Property Law",
                "Mathematics for Operational Research",
                "East Asian Studies",
                "Physiology, Development, and Neuroscience",
                "Determined upon appointment",
                "Public Health and Primary Care",
                "Epidemiology and Medicine",
                "Clinical Biochemistry and Medicine",
                "School of the Biological Sciences",
                "Animal Embryology",
                "Molecular Endocrinology",
                "Fluid Mechanics",
                "Computer Science and Technology",
                "Chemical Engineering and Biotechnology",
                "Quantum Physics",
                "Marketing, Strategy, and Innovation",
                "Plant Systematics and Evolution",
                "Health Neuroscience",
                "Information Engineering",
                "Modern Arabic Studies",
                "Experimental Medicine",
                "Ecology and Evolutionary Biology",
                "Sustainable Reaction Engineering",
                "Chinese Development",
                "Arts, Humanities, and Social Sciences",
                "Education, Development and Learning",
                "Infrastructure Geotechnics",
                "Crop Science",
                "Deep History and Archaeology of Africa",
                "Digital Humanities",
                "Technology and Innovation",
                "Anthropology of Inner Asia",
                "Autism Research",
                "Penal Theory and Ethics",
                "Organisational Behaviour",
                "Electrical and Computer Engineering",
                "UKREC Director",
                "Extension Administration Research and Education Center",
                "Animal And Food Sciences",
                "Biosystems And Agricultural",
                "Engineering Entomology",
                "Horticulture Plant And Soil Sciences",
                "Plant Pathology",
                "Regulatory Service"
        };
    }

    public static String[] facultyCodes(){
        return new String[]{
                "RSOA-4150",
                "FOCC-9399",
                "FOEN-6925",
                "FOHW-2893",
                "HOAF-6397",
                "FOLP-9166",
                "FOMA-1375",
                "FOMB-6100",
                "FOOS-6186",
                "FOPI-7136",
                "FOTA-7658",
                "FOED-2130",
                "FOEB-8607",
                "FOLW-2045",
                "IOCC-3574",
                "LCFI-4937",
                "FOES-4824",
                "FOML-5269",
                "FOAM-2836",
                "CFTC-2627",
                "IOTG-8965",
                "FOPA-5169",
                "IOAW-2127",
                "FOCL-3255",
                "FOMS-1857",
                "FOP(-8863",
                "FOEX-7513",
                "IFMI-3682",
                "FOBA-1254",
                "JBSH-7758",
                "FOCS-8332",
                "FOCE-6533",
                "SOMF-9144",
                "FSIF-2798",
                "SOHA-5517",
                "GSOE-6231",
                "SOES-4245",
                "GSOB-7002",
                "LSFQ-1495",
                "SOEF-2703",
                "CSAH-9629",
                "DDTO-8908",
                "GAHF-5000",
                "GAIM-3667",
                "GAHE-4094",
                "OARM-2665",
                "AAAJ-8873",
                "BOYV-3143",
                "CLQA-2685",
                "GSOB-5192",
                "CVGF-2522",
                "CSXH-8740",
                "EOSK-8087",
                "EDZY-7784",
                "EJOD-4375",
                "HVNB-5297",
                "IRHY-9346",
                "LEAF-8914",
                "LTDR-9988",
                "LAAS-3517",
                "MASP-4091",
                "PSOX-2999",
                "PPMY-4890",
                "PEFA-2011",
                "PVWI-8632",
                "CORJ-1335",
                "NCIT-7469",
                "IBPA-8696",
                "NIIB-3714",
                "QABN-3660",
                "NDOC-1009",
                "NBOC-3015",
                "RLAD-6116",
                "NRNU-5734",
                "NCFS-7678",
                "RLAT-1927",
                "LMAO-6169",
                "NACC-4690",
                "NAHF-6425",
                "BBOC-6980",
                "HOPT-8683",
                "NBFV-2119",
                "WNDU-6107",
                "MANB-7634",
                "NMOS-2291",
                "MMOA-5037",
                "LADM-1458",
                "CNOL-9023",
                "JP-N-3774",
                "SAFO-7479",
                "NABD-3761",
                "ECDR-9161",
                "MCAL-3111",
                "CNOS-2335",
                "DALI-6462",
                "NCUR-9320",
                "BPAS-2514",
                "IBMJ-3761",
                "BEOK-4007",
                "TSAE-5704",
                "KMSG-7755",
                "DAFF-2412",
                "RMYD-2770",
                "FAMA-4143",
                "FAMA-3013",
                "FRLE-1537",
                "ABNN-1963",
                "BLBG-5985",
                "CCAI-9241",
                "DSAA-9438",
                "PMMP-9494",
                "OORE-2393",
                "SANF-7478",
                "APAS-8508",
                "BAKU-2775",
                "ORSG-3219",
                "SCMY-8816",
                "QAIS-1300",
                "ELMT-1522",
                "NVNU-2011",
                "SBTQ-7406",
                "STFK-8954",
                "LXRD-2202",
                "POMI-3793",
                "AISJ-6174",
                "CPAY-2036",
                "MAFP-3206",
                "VCFT-6125",
                "CCRX-5450",
                "CGLN-8123",
                "EFYC-6971",
                "CBAR-2352",
                "FIJO-8921",
                "BSAC-6453",
                "IOAF-4442",
                "LELM-2227",
                "MTPN-7652",
                "GTAB-9805",
                "REPZ-6721",
                "EENZ-7426",
                "AEQE-7839",
                "EDXN-6498",
                "CSRN-1307",
                "CCCD-4993",
                "SPSP-2879",
                "CMFT-8876",
                "OBWX-7706",
                "HMUQ-2515",
                "STCH-2004",
                "TMAB-4569",
                "AEBU-1489",
                "EOET-2542",
                "MTER-9273",
                "PCSE-7607",
                "VDPT-6817",
                "MSAM-4289",
                "IPLJ-6605",
                "MFOR-4584",
                "EASU-8032",
                "PDAN-6240",
                "DUAP-2987",
                "PHAP-4648",
                "EAMV-2600",
                "CBAM-7167",
                "SOTB-1601",
                "AEFN-8090",
                "METM-6030",
                "FMUH-9881",
                "CSAT-6254",
                "CEAB-4329",
                "QPYU-6717",
                "MSAI-9981",
                "PSAE-8856",
                "HNKH-3372",
                "IEKA-2285",
                "MASM-6644",
                "EMWC-9528",
                "EAEB-5264",
                "SREZ-8762",
                "CDPZ-3218",
                "AHAS-1820",
                "EDAL-5201",
                "IGMG-2330",
                "CSJB-8020",
                "DHAA-9330",
                "DHAE-3540",
                "TAIZ-7206",
                "AOIA-9199",
                "ARKF-4880",
                "PTAE-4359",
                "OBGJ-8875",
                "EACE-8016",
                "UDDX-6857",
                "EARA-2591",
                "AAFS-4807",
                "BAAE-6246",
                "EECJ-2407",
                "HPAS-7329",
                "PPVG-4011",
                "RSFC-8858"
        };
    }
}
