package me.quyen.entities.fakadata;

import java.util.concurrent.ThreadLocalRandom;

public class LibraryData {

    public static String libraryName(){
        return nameUrlEmailCode()[0];
    }
    public static String libraryUrl(){
        return nameUrlEmailCode()[1];
    }
    public static String libraryEmail(){
        return nameUrlEmailCode()[2];
    }
    public static String libraryCode(){
        return nameUrlEmailCode()[3];
    }
    public static String[] nameUrlEmailCode(){
        int chooseInt = Math.min(libraryCodes.length, libraryNames.length);
        int rint = ThreadLocalRandom.current().nextInt(0, chooseInt);
        String libName =  libraryNames[rint];
        String libCode =  libraryCodes[rint];
        String http = "https://www.";
        String[] domainTails = new String[]{".com",".net",".org",".me"};
        String[] mailTails = new String[]{"@gmail.com","@hotmail.com","@live.look","@yahoo.com", "@email.me"};
        String tname = libName.replace(" ","").toLowerCase();
        String email
                = tname + mailTails[ThreadLocalRandom.current().nextInt(0,mailTails.length)];
        String urlString = http + tname
                + domainTails[ThreadLocalRandom.current().nextInt(0, domainTails.length)];
        return new String[]{libName,urlString,email,libCode};
    }

    private static final String[] libraryCodes = {
            "BHQ-752","WLY-504","NOI-352","PPK-866","BSH-376","EPV-635","PTQ-378","PPK-100","SBM-184","SSW-879","PPZ-754","BHD-550",
            "KJY-769","BHQ-851","BHJ-479","MMF-553","OMX-470","MRL-194","CCP-688","LSU-731","WPS-304","BRC-684","LLG-846","COF-948",
            "PTF-588","SVW-338","WWD-976","WWP-512","QQF-608","IIK-178","SLQ-627","IAG-353","PTA-818","SCI-197","NNN-842","TRZ-396",
            "FBE-679","BBN-366","PPK-453","IIP-844","POJ-123","IJD-555","EES-434","DDL-729","HOZ-102","BDG-283","RRR-780","LLI-802",
            "LOU-532","BOX-663","SSJ-164","III-677","RCG-385","NDX-221","WWB-214","LLV-313","SHV-636","OBD-264","LLA-725","SSO-832",
            "WNG-554","LOE-366","CMQ-148","CCG-276","BOG-296","WWX-995","DDH-153","SCS-874","LEU-738","ABH-913","EEJ-748","TBJ-597",
            "SJC-376","WLY-148","TBX-920","IIM-116","BCV-735","DCB-579","NNF-498","CRW-839","NNA-906","ILB-459","PPR-984","PAD-318",
            "NHY-522","KHE-535","BTQ-772","PTU-343","BBJ-255","BBX-241","SSP-295","QBN-945","CVJ-419","WWS-989","LLH-787","ILB-330",
            "TBR-679","OBW-105","WWX-151","BRV-672","DLS-483","BBQ-552","BBN-390","BTR-971","PPV-586","TQV-377","SSB-800","LLQ-366",
            "CCC-606","RHY-459","TKJ-512","WSJ-930","BTB-734","POA-990","PTE-571","LPZ-110","BBV-486","AOX-133","EPX-680","BHU-706",
            "CHR-831","LLD-545","PTW-817","KKN-521","TBK-612","TBN-175","LLT-927","RCI-629","RRX-554","TBT-471","VVM-775","IAX-833",
            "IIX-515","TLJ-611","SLA-725","BLP-164","WHV-354","LAQ-744","RRW-672","LLC-635","TBJ-502","BBM-540","LLQ-764","TLD-873",
            "LLE-798","FFP-158","BCM-190","TAN-519","NNQ-919","BBD-914","SHL-432","PPV-935","EOX-839","TLF-991","QQO-183","NNQ-580",
            "NAG-316","PPE-652","RRF-395","SSH-482","TLP-130","SSO-544","BBC-925","BBC-816","BBD-397","PTE-204","AOB-176","RRQ-771",
            "SDV-454","TNF-898","DLY-400","WWV-974","LNL-989","SAL-262","ERA-904","BNY-950","TBQ-575","SHY-574","SCF-109","TTN-866",
            "TRE-504","WWZ-538","BHW-390","BHK-606","SCR-179","MLI-623","WWT-979","BDF-499","WWQ-309","TKQ-938","BBK-412","WWP-430",
            "BPA-367","TBJ-363","IEL-711","LHK-170","KKP-871","BBR-630","DLB-130","SEK-629","TSC-827","BBM-382","IIV-807","EEN-408",
            "IJI-639","FFY-794","TRU-979","WSX-145","RRZ-553","PPE-105","SSQ-230","TBX-273","TTO-273","RRJ-737","TTB-642","WWI-741",
            "LCG-482","PTC-352","VVN-315","WVT-827","SSF-204","IIM-366","WWO-411","TRA-901","WWF-313","ECZ-313","FFQ-289","CTB-534",
            "BBY-805","LLU-547","SSY-146","RPH-130","NII-987","PLP-768","KKV-798","CLA-262","RRP-810","TBH-371","RRY-108","VVG-628",
            "FFM-105","TLI-455","VHX-371","KKG-332","LOQ-454","SSZ-146","TTH-301","BLW-880","BBA-660","CTX-498","NNA-378","AAF-338",
            "LES-575","QQP-957","LLF-307","BBE-404","BBY-721","CCU-727","BBA-757","RLM-979","BBH-575","LCU-712","QSA-623","TQO-908",
            "WWW-730","ISW-417","PPN-709","PTB-546","CTP-341","QLZ-414","CMW-340","BLM-842","PPB-801","BGD-269","TTU-161","SSM-174",
            "TTX-977","SHN-369","SSQ-883","BBS-496","PPH-416","EOS-977","CCP-610","WLJ-846","CCB-645","PLI-291","IJC-784","RRM-377",
            "TBH-475","LCP-231","PFU-482","EBH-916","IPL-853","LLI-255","BBI-641","NLQ-174","WWA-213","SLT-107","CCN-561","TTN-864",
            "SOY-253","SSU-499","SSE-496","IOZ-788","WWS-846","SSD-386","SSD-656","VLD-207","RHZ-759","KOX-607","VVV-428","IIF-884",
            "NNY-260","WWI-675","BHW-988","SSI-810","FJK-227","UBQ-647","SSM-707","LLB-960","TOX-866","OBN-352","OLP-946","SSK-401",
            "LCR-810","PPY-316","PTQ-703","CCI-745","PTK-134","TTP-288","LLK-207","KLQ-583","ELL-396","CLY-539","TTP-629","BBU-112",
            "RAH-742","PTW-928","BRI-183","SSV-134","BHC-626","PPY-688","CCX-314","ILE-191","PHV-341","NND-146","SSO-131","TRR-487",
            "WVY-975","VVQ-808","CCF-204","CCH-640","SSX-886","CTP-717","TTM-733","CLT-774","PPQ-464","BBB-124","SRG-599","WWK-526",
            "BDX-350","IIJ-935","IAM-715","RRD-419","PPG-679","FHR-411","IOA-870","LLB-926","CTU-566","IIK-877","CCZ-543","PTB-604",
            "CVI-437","SSJ-305","WLW-993","QQA-718","RRK-265","BPH-723","LLD-385","QLD-575","BBB-426","QFZ-666","DPZ-121","TBL-557",
            "LLT-920","LLM-998","BBG-978","BDS-925","CCI-830","RRO-923","PPF-150","SLI-782","PPW-559","TBZ-749","TBP-473","TLF-373",
            "NNC-912","WPH-364","TBF-331","DDP-967","BBA-400","CVA-897","CCC-623","BLT-544","PPH-687","KTQ-152","TTH-903","BSI-332",
            "RRQ-745","LLR-105","RRX-659","NNM-516","IIY-496","PTW-178","EOQ-797","ILQ-255","CCT-980","ERJ-191","CCN-148","PIX-581",
            "PBQ-484","BBB-258","FFN-322","MMD-346","PPS-761","PBL-430","PPM-690","PLS-856","IOA-402","LLQ-281","AOE-440","KIE-432",
            "BHH-732","SSD-763","NNO-578","LLF-314","DLT-977","TRB-957","BHI-388","WLL-652","MMM-286","PPO-260","BRS-482","BCA-367",
            "TIL-913","ILE-397","TTQ-303","LLM-805","IIQ-902","TBY-306","LOO-442","ELW-888","GGF-707","SQM-929","BBQ-921","RVL-846",
            "LLV-577","MMV-872","LLN-320","BBQ-540","BBS-243","FFU-278","SVD-123","DLG-674","IIF-171","CCV-322","TNI-779","SEV-413",
            "THU-450","TLO-406","PLQ-759","RJC-602","TTA-948","BBN-299","ICI-495","ILY-851","BHF-177","CCU-694","IIY-350","LSG-517",
            "TBJ-107","BBS-107","WWZ-209","CCL-822","SHR-912","PPS-926","BBS-570","NLA-937","SSA-407","QFV-646","SSW-545","LHV-888",
            "MMX-219","BLS-818","SSW-494","SCX-753","RRX-411","TLT-213","LZI-753","WLQ-865","SCV-571","IHV-804","CCM-926","EIO-803",
            "TBQ-866","TNM-308","IRX-299","TLM-313","KPS-804","PCU-639","WMB-621","PSC-116","LLF-587","MMA-575","PPP-448","SIV-997",
            "SHS-725","BHX-622","EPO-848","DBD-649","PTH-554","LDL-540","WWN-292","SLY-389","WWB-981","DDD-697","TBB-124","NVH-624",
            "TNP-918","KOK-615","LLI-462","TRJ-951","MMV-136","TRC-723","LLV-308","ORT-528","BBP-923","SSH-592","WWP-141","VCU-761",
            "WWK-325","SQM-856","KKS-251","BHG-650","BTA-775","SSS-557","FFT-942","NHI-846","CTB-509","BBT-728","PPK-759","ICK-122",
            "SCD-654","BRK-657","ISL-931","PTY-151","TLT-443","CCC-769","WPO-885","LLF-132","LES-486","SHE-331","TBU-610","PIF-998",
            "BHV-486","SSD-556","IIU-414","NNU-399","RRB-635","LSG-190","EBT-277","CCC-661","PPY-403","CCP-516","NRI-301","PSE-712",
            "BPJ-495","PCM-657","LEV-355","SRO-969","LSU-965","NVT-980","PPJ-237","BPJ-607","NNS-518","TTG-890","DRG-853","PHF-650",
            "RRM-174","RRF-788","WLA-860","LOC-227","WOQ-362","VVY-117","BLE-290","BES-349","FFX-292","RRV-237","PPK-232","CVC-609",
            "LHQ-594","NNH-359","MMY-172","BBT-418","LLH-859","SCK-913","CCS-588","RAX-329","LLS-900","EOX-220","TVN-444","WET-214",
            "TBP-267","MLU-188","RRH-224","COK-776","QFO-193","COZ-499","ELX-815","BBW-208","DPQ-262","JJD-551","SSM-151","SIK-406",
            "PPM-419","TBR-538","TBS-481","RRG-103","EOE-544","WWM-592","BLW-251","BBZ-285","PTF-113","FFB-232","VVV-979","LSO-434",
            "BBG-866","CCB-720","RAU-556","FFO-463","ECD-889","LEP-240","SGW-608","PPH-951","LLN-878","BBE-230","SHF-829","REC-133",
            "NOE-803","EBU-244","TTM-326","BWV-188","SIZ-352","BBT-573","CCT-646","CTE-859","SSL-428","HLS-942","CRN-715","CCE-324",
            "TRV-828","NIK-351","SCH-346","LEM-956","VVI-109","RRI-172","RWP-210","LLB-269","BBL-520","KNN-704","VVI-476","BVK-107",
            "WHM-296","BPG-658","PTV-162","NKY-516","SSE-999","SDH-169","BBR-139","MML-169","IIY-945","TRC-214","GOR-612","KHQ-819",
            "LHI-716","TBH-837","BJA-905","PPV-240","EMH-563","BBF-610","SSV-408","WWM-495","SHY-271","TBY-746","SJI-341","ELM-382",
            "SPX-515","TSO-430","THB-733","RRE-807","LSD-508","TTH-280","MRP-334","CCA-203","PPW-461","WVB-180","LLK-832","KOQ-527",
            "BLC-766","CAF-863","NNE-204","SSG-618","TRV-311","SSQ-903","WVV-914","IIC-283","PON-410","BHS-697","FFI-345","LEA-247",
            "COM-723","BEQ-266","PPE-205","LLN-395","BRU-926","PPE-941","LHO-526","LLY-540","TBK-236","TLV-886","IIL-611","WRM-993",
            "WSO-351","PPN-473","BBF-784","BBK-853","SHL-674","LLZ-451","TDT-385","SSA-131","BBS-300","PRW-987","DLP-884","WLI-406",
            "RRV-836","IAZ-784","IIV-259","PMU-222","CCY-874","EEJ-313","RHL-531","BBK-981","FFD-403","BOH-272","SJL-858","MPT-912",
            "PCY-495","BEA-483","BBX-416","NNV-743","PTR-736","SSF-495","LLG-734","WVK-385","WCU-234","IRP-433","IJE-828","SSH-683",
            "SSM-144","TQY-333","NOX-827","LLG-745","SSI-686","BHT-275","WWH-401","ISL-806","WWH-385","EOJ-519","TTS-470","TQE-131",
            "NES-778","WRC-850","PPC-335","BBW-350","MLQ-946","SVZ-719","SST-126","CFM-831","QKN-695","IQH-418","VVY-706","BPT-889",
            "OBU-488","TLU-606","WWA-765","CVY-402","IAB-498","PTG-921","BBW-653","KKZ-108","SSS-402","TBN-217","IIF-357","ICL-539",
            "EPG-870","SSD-204","NHS-431","RRQ-300","TBU-246","KCK-269","FFV-495","PPQ-396","BON-159","IEQ-452","BBC-460","NPU-662",
            "KKB-287","TBE-357","IKG-731","BBW-357","SSR-436","LHD-582","CCV-490","OLR-224","WTJ-653","NUW-795","VVW-530","IJL-991",
            "WHQ-368","SSY-180","CCJ-353","TTB-624","BBG-296","BLX-663","BHV-273","VVD-255","ERC-679","SSH-586","PPI-893","TLE-588",
            "BBR-249","WWQ-307","EES-553","PPP-444","IRL-120","COD-128","IPJ-994","VLR-722","LOK-411","SSE-653","PPE-597","BSR-780",
            "WWD-998","RRG-375","LLT-464","PPZ-414","FFI-832","LEA-568","WWY-182","ECZ-720","NIX-283","RIX-158","PTV-467","EPN-429",
            "BBE-312","IAT-573","ILW-462","MLS-925","NNV-270","NIZ-361","CVR-273","BDJ-825","LEF-409","WCH-268","IIP-156","TRB-767",
            "TRK-897","BAJ-872","MME-570","TTU-109","BBZ-499","WHZ-633","LOT-539","MMA-837","OBC-542","BBX-617","BSO-120","GGR-266",
            "LLA-255","ILU-662","WPI-205","CLK-503","CBP-379","FRT-613","SCY-422","LLO-214","TBA-518","BOH-484","BBX-953","ELP-544",
            "NIP-547","BNH-374","BJS-973","OBY-466","IIO-629","LON-428","CMV-598","ELO-953","TPN-626","RMI-546","RRM-366","EEE-338",
            "PTV-920","WJG-681","BBP-403","QSH-573","BCL-194","RNU-150","PTS-750","CCY-511","NNZ-984","TLR-702","WBW-428","WWW-295",
            "CVJ-551","SLQ-255","DLT-784","VVC-549","VVO-758","SSW-313","III-207","BBZ-749","SDS-482","LOX-288","CVK-677","PPA-755",
            "SRI-219","QOV-118","BBP-842","NLJ-753","LLD-678","BHL-343","WWQ-787","ILQ-701","IGR-189","BLE-291","SSK-184","VOI-746",
            "WWW-649","NSZ-702","RRJ-434","KQT-113","ROT-224","TIP-727","PTI-933","WWA-996","AAE-167","CHR-768","PPA-772","IIY-361",
            "TRY-865","TBE-338","SJG-549","BHO-882","WWC-197","LLZ-388","KKK-362","BBP-667","PPY-104","PPO-822","TBZ-587","TRY-186",
            "LHA-563","WWD-953","PTI-737","WNB-281","MMM-171","NDP-115","DLK-404","SSA-758","TBM-167","EBN-563","AAL-188","BWO-916",
            "BLG-708","BHW-196","LNK-330","LJY-176","TQB-781","BEU-279","EPH-497","TTX-551","KTE-635","MLF-766","TLC-102","SCV-284",
            "SLL-353","LSJ-884","CCR-705","PPU-696","BBH-100","LLW-351","TRJ-364","FOH-124","NST-854","BPU-479","QSO-151","WSR-619",
            "PPD-155","TNW-265","WLU-950","IIF-448","LLE-941","PPF-626","TTX-866","SSP-760","IHS-110","ILZ-367","BBZ-285","DBN-667",
            "WSV-751","TRN-198","NDS-216","SSB-540","TTQ-249","BBG-527","VVW-785","PPP-933","LVW-261","EEJ-603","TBE-638","FFN-726",
            "TBS-240","BOF-637","PBC-245","BRR-898","BBH-904","PTF-245","BHE-397","BHM-771","TBT-853","IIH-597","TBE-313","TLH-805",
            "BET-308","BLO-419","ICS-864","NNN-675","CCD-782","CCN-721","NNK-205","LNO-747","PTB-658","DDB-392","EEB-212","TBM-479",
            "BHI-864","LLE-220","WWN-461","RJQ-489","EEK-268","BOV-543","IRX-439","SRO-954","SHF-245","EEX-519","LLL-636","ILR-454",
            "TLK-882","PLH-604","MBO-460","PPG-448","PPM-775","WWL-617","LHB-774","QQQ-797","PPC-373","PPI-318","SSU-969","BHT-140",
            "TBP-562","KHA-271","PWJ-866","EHB-142","WWB-222","PTF-400","WWH-220","RRK-296","NNZ-445","BBC-685","PPZ-668","PLR-856",
            "WOB-704","OLX-521","IIG-709","NNG-904","SSV-669","CTF-662","FRL-723","LLR-649","SSR-538","DLE-917","IIF-499","WLL-732",
            "IPW-319","COU-331","NIE-418","IIB-702","IIN-781","FFU-366","TTV-593","LLH-900","WWW-677","FFK-551","WWW-702","BSC-507",
            "TLC-382","BBC-267","PCU-432","SSP-388","SHV-992","IIY-407","PHP-270","RBU-474","BBV-374","SOZ-325","LLG-541","FLS-415",
            "AOZ-674","LHX-190","LLY-328","IIU-960","MPC-382","MGR-577","NNN-535","PPK-346","PPU-799","TBJ-396","NNG-442","LZM-220",
            "WRE-220","SLY-939","SST-636","EEC-123","BBB-958","RJX-219","SSL-498","TTN-415","SSK-276","NNO-164","PTU-345","RLC-349",
            "PTZ-433","RRF-318","COL-360","WWO-568","ELZ-928","NJF-741","BBV-350","RRB-220","BBA-329","IIP-337","SSI-127","OBS-687",
            "BBD-157","NID-299","RAS-911","AAT-912","SSL-645","PPY-395","MLE-936","LLH-521","SSV-755","BCJ-656","KKR-725","MPW-685",
            "MIP-833","LON-867","IAO-352","WWN-816","LLW-831","CJL-659","EER-628","BBJ-943","DVB-401","EBM-155","WWS-933","BBF-488",
            "LHR-313","CCJ-765","EEY-441","EED-441","IRY-892","SJG-654","BBV-434","NNP-590","WQX-248","IBX-290","ILL-726","RRZ-586",
            "WHR-115","TQT-695","TTL-820","EAY-873","TTO-708","LLV-639","EEJ-900","LLE-220","ECO-397","LNT-899","BBQ-697","SSL-491",
            "BLW-361","BLG-559","CCI-373","LGH-415","SLK-427","III-489","DLR-747","WPX-968","EPM-147","FFC-680","RRE-906","IIN-277",
            "TST-902","LEU-349","IIO-167","ELT-734","WOJ-840","CJZ-894","RRX-117","LLA-599","WLA-130","URG-839","EEK-457","LSV-975",
            "TAZ-538","TTI-215","LSQ-458","DBF-683","CVA-491","PJG-576","NNV-860","CCX-449","LLP-196","EEM-323","RRJ-355","CCA-869",
            "ILM-446","SLN-875","PPX-544","PPA-279","MPR-492","LLD-213","TIT-859","WWO-500","TLT-786","KLL-531","RRX-821","BBZ-666",
            "LBE-346","TRF-111","FHN-485","TTW-429","BCE-261","RJP-339","IIJ-684","LOR-111","IPZ-635","WSH-645","TBL-286","PPN-287",
            "BEB-985","BBA-611","BBK-549","PPO-676","CQY-446","IIT-200","SOR-682","EPJ-619","CPU-930","LOU-740","TTB-505","PPK-563",
            "NEY-494","NEP-613","PPX-152","BBV-749","BEB-102","CJQ-734","WWY-629","SSZ-225","SVE-184","RAN-749","IRF-909","SSL-709",
            "TRP-334","WDK-958","SSB-772","EOH-351","RRD-521","BBD-592","TSI-774","BHO-254","RBR-164","OBG-215","NNS-179","IIZ-366",
            "BCR-770","BHD-595","BBF-520","LCG-983","LLE-755","SSU-834","BCD-364","RRB-394","BEY-544","TPB-673","RRS-350","LLE-359",
            "PPO-718","CQK-818","CVP-980","CCG-868","ISV-922","PPH-873","SLV-176","ILO-888","PPW-534","LLR-912","DPP-445","NNA-431",
            "PPR-118","IIX-899","BBP-926","WWX-750","NHO-173","PFP-313","PGS-821","SSK-914","WLS-983","LSR-420","PPS-798","SSP-530",
            "WWV-999","LLO-579","SOR-797","ECD-375","BBW-833","PPW-881","WVD-724","WWA-935","IFC-195","BIZ-118","LLY-398","BBJ-560",
            "BHG-148","RRJ-341","RRO-737","LDM-341","RLP-456","SSR-913","LCP-498","CCQ-675","SGS-298","SLG-884","BBS-171","LLS-510",
            "IIT-187","NDP-172","DLG-179","TBK-727","CCA-934","LLG-530","CLP-606","BBR-493","DBR-713","NCT-534","WSP-274","TTN-768",
            "LTY-800","LLH-585","IIY-150","TTP-786","SSQ-266","BBJ-784","LZB-940","TOU-942","ECV-138","ELZ-381","SSF-426","PPL-514",
            "TBH-293","BBV-688","PPU-378","BHV-832","BJR-615","KKM-791","PPI-967","TQO-862","PHM-482","BBO-373","LLR-240","LLE-868",
            "TFW-534","SSR-677","SOR-111","CHY-979","QQE-851","TTF-382","IKV-102","WWV-760","RNA-957","LHG-241","BBE-872","WWC-765",
            "WRM-286","LLG-757","VVT-178","SJS-441","LWL-384","CCS-258","WHV-378","BSO-148","TCC-808","BEY-367","WHI-872","PPI-373",
            "RRN-639","BBM-906","BBT-260","LHO-176","LLL-337","LTL-489","NSC-846","RRX-486","WDR-762","PLD-400","IPX-482","COG-498",
            "PPC-474","RRL-696","BBQ-575","ILL-510","RRD-649","ELJ-303","DLM-497","WRH-211","ICY-386","LCY-553","TLI-970","QQA-945",
            "PPR-663","PCV-613","MLD-711","LVN-179","PLZ-122","BSP-581","CWQ-516","PTV-309","BBW-841","ILL-526","CLV-601","WWD-201",
            "BCR-704","BCO-286","NNZ-523","TLF-609","NJV-802","SHZ-541","IIE-887","RRL-189","BRE-768","VBJ-438","MRI-883","QRF-248",
            "SSS-550","COR-581","SSP-290","BLG-820","BPY-122","QCY-274","MLC-155","WWA-318","BBO-144","ILN-894","EEU-271","BHT-970",
            "CCR-424","WWX-480","IWA-505","WRU-499","OMB-739","PTW-157","ETL-210","WWX-718","RJP-878","LIE-826","SSP-585","PAG-980",
            "IIM-628","LRV-649","PPY-602","SSK-578","BWT-796","WWE-951","OBE-766","SEE-389","PJY-170","PPA-450","SQR-900","WWM-133",
            "VVO-997","WAE-668","CCC-102","PPL-903","ERH-842","EBA-888","LLN-447","RJD-882","BJL-833","LLF-887","KOI-372","IIT-223",
            "LHP-513","KHS-356","TTK-613","OPW-317","PLM-241","TFK-965","IPO-804","PTX-872","SHM-618","MLB-513","MBW-731","LHN-721",
            "BRS-314","SSE-793","CLI-373","KNM-589","BHH-438","IMW-153","EEE-972","PPF-135","MRC-721","ILX-130","LLN-511","BSS-218",
            "RRU-208","CCZ-286","SLT-301","MMY-974","LOM-546","LLX-338","IIA-938","CTF-278","BCJ-683","OIY-659","LLF-813","DDT-166",
            "FON-316","SSN-753","WLM-730","WGK-693","LLH-219","IEN-514","KKH-119","TTH-258","PPC-453","WDC-861","RRJ-342","TKY-455",
            "NNM-605","BBQ-861","PLI-441","EMR-996","DCG-821","POQ-404","PTV-866","SSM-382","RRA-842","SLI-692","LLO-649","NJB-643",
            "PPZ-238","AAH-147","PBT-100","IRX-492","SSI-546","WJF-394","VRU-846","TTN-235","SSJ-557","SBS-649","BBE-366","PPV-754",
            "TBP-880","CTW-819","VVZ-767","PPQ-974","RRR-974","LLU-927","AOB-799","RRD-526","LLY-915","CHM-171","CCW-287","FFX-745",
            "KCL-519","PCS-622","ICD-156","BLZ-208","KDY-222","NNX-261","DPO-700","EEC-358","PTV-846","TLD-217","BBW-892","TTB-780",
            "TLR-255","IIT-857","FFS-676","TLZ-146","LGR-631","COQ-696","IPJ-396","AOP-722","QQP-533","PPV-115","LLF-556","VVB-595",
            "TRW-114","QZL-346","PLA-754","BOV-396","LNK-352","PTZ-375","BDB-340","PPI-576","NNZ-365","WHK-199","PPK-221","RRS-743",
            "BCB-548","LLU-871","LLQ-217","TLK-316","BLX-967","PPR-184","CLA-973","NNS-434","TRR-166","KKD-284","KKN-412","MMY-768",
            "TWK-655","LLH-149","DBD-565","ELI-666","SSS-446","BBM-897","TBL-175","WLE-770","WWQ-909","NNP-386","RRS-175","EEW-209",
            "QHF-204","LGT-212","WWH-698","TLN-462","PPR-380","SSL-251","LTT-148","CLN-925","IIG-366","EEQ-529","IIO-383","IIU-250",
            "BDY-631","LLG-145","CTV-744","BHR-449","RRR-301","LLP-938","TOQ-246","TRZ-759","EEY-427","WWI-669","LLS-928","SSS-180",
            "PIM-845","WWO-766","NNU-294","KEC-397","PPI-207","VVM-631","TEJ-341","LLS-273","IIG-229","NNP-401","SSR-722","RRD-388",
            "PTB-182","SCD-960","MMJ-290","SCN-524","NNF-199","RHO-957","NVR-447","TSO-330","LLQ-574","IIM-114","NNM-640","SSE-486",
            "LRU-880","PPU-166","BHE-863","PTY-411","IIW-922","BBK-150","TBE-427","BDO-424","TTD-603","SSW-454","RRV-429","HHE-635",
            "TWS-647","NLK-375","CCE-685","LOT-569","PPB-422","LLR-572","SBU-360","TLE-977","CCU-325","PRU-757","PPB-818","GGC-746",
            "WCP-189","LER-528","BBQ-997","RCR-115","BHI-982","WCD-850","TTJ-394","PPI-612","WWQ-335","ISV-812","CVX-831","BBC-982",
            "RIB-786","FJU-444","SSP-760","CVW-100","LPY-533","PTR-828","PPE-628","BBY-775","CUS-472","PPD-202","LLO-971","NNP-409",
            "LJG-495","BDS-945","BKC-522","PPH-979","ESN-948","FFI-763","QSQ-467","PTH-483","LOZ-802","SSR-902","WWX-725","CVJ-216",
            "VBJ-141","BBJ-952","POJ-511","WIB-742","DBK-488","LLK-512","EPB-440","MEU-543","WWT-385","CCO-330","BBX-656","BHX-996",
            "EEO-788","ECF-905","RRG-865","LSD-538","VVF-423","CQO-388","RRD-517","LLT-731","CCR-629","BBK-933","LLV-910","LOC-438",
            "TSO-731","WWZ-286","BBA-660","CCF-801","MMF-737","TRD-161","SSR-319","TBK-281","EEG-664","IND-813","LLZ-110","TRR-524",
            "PPC-409","PTM-943","TLV-986","NEM-942","HWH-730","BBB-630","TSZ-626","TRV-414","WRS-924","TPA-432","BBL-731","PTH-663",
            "KNA-486","BRM-616","WWH-288","PTM-980","WWC-256","SST-881","SNU-394","FFV-429","PTK-378","LLR-275","R'F-288","LLH-205",
            "TCZ-430","FFE-852","CVR-560","QSI-639","KKU-110","PPA-472","ELX-426","PTD-366","GGA-952","NAC-924","LHD-872","PTK-513",
            "LLO-120","NKE-195","LLW-989","PPK-717","POG-609","LLR-220","TBR-442","BBG-523","LHQ-409","SCO-153","BEQ-768","BHV-536",
            "NRO-492","WWV-956","KKL-107","IIC-290","LLH-471","BHM-734","TTT-465","TTZ-891","BPB-157","LVW-203","NNQ-465","WWW-922",
            "BCO-269","SSJ-522","BOF-265","FFS-283","BBI-589","C1K-717","TLG-626","RRI-946","BSF-655","AAG-897","TRV-748","SSP-916",
            "LLW-721","WWA-476","MMM-930","TEY-162","BBF-635","NEW-720","KHV-762","IHI-503","BHN-494","IIT-828","LZU-636","CCO-560",
            "LND-200","SSV-526","TSP-137","LLJ-380","EEA-720","LOY-239","TTE-111","KKZ-979","MMI-780","CCG-604","BHX-407","ILH-211",
            "SRK-320","WWD-919","NNF-216","WEC-991","DDG-663","PTY-922","WWX-551","BHZ-134","TNQ-937","NKW-427","PPJ-437","VVD-182",
            "KCZ-494","OPT-905","PPD-358","NNO-745","DPL-175","RBB-569","IOH-299","BBM-502","TBT-164","WRP-429","RIQ-133","BBJ-545",
            "PJC-158","SJE-124","PPN-507","PPX-280","TBN-844","SEM-349","EHH-850","BLM-139","DEH-881","DDM-623","SSW-494","TLI-646",
            "IJT-167","BBP-157","SLX-426","LLA-864","IIZ-195","KPW-793","SSB-985","KKN-123","KKJ-794","TBH-614","LLM-475","LLU-389",
            "BOY-862","TRP-100","BBA-670","ERN-365","LLM-822","LLN-184","GGJ-172","SSC-130","PPI-992","WWX-730","PTV-761","R'D-408",
            "SHF-631","PLJ-886","BRH-399","BHV-608","IID-387","SHD-740","VVW-742","ELS-770","SSV-932","RRU-721","WLX-831","PLD-942",
            "BBK-838","SCK-826","BWQ-886","PTF-783","NOM-796","WHV-129","IIB-904","LQY-602","SSK-424","IIE-995","LLQ-637","TRZ-972",
            "TSN-548","BBU-753","FFE-374","RAC-422","TLU-146","BBG-465","WWK-950","DLV-238","MMU-326","MRG-528","SHH-129","LLS-859",
            "TBY-914","KCO-409","LJN-521","BHT-527","SSZ-486","ELL-927","CCL-279","TRO-358","VVB-467","EPT-239","PPM-821","BBI-263",
            "WJV-170","ROI-551","PPC-201","WHE-677","CCE-363","LPS-665","IOJ-216","RLQ-714","PPF-355","IIA-844","ILF-787","PPG-356",
            "EJU-673","TBM-453","BOB-542","NNG-117","TBE-252","NDM-659","COI-512","BHP-925","IIP-873","GGK-130","BIS-716","BBZ-415",
            "BBZ-839","LLP-787","LLW-455","ABZ-404","PTO-607","PMS-775","NEC-603","LVA-179","TJG-500","WWD-803","AKM-935","TSN-158",
            "TBH-563","PPC-350","TPL-704","TBM-273","BBF-493","SCH-196","SLQ-620","ILD-947","RRL-847","ELZ-244","OLL-749","IJR-665",
            "TLD-574","QRJ-860","SHX-952","TCK-716","CCZ-886","BBL-806","BRZ-131","TQB-463","PPR-706","KBN-240","MDC-932","ISE-146",
            "BDO-940","IWO-721","PPK-398","WJD-751","LLR-367","LTR-738","ROB-528","MRR-413","LLP-250","BJV-491","SLO-270","WWD-123",
            "TBL-421","TLM-998","BEP-881","NNT-898","EEQ-476","PPR-770","ISO-231","VBR-918","PTN-723","IOQ-358","EVX-566","JLA-948",
            "WWV-636","BKF-785","NHE-768","LLI-817","IIV-141","BHB-939","LHU-255","WPT-628","NNM-902","HRR-735","WRX-967","EDU-325",
            "TBY-696","TSM-358","RRW-363","ILB-195","BHA-795","RLM-793","WBO-542","SNF-594","WWI-139","LLY-154","MLJ-523","WWK-570",
            "TKC-670","EPS-812","IPO-699","WWH-185","SSK-475","NNH-262","WPJ-532","KKO-959","TBH-276","CCC-675","TBZ-898","BLS-358",
            "SEH-442","GRM-323","WBY-268","DDG-340","LLN-765","SCB-873","BNE-342","TRX-632","IIW-827","VVD-127","CCJ-538","PPJ-628",
            "WWU-865","FPN-357","EBI-263","BPS-964","OBK-348","LLM-989","ILA-802","PTS-703","SSC-780","VBE-252","PPA-351","LLM-643",
            "QCX-501","SSF-192","TLN-135","TON-707","SSA-655","CVO-346","TRY-302","IWP-132","BCR-946","GGZ-917","ERE-594","RRZ-250",
            "SLU-346","TTS-453","KOL-348","NNO-568","EEC-258","LLQ-873","SSQ-353","AAZ-676","PPP-895","ERG-629","QWE-696","ITT-413",
            "TRM-190","MLC-754","ABG-402","SLM-197","IIB-144","BBP-264","LLA-499","CDE-562","NVS-584","CCZ-638","TRO-579","EOW-346",
            "DPP-603","BJE-694","POH-957","PPN-621","BEC-652","TRV-519","QCG-839","NNN-782","CCO-303","IIK-207","PCC-895","AAA-784",
            "BHU-214","PPL-383","BBJ-237","WWX-161","PPV-208","PPL-571","SSB-553","PPT-272","TLL-123","CCE-925","SST-452","PPT-336",
            "LTN-375","BRJ-834","LGZ-358","IPC-764","TTE-366","LLW-649","NNE-965","TBP-288","WHU-764","EBX-235","ROQ-142","SOR-244",
            "OBH-791","RRU-410","TCG-178","SLH-718","WWC-842","LLW-272","TLP-242","SSQ-465","LLL-954","NKF-675","BVT-770","BON-432",
            "WMM-195","SOF-705","ERQ-715","ICC-117","PPO-450","WWL-759","CTR-655","PCV-885","SSD-705","KCG-129","WWP-514","SSF-230",
            "BTQ-875","CCQ-778","BBR-231","ELF-703","CTQ-790","CCK-848","TSP-588","EPC-639","BAC-649","RRZ-938","NNI-990","NNT-377",
            "LDG-722","CCD-239","PTE-245","BHI-700","ISZ-939","TBC-736","PLH-340","PPM-308","IOW-356","BPT-392","RFA-316","PTM-373",
            "TQJ-815","WWA-820","BJW-602","MBR-815","CVY-492","NJJ-120","NAT-731","BBF-400","TTH-511","PPX-157","BPE-127","PPM-626",
            "NNM-295","BBV-188","KHW-623","RLC-668","PPM-716","IIT-533","BBG-378","IIY-987","BBS-286","LJU-974","RRR-982","WWJ-766",
            "ROV-356","WWR-568","SJF-796","LNC-417","SST-747","BBK-812","SLS-741","PPB-924","PPT-731","BCY-149","BII-736","AAQ-714",
            "OBW-156","EPX-259","PJW-909","BOT-466","WWI-890","WPH-293","CCH-292","BBP-438","FHJ-377","PHB-378","SSO-665","HHL-412",
            "BDW-388","PTW-817","TLX-744","IWI-586","BSE-953","COG-420","RAB-259","WWQ-352","NUG-848","PPT-552","CCZ-813","IEO-756",
            "SNO-431","IID-635","WJA-259","BHA-284","LLP-364","LLT-925","LBD-741","SEO-471","PPP-937","SJJ-131","LLT-922","SSR-147",
            "SUS-118","ERO-855","WWZ-346","FPU-929","PPQ-122","SSO-411","MSW-929","CCN-792","CCU-708","CCT-798","CAV-186","RRO-593",
            "CQI-949","CCT-307","LLM-868","BBT-849","LLO-733","PBG-795","LLL-432","MRW-625","SCD-583","BBX-819","IOH-258","KOR-915",
            "RIE-524","MRA-102","AAW-721","WSC-596","BLB-193","TLP-992","BSJ-298","PPW-195","VVV-356","VJZ-483","CCR-767","RSE-259",
            "WWK-942","TRR-255","LLE-321","HHT-831","FFA-637","TTE-995","WLE-612","DLO-779","RLQ-582","WWH-718","BBY-926","PIT-148"
    };
    private static final String[] libraryNames = {
            "Book Haven","Wordsmith Library","Nexus Of Knowledge Library","PageTurner Palace","Blue Sky Books","Enchanted Pages","Page Turner's Hideaway","ProseParade Partners","Serenity Books Library","Serene Stories","Pages Perks","Book Haven Solutions",
            "Knowledge Junction","Bookish Hideaway","Bookworm's Hideaway","Mindful Manuscripts","Open Mind Library","Mindful Reads Library","Chapters Chill Library","LibraryLogic Services","Wisdom Page Library","Bookscape Retreat","Literary Leaf Library","Chapter One Resources",
            "Page Turners","Story Vault","Word Wonder Library","WordWeaver Warehouse","Quantum Quill Library","Ink Imagination Library","Story Loft","InfoVerse Advisors","Page Turner Repository","Storybook Corner Library","Novel Nook Oasis","The Reading Nook Company",
            "Future Books","Book Buffet","Page Perfection Library","Idea Incubator Library","Pages Of Prosperity","Imagination Junction","Explore Escape Library","Digital Dewey Decimals","Haven Of Knowledge","Bookworm's Delight Library","Reading Retreat Center","Literary Luminary Ventures",
            "Literary Oasis","Bookish Oasis","Story Seeker's Sanctuary","Insightful Ink","Read City Library","Novel Discovery Library","Word Wanderer's Retreat","Literary Luminary Solutions","Storyline Hub","Open Bookshelf Library","Library Lounge Loft","Storyline Solutions",
            "Word Nook","Library Of Imagination","Creative Minds Library","ChapterVerse Collective","Bookworm Oasis","Wisdom Woods Library","Dreamer's Den","ScanQuest Consulting","Literary Escape Room","Adventure Bound Library","Enlightened Emporium","The Bookshelf Collective",
            "Storyland","WordCraft Library","The Bookshelf Collective","Idea Illuminaire","Book Castle Library","Dreamy Chapters Library","Novel Nook Corner","Cover2Cover Resources","Novel Nook Collective","Inkwell Library Co.","Page Perfect Pavilion","Pages And Prose Enterprises",
            "Novel Hub","Knowledge House","Beyond The Page Library","Page Turners Library","Book Buffs Library","Book Buff's Library","Story Spectrum","QuietCorner Business Support","Chapter Verse Vault","Word Wander Library","Literary Lens","Imaginarium Libraries",
            "The Bookshelf","Open Book Society","Wisdom Words Library","Bookworm's Refuge","Dreamworld Library","Boundless Books Hub","Bookworm's Bazaar","Beyond The Binding Consulting","Peak Page Library","The Quill Scroll Library","Storyteller Sanctum","Literati Locale",
            "Creative Chronicles","Reader's Hideaway","The Knowledge Corner","Word Smith Library","Beyond The Bookshelf","Pages Of Possibility","Plot Twist Plaza","Librarian's Pride Solutions","Boundless Books Cove","Aisle Of Knowledge Library","Evergreen Pages","Bookworm Haven Co.",
            "Chapter House","Librarian's Library","Page Turn Studios","Knowledge Keepers Library","The Book Oasis","The Bookish Beacon","Luminary Library Lane","ReadWrite Consulting Firm","Reading Rainbow Lounge","The Bookcase Collective","Verses Vault","Ink And Insights Inc.",
            "Idea Imprints","The Literary Junction","Storybound Library","Book Lovers Retreat","Word Haven Library","Literary Alcove","Read Relax Oasis","Literary Liaison Services","The Book Barter Box","Book Bliss Library","Literature Lighthouse","The Library Lab",
            "Literary Lounge","Fiction Frenzy","Bookwyrm Collective","The Academy Of Pages","Narrative Nexus","Boundless Biblioteca","Storyteller Haven","PageMaster Partners","Echoes Of Pages","The Literary Loft","Quill Quest","Novel Notions Solutions",
            "Novel Approach","Prose Palace","Readwell Repository","Story Seekers Society","The Lit Lounge","Scripted Serenity Library","Bookworm Bliss Retreat","Bibliophile Business Solutions","Bookish Bliss Hub","Paper Trail Library","Aura Of Authors","Read Right Resources",
            "Storyteller's Den","The Novel Spot","Dreamscape Library","Whispering Words Library","Literary Nexus Solutions","Story Arc Library","Enlightened Reading Nook","Book Nook Library","The Bookshelf Sanctuary","Storyteller's Haven Library","Storyteller Central","Tome Trove Co.",
            "The Reading Room","Word Warehouse","Bibliophile Hub","Book Haven Collective","Storybook Central Co.","MindPalace Library","Wisdom Words Repository","Bibliophile's Dream Library","Word Whirlwind Exchange","The Knowledge Kiosk Library","Book Bridge","Wordplay Works",
            "Bookworm's Paradise","The Bookworm's Den","Inkwell Emporium","Literature Hub","Knowledge Korners Inc.","Bibliophile Bay","Dreamland Library Hub","Storybook Emporium Library","The Storyteller's Den","Book Bridge Library","Insight Inc.","Enchanted Edits Enterprises",
            "Imaginarium","Fiction Fort","The Reading Room Co.","Word Sanctuary","Reading Retreat Enterprises","Prose Poetry Library","Silent Sanctuary Books","The Bookshelf Library","Trusty Tome Treasury","Reading Rainbow Library","Text Tale","Whimsical Words Workshop",
            "Literary Co.","Page Turner's Haven","Volume Vault","Wisdom Vault","Shelf Space Creations","Infinite Insight Library","Whimsical Words Wonderland","The Reading Corner Library","Whimsical Words Warehouse","Endless Chapters Library","Folio Fusion","Cover To Cover Solutions",
            "Boundless Books","Literature Lair","Storyteller's Sanctuary","Readers Paradise","Novel Ideas Corporation","PixelPage Library","Knowledge Kingdom Collection","Chronicles Library","Riveting Reads Retreat","The Book Baron Library","ReadNook Retreat","Verbatim Ventures",
            "Fiction Forge","The Literary Emporium","Verse Haven","Knowledge Kabin","Literary Oasis Solutions","Script Sanctuary","Tranquil Tales Treasury","BookBridge Library","Boundless Bookscape","Cover To Cover Corner","Novel Nest Station","Arcane Archives",
            "Literary Escape","Quiet Quest","Literary Lantern","Beyond Books Library","Bibliophile Blvd.","Chronicle Corner","Bibliophile's Banquet","RiverReads Library","Bookworm Boutique","Librarian's Choice","Quill Scroll Oasis","The Quill Collective",
            "Word Whisperers","Imagination Station","Papyrus Paradise","Paper Trail Retreat","Cover To Cover Enterprises","QuillQuest Library","Curious Minds Library","BookBloom Library","Paper Pathway","Book Galaxy","Thumbprint Tales","Scribe Space Solutions",
            "Tale Tales","Storybook Hideaway","Storyline Studio","Bookish Bliss Business","Prose Perfection Co.","Echoes Of Knowledge","Creative Cornerstone Collection","WisdomWell Library","Creative Cove","PageTurner Library Co.","Imagination Junction Library","Readleaf Resources",
            "The Book Vault","Literary Cornucopia","Page Flip Prosperity","Enchanted Book Nook","Infinite Pages Corporation","Library Luxe","Bookish Bliss Haven","NovelNest Library","Word Wizard Warehouse","Storyline Library Services","Chapter Cove Library","Tome Treasury",
            "Story Oasis","Shelf Smart","Scripted Serenity","Inkwell Oasis","Word Wonders Ventures","Story Scape","Serene Storyteller Shelter","VisionVault Library","Read Haven","Knowledge Oasis Solutions","Verb Vault Library","Inkling Inn",
            "Novel Nook","Word World","Book Haven Hub","Story Sage Library","Fiction Junction Solutions","Ultimate Bookshelf","Story Sense","LiteraryLoom Library","Tale Oasis","Open Book Resources","Omnilore Library","Storybook Square",
            "Literary Corner","Paper Paradise","Page Turner Place","Chapters Chai Library","Paper Trail Innovations","Tome Time","Literature Lane","KnowledgeKey Library","Echo Library","Chapterscape Library","Text Trove Library","Bibliophile Bonanza",
            "Read And Relax","Page Turner","Bookworm's Retreat","Storyteller's Sanctuary Library","Bookworm Haven Co.","Paperback Perfection","Chapter Cove","IdeaForge Library","Prose Haven","Novel Nexus Network","Story Spark","Text Retreat",
            "Word Voyage","Verse Ventures","Creative Corner Library","Curiosity Cove Library","Story Sanctuary Solutions","Cover To Cover Co.","Text Treasury","ChapterCheck Library","Papyrus Palace","Boundless Books More","Smart Reader Hub","Wisdom Woods",
            "Bookworm's Den","Imaginary Ink","Ink And Imagination","Reading Retreat Library","Page Perfection Enterprises","Fiction Haven","Ink Oasis","LiteraryLuxe Library","Cover To Cover Oasis","Infinite Imagination Libraries","Culture Cache","Page Turner Tavern",
            "Chapter Verse","Storyline Station","Wordsmith's Library","Quiet Quill Library","Reading Rainbow Corporation","Bibliophile Paradise","Library Lab","QuestQuill Library","Book Bower","Quest For Knowledge Collective","Dream Page","The Book Nook Library",
            "Library Lounge","Literary Lighthouse","Beloved Books","Bookworm's Den Library","Creative Chronicles Ventures","Reading Respite","Poetic Pavilion","StoryStream Library","Page Parlor","The Book Nook Emporium","The Book Barn","The Literary Lounge Library",
            "Novelty Nook","Whispering Pages","The Bookshelf Boutique","Dream Destination Library","Biblioteca Bliss Co.","Chapter Verse Retreat","Cover Corner","BookHaven Library","Plot Point Plaza","Knowledge Tree Library","Thought Temple","BookNest Solutions",
            "Reading Retreat","Lit Lounge","Reading Rainbow Retreat","Novel Nest Library","Inkwell Innovations Ltd.","Plot Twist Paradise","Epicenter Of Books","ImaginationInk Library","Cover Cove","Enlighten Reads Repository","Chapters Cheers","PageTurn Innovations",
            "Paperbacks Brews","Bookshelf Boutique","Fictional Findings","Mindful Muse Library","Papyrus Paradise Enterprises","Page By Page Retreat","Page Pathway","ProsePlace Library","Idea Oasis","Literary Luna Library","Aisle Of Adventure Library","KnowledgeHive Investments",
            "Bookish Haven","Storytime Sanctuary","Novel Notions","Libro Lounge Library","Dreamer's Library","The Reading Cove","Book Haven Creations","WonderWord Library","Manuscript Mile","Prose Perusal Index","Bibliophile Retreat","Bibliosphere Creations",
            "The Imaginarium","Imaginarium Library","The Thoughtful Tome","Literary Landmark Library","Infinite Imagination","The Bookish Retreat","Literary Oasis Emporium","EchoEndeavor Library","Genre Gallery","Story Quest Library Co.","Book Bliss Bound","ReadWell Ventures",
            "Literature Lounge","Mindful Muse","Literary Loft","Bibliophile Bliss Library","Bookworm Bungalow","Folio Forum","Storybook Vault","DreamDive Library","Insight Isle","Creative Chronicles Center","The Narrative Nook","ShelfGenius Enterprises",
            "The Hidden Shelf","The Literary Lab","PageTurner Libraries","Read-E-Books","Tales Trails","Bibliotheca Boutique","Infinite Chapters Hub","InsightInk Library","Book Haven Incorporated","Curated Collections Library","Imagination Island Library","LibraSource Solutions",
            "The Book Bar","Bibliophile's Bliss","Wisdom Writ Library","Chapters Coffee","Storybook Haven","Prose Perch Library","Bibliophile Bloom","NovelNote Library","Shelf Space Solutions","Quest For Knowledge Library","Symphonic Stories","LiteraLink Holdings",
            "Magazines More","Book Lovers Hideaway","Story Spark Libraries","Storyteller's Cove","Reading Reverie","The Literary Garden","Literary Zen Lounge","WisdomWatch Library","Storybook Central Ltd.","Infinite Horizons Library","Clarity Corner Library","EchoLibrary Innovations",
            "The Book Nook","The Novel Nest","Insightful Reads Library","The Literary Nook","Knowledge Palace","Poet's Corner Library","Word Magic Haven","PageTurner Solutions","Literary Lounge Creations","Mindful Musings Library","Premier Prose Place","StoryArc Industries",
            "Storyteller's Haven","Book Haven Library","Enlightened Pages Library","Dreamland Books","Page Turners Hub","Literary Discoveries Library","Wordsmith Wonderland","Storybinders Library","Wise Words Workshop","Data Driven Library","The Book Barrel","NovelEdge Ventures",
            "The Novelty Library","Knowledge Oasis","Literary Legacy Library","The Reading Haven","Mindful Memoirs","The Reading Room Library","Leafy Library","OpenBook Resources","Boundless Books LLC","Story Sage","Wisdom Well Books","VerseVision Creations",
            "Word Wonderland","Story Quest Library","Knowledge Kingdom Library","Book Haven Enterprise","Beyond The Cover","Spectrum Stories Library","Fiction Frolic","Novel Haven Services","Cover To Cover Concepts","Book Buff Barn","Prose Perfection Library","InsightfulReads Co.",
            "Storyteller's Corner","Bookworm Retreat","Imagination Station Library","Page Turner Library Solutions","The Learning Loft","Creative Canvas Library","Whispering Pages Emporium","Literary Lounge Hub","Literary Escape Productions","Storytelling Haven","The Book Buff Library","PaperTrail Innovations",
            "Bookworm's Haven","Shelf Savvy Library","Infinite Ideas Library","Novel Nook Consulting","Read Relax Corner","Literary Spectrum Library","Enchanted Bookshelf","CheckOut Chronicles","Prose Poetry Partners","Chapter Chronicle","Novel Retreat Library","PapyrusPeak Solutions",
            "Bibliophile's Paradise","Pages Co Library","Literary Escapade","Storyline Resources Co.","Literary Spectrum","Novel Vision Library","Prose Poetry Pavilion","Beyond Pages Consulting","Narrative Nexus Group","Tale Twist Co.","Dreamy Reads Library","ProseWave Holdings",
            "Reading Refuge","Read Recharge","Wordplay Library","Literary Oasis Services","Wisdom Oasis Library","Visionary Voyage Library","Bookmark Library","Bookshelf Enterprise","Fiction Frontier Enterprises","Retro Read Library","Prime Prose Library","ChapterOne Ventures",
            "Literary Hideaway","Novel Nook Library","Muse Meets Paper Library","Bibliophile Business Partners","Learning Lighthouse Library","Storyteller's Corner Library","Creative Cove Library","ReadStreet Advisors","Library Loft Solutions","Echoes Of Pages Library","The Versatile Volume Library","WisdomWorks Enterprises",
            "The Book Stack","Mindscape Library","Reading Rainforest","Chapter One Innovations","Quest For Quills Library","Chapter One Corner","Expression Library","Bibliophile Biz","Dream Page Ventures","Journal Junction Library","Story Stacks","SereneStack Investments",
            "Prose Paradise","The Bookshelf Expanse","The Bookmark","Reading Realm Ventures","Echoes Of Elegance Library","Word Wonder World","Bindery Library","Bookworm Bureau","Plot Twist Productions","Fiction Foundry Library","Verse Valley","LibraLink Solutions",
            "Bookish Bliss","Chapter Corner Library","Read And Relax Library","Fiction Forge Enterprises","Enchanted Chapters Library","Literary Escape Lounge","Story Garden Library","Prose Palace Partners","Literary Lantern Co.","Bookworm Bliss Library","Scripted Haven","Readwise Enterprises",
            "Novel Oasis","Enchanted Bibliophile","Timeless Tales Library","Bookworm Workshop","Solace In Stories Library","Bibliophile Bliss","Chapters Co. Library","Cover To Cover Consultancy","Story Sanctuary Ltd.","Heritage Library Club","Chapter Retreat","CuriousCrate Co.",
            "The Reading Nook","Novel Ideas Library","Storybook Corner","Literary Escape Strategies","Verse Venture Library","Reading Room Haven","Read Well Library","Literary Lair Labs","Book Buffet Creations","Knowledge Nexus","Versatile Volumes","BoundlessBooks Ventures",
            "Wordsmith's Haven","Bookish Paradise","Page Turner Hub","Novel Knowledge Ventures","Serenity Shelf Library","Shelf Discovery Den","Bookshelf Bliss Library","Midnight Manuscripts","Inkwell Innovations","The Reading Retreat Library","Genre Oasis","KnowledgeKraft Holdings",
            "Literature Haven","The Bookworm's Hideaway","Bookworm Junction","Prose Paradise Solutions","Enlightened Minds Library","Book Buff Bistro","Storyteller Sanctuary Library","Wise Words Workspace","Storyline Haven","The Bibliotheca","StoryTroves","Enchanted Library",
            "Storyteller's Paradise","The Silent Page","Tome Haven","Reading Reservoir Co.","Literary Sanctuary Library","Text Tales Terrace","Mindful Reading Library","Chapters Consult","Page-Turner Paradise","Wonder Vault Library","Learning Loom","Knowledge Oasis Library",
            "Book Lovers' Lair","Chapter And Verse","Narrative Nest","Storyteller Support Systems","The Reading Nook Library","Scripted Symphony","Word Vault","Imagine Ink Co.","Pages Of Wonder","Bookish Haven Library","Folio Focus","Literary Escape Library",
            "Chapter One","Bookshelf Emporium","Plot Point Pavilion","Literary Lantern Consulting","Bookish Retreat Library","Page Perfection Place","Literary Harbor","Literary Legacy Solutions","The Bookshelf Spot","The Literary Ark","Insightful Ideas","Wisdom Repository Library",
            "Word Sages","Page-Turner's Paradise","Bibliophile Bistro","Bookish Bridge Services","Storyteller's Haven Library","Literary Lounge Legacy","Tome Domain","Shelf Space Experts","Bibliophile Base","Page Retreat Library","DreamPage Library","Wordsmith Library",
            "Read Relax","Ink And Paper","Imagine Inn","Page Master Innovations","Chapter Charm","Education Euphoria","Readers' Haven","Boundless Books Business","Fiction Foyer","Bibliophile Oasis","SmartStacks","Mindful Pages Library",
            "Pages Co.","Bibliophile's Emporium","Biblioteca Bliss","Novel Nest Resources","Page Turner Palace","Storybook Station","Library Legacy","Wisdom Vault Library","Wordcraft Corner","Inkwell Retreat","IdeaVault","Serene Scrolls Library",
            "Shelf Space","The Quiet Shelf","Narrative Oasis","Literature Loft Solutions","Storybook Serenity","Book Haven Solutions","Word Wonder Emporium","Infinite Shelf Library","Wisdom Way Library","Echoes Of Imagination","Tale Trail Library","The Quiet Corner Library",
            "Novel Experience","Wordsmith's Retreat","Page Perfection","Book Binder Business Partners","Mythical Library","Storyline Ventures","Story Seekers Studio","Chapter Forge Library","Quill Knowledge Library","Ink Quill Library","Verbose Vault","Bookworm's Paradise Library",
            "Open Book","The Literary Depths","Word Weaver's Den","Chapter Verse Ventures","Ink And Page","Page Turner Enterprises","Bookish Boutique","Knowledge Key Library","Serene Story Library","The Book Bower","Idea Inkwell","Infinite Chapters Library",
            "Enlightened Pages","Storybook Sanctum","Novel Haven Library","Reading Rainbow Enterprise","The Bookshelf Hub","Knowledge Corner Consulting","Fiction Fusion","Page Palate Library","Book Oasis Library","Imagination Emporium","Bibliophile Boutique","Novel Path Library",
            "Knowledge Kingdom","The Bookish Bouquet","Infinite Knowledge Hub","Bookshelf Blueprint Co.","Study Scape","Literary Haven Co.","Chapter Chronicles","Odyssey Library","Wisdom Tree Library","Novel Universe Library","Verse Village","Imagination Junction Library",
            "Word Haven","Story Stack","Chronicles Corner","Tale Trail Consulting","Book Bound","Bibliophile Lair","Book Haven Library","Verso Vault Library","Enlightened Reader Library","Storyteller's Sanctum","Paperback Pavilion","The Literary Hideaway Library",
            "Bookworm Bliss","Word Wizard","Enchanting Escapades Library","Pages Prose Library","Intrepid Reads","Chapter One Solutions","Ink Pages Library","Verbatim Library","Literary Odyssey Library","Story Seeker's Domain","Poetry Plaza","Bookshelf Sanctuary Library",
            "Wise Words","Reading Realm","Literary Lighthouse Library","Print Paradise","Fiction Fortress","Literary Escape Ventures","Wisdom Words Library","Epic Chronicle Library","Novel Insights Library","Read It Reap","Page Turner's Palace","Eloquent Pages Library",
            "Bookish Boulevard","Ink And Pages","Imagineer's Library","Muse Library","Novel Nomad","Novel Ideas Agency","Chapter Verse Library","Bookworm's Delight Library","Literary Emporium Library","Wordsmith's Corner","Ink Insight","The Reading Retreat Library",
            "The Reading Corner","Books And Beyond","Museful Moments Library","Turn The Page Library","Bookshelf Bistro","Word Haven Co.","Literary Oasis Library","Memoir Muse Library","Open Book Society Library","Book Buff's Emporium","Blue Spine Library","Gutenberg's Garden Library",
            "Library Lane","Inkwell Library","Whispering Pages Library","Chapters Library Collective","Climbing Bookshelves","Fictional Realms Consulting","Storyteller's Corner Library","Libra Lex Library","The Bookworm's Den Library","Bookworm's Oasis","Beloved Books Library","Enlightened Library",
            "Novel Ideas","Book Nook","Bibliophile Junction","Open Book Exchange","Imagination Inn","Literary Oasis Group","Creative Minds Library","Enigma Library","The Page Turner Library","Read Me Library","Reading Rainbow Co.","Enlighten Emporium",
            "Page Turner Library","Wordarium","Bookish Bliss Library","Quill Scroll Library","Bibliophile Corner","Reading Nook Solutions","Paper Trails Library","Chapter Charms","Novelty Nook Library","The Literary Exchange","Writer's Block Boutique","Wordsmith's Workshop",
            "Chapter Verse Library","Storyteller's Library","Dreamweaver's Library","Verse Vault Library","Verse Venture","Storybook Strategy Partners","Imagine Ink Library","Book Buff's Retreat","Storyteller's Den Library","Literal Oasis","Chapter Verse Collective","Progress Page Place",
            "Storyteller's Retreat","Queens Of Ink","Bibliotheca Bliss","Novelty Library Hub","Literature Loft","Bookish Haven Ventures","Word Wizard Library","Inspiration Library","Imagination Gateway Library","Bookscape Library Co.","Storyland Station","Verse Oasis",
            "Word Wizard Library","Novel Spot","Read Relax Co.","Knowledge Quest Library","Reading Oasis Library","Think Ink Consulting","Page Turner Library","Word Wonder","Arcane Archives Library","Chronicle Hub","Page Perfection Emporium","Infinite Ideas Inc.",
            "The Reading Spot","The Bookworm's Cove","Storyline Junction","Bibliophile's Haven Library","Wise Words Library","Literary Luminary Co.","Knowledge Kingdom Library","Bibliophile Bridge","Papyrus Pavilion Library","Prose Paradigm","The Book Maven","The Revelry Repository",
            "Literary Hideout","Word Wizard's Hideout","Page Turner Club","Word Nook Library","Mindful Margins Library","Novel Destination","Dreamscape Library","Storyteller Sanctuary","The Book Buffet Library","Enlighten Books","Author's Alley","Boundless Words Library",
            "Book Lovers' Haven","Bookish Headquarters","Literary Nook","Literary Journey Library","The Quiet Quill Library","Bibliophile Emporium","Enchanted Pages Library","Tale Teller's Library","Knowledge Tower Library","Muse Library Co.","The Library Lounge","Storybook Corner Library",
            "Storyland Library","Literary Sanctum","Creative Corner Books","Prose Paradise Library","Bookworm's Bliss Library","Literary Landscape Solutions","The Reading Nook Library","Fictional Oasis","Novel Sanctuary","Beyond Pages","Quill Scroll Co.","Wonder Shelf Library",
            "Pages Prose","The Novel Depot","Wisdom Library Collective","Ideas Ink Library","Literary Lantern Library","Pages Poetry Partners","Tome Time Library","Storybook Sanctuary Library","Imagination Hub Library","Intellect Library","Book Buff's Bazaar","Dreamy Bookcase Library",
            "Wordsmith's Sanctuary","The Reading Experience","Novel Discovery","Story Sanctuary Library","Thoughtful Tomes Library","Bookish Bliss Consulting","Verse Vault Library","Prose Pages Library","Literary Voyage","Echoing Epics","The Bookish Hideaway","Fiction Find Library",
            "The Book Cave","Bookish Odyssey","Pages Brews","Bookworm's Retreat Library","Book Bridge Library","Page Turner Pavilion","Bookworm's Hideaway Library","Bibliophile's Hideaway Library","The Bookshelf Oasis","Infinite Insights","The Book Bridge","The Library Loft",
            "Bookish Escape","BookWorm Library","Infinite Chapters","Narrative Nest Library","Cozy Corner Library","Chapters Charm","Novel Nest Library","Literary Nook Library","Page Turner Center","Discovery Den","Education Emporium","The Bookmark Library",
            "Bibliophile's Haven","LitLife Library","Wisdom Works Library","ReadWorld","Enlightened Edges Library","Bibliophile's Oasis","Intellectual Refuge Library","Spectrum Readings Library","Storyteller Hub","Enlighten Endeavors","Literary Legacy Lounge","Imaginaread Library",
            "The Literary Hub","PageTurn Library","Mindscape Books","Page Palace","Prose Party Library","Word Weave Warehouse","Literature Haven Library","Quest Quill Library","Pageant Palace","Page Paradise Library","Study Spot Central","Bookscape Hub",
            "The Book Sanctuary","Knowledge Hub Library","Page Wizards","Educate Hub","Word Wonderland Library","Plot Twist Panorama","Whimsical Words Library","Readers Refuge Library","Novelty Nest","Book Boundaries","Page Perusal Plaza","PageQuest Library",
            "Word Oasis","OpenBook Library","Imagine Ink Library","Nova Novels","Serene Scrolls Library","Cover To Cover Collection","Fictional Retreat Library","Lore Lounge Library","Storyscape Studio","Dreamy Library","Insightful Infinity","WordWonder Library",
            "Ink Page","Chapter One Library","Novel Ideas Hub","Insight Institute","Insightful Inkwell Library","Fiction Finders Forum","Thoughtful Tomes Library","Library Labyrinth","Word Weaver's Workshop","Fiction Fiesta","Wisdom Workshop","Bookworm Sanctuary",
            "The Literary Lounge","Boundless Books Library","PageTurner Central","Story Sanctum","Story Haven Library","Inkwell Inn","Poetic Haven Library","ReadAhead Books","Bookworm Bazaar","Storyteller's Oasis","Learning Lounge","Fabula Library",
            "Art Of Reading","Literary Haven Library","Literature Lab","Infinite Ideas","Mindful Pages","Memoir Garden","Nova Nexus Library","PageTurner Place","Page Perch","The Book Niche","Novella Nook","Literary Zenith",
            "Write Read","Storyline Library","Storyteller Station","Enlighten Exchange","Brainwave Books","ReadSpire","Storyteller’s Sanctuary","Text Tales","Story Spire","Novella Nectar","Paper Tales","Readopolis Library",
            "Page Turner's Paradise","Read Rendezvous","Chapter One Chronicles","Wisdom Way","Enlightened Library Hub","NovelNest","Beacon Books Library","Readwell Resources","Book Barter","Insight Inn","Story Spires","Odyssey Books",
            "Book Bazaar","Novel Idea Library","Read And Relax Retreat","Academic Alcove","Sage Scrolls Library","PageTurn Pro","MindMerge Library","Literary Legacy Ventures","Storyteller's Shelf Library","Bibliophile's Corner","Knowledge Koop","Maven Pages Library",
            "Mystery Imagination","Literary Oasis Library","Imagination Avenue","Wisdom Well","Lifelong Learning Library","ChapterCrafters","Enlightened Editions Library","Bibliophile Bliss Corporation","Dream Voyage Library","Enchanted Bookshelves","Word Wonders","Bookworm Boudoir",
            "Literary Haven","Curiosity Corner Library","Enchanted Encyclopedia","Educate Emporium","Insightful Reads","StorySage","Beyond Books Repository","Novel Nook Innovations","Wisdom Quill Library","Imaginarium Books","Idea Library","Reading Reservoir",
            "Wordsmith Hub","The Quiet Shelf Library","Textbook Treasures","Endless Adventure Library","Thoughtful Tomes","Literary Lane","Epiphany Emporium","Literature Loft Inc.","Enchanting Chapters Library","Literary Nirvana","Book Barrel","Story Street",
            "Book Lovers' Den","Bibliophile's Lair","Classics Corner","Literary Gems Library","Storyteller Library","Inkwell Insight","DreamWeaver Library","Whispering Pages Co.","Enlighten Pages Library","Fictional Frontier","Read Refuge","Inkwell Isle",
            "The Storyteller's Corner","Literary Escape Library","Inkwell Institute","Enlighten Library","Wise Owl Library","ChapterVerse","Resonance Reads Library","Literary Lantern Solutions","Wanderlust Library","Undercover Reads","Epic Eden","Literary Spectrum Solutions",
            "Tales And Tomes","Tome Time Library","Literary Sanctuary","Dreamy Bookshelves","Chapters Verses Library","PageMuse","Novel Notions Library","Chapter Chronicles Corporation","Literary Labyrinth Library","Enlightened Escapades","Resolute Readers Library","Chapter Corner Co.",
            "Imagination Library","Storyville Library","Prose Perch","Poetic Pages Library","Mindful Pages Library","Literary Links","The Infinite Chapter","Word Wizardry Enterprises","The Literary Cove","KnowledgeHub Library","Read Relish Library","Boundless Books Agency",
            "Literary Bliss","The Reading Tree","Fictional Haven","Tucked-In Tales Library","Bibliophile Central","Readorama","Idea Illumination Library","Literary Oasis Ventures","Illuminated Pages Library","Wisdom Stack Library","The Bookworm's Refuge","Page-Turner Partners",
            "Bookworm Emporium","Book Buzz Library","Bookworm's Burrow","Papyrus Palace Library","Creative Quill Library","Inkling's Inn","Spark Of Wisdom Library","Enlightened Pages Co.","Chapters Prose Library","Literature Oasis","Tale Teller's Trove","Prose Palace Professionals",
            "Novel Escape","Novel Escape Library","Page Perusal","Brilliant Books Library","Bookish Escape Library","ChapterCharm","Wordsmith’s Workshop","Story Seekers Solutions","Storybook Vault Library","Read Alcove","Illuminate Reading Room","Storyteller Syndicate",
            "The Reading Retreat","Wisdom Den","Story Soiree","Echoes Of Eternity Library","Radiant Readers Library","Bookish Banquet","The Storyteller's Nook","Bookworm Haven Innovations","Read Between The Lines Library","Open Book Repository","Novel Nook Nexus","Inkwell Innovations Inc.",
            "Book Cove","Bibliophile's Hideaway","Bookshelf Brilliance","Leafy Chapters","Literary Luminary Library","Storyteller's Studio","Bookmark Collective","Read Runway Corporation","Bookworm Emporium Library","Thoughtful Pages Library","Reading Retreat Ridge","Literary Lounge Enterprises",
            "Paperback Paradise","Creative Quill","Chapter Verse Co.","Chapters Chai","Infinite Stories Library","Page Patrol","Spectrum Library","Imagination Library Collective","Paperback Paradise Library","Legacy Library","Dream Pages Domain","Novelty Network",
            "Prose Perfection","Imagine Ink","Byte-Sized Books","Word Wise Library","Novel Haven","Page Flipper's Paradise","Pages Galore Library","Story Seekers","Whispering Leaves Library","LibraTech Solutions","Prose Paradise Plaza","Story Scribe Solutions",
            "Wordsmith Warehouse","Literary Lab","Storyweaver Oasis","Enchanted Chapters","Bookshelf Boulevard","Paperback Perch","Word Vault Library","Word Wanderers","Idea Forge Library","Bookshelf Innovations","Library Lavish","Bookish Buzz Business",
            "Bibliophile's Hideout","Reading Rainbow","Read Relax Retreat","Literary Dreamland","Readwell Library","Story Stash","Literary Cozy","Creative Chapters","Secret Garden Library","Storyline Library Solutions","Bookish Bliss Boulevard","Literary Lighthouse Ventures",
            "Ink Inc.","Novel Discoveries","Dreamers' Library","The Book Emporium","Classic Corner","Lore Lounge","Chronos Library","Book Blend","Dream Bound Library","Novel Concepts Library","Word Symphony Sanctuary","Tome Triumphs",
            "Literary Treasure Trove","Literary Landscape","Infinite Imagination Books","Tales Trails Library","Shelf Scape","Book Buff's Hideaway","Literary Zen","The Open Book Nook","Eclectic Collection Library","Enlighten Library Services","Story Seeker Station","Page Perfectionists",
            "The Book Hub","Bookish Bazaar","Paperback Palace","Book Haven Libraries","Bookmark Junction","Knowledge Korners Library","Page Perfect Library","The Quiet Corner","Pagemaster's Hideaway","Bookworm Business Services","Literature Landmark","Literary Landmark Agency",
            "The Fiction Foundry","Storytime Station","Storyline Oasis","Chapter House Library","Quill Quest Library","Tranquil Tomes Library","Infinite Knowledge Library","Wisdom's Warehouse","Reading Nook","Literary Haven Solutions","Book Buffet Bazaar","Wordplay Wizards",
            "Word Refuge","Library Loft","Verse Vault","Storybook Junction","Literary Wonderland","Cozy Chapters","Wisdom Hub Library","Bibliophile's Sanctuary","Tome Corner","Bibliophile Enterprises","Wisdom Hub","Prologue Partners",
            "Read Retreat","Bookmark Boutique","Boundless Books Boutique","Literary Haven Hub","LibraLit Library","Literary Tranquility","Novel Sanctuary Library","Reading Revolution","Wordsmith's Domain","Prologue Library Solutions","Infinite Pages","Chapter One Creations",
            "Page Paradise","Reader's Retreat","Bookworm Bistro","Inklings Library","Read Rock Library","Enchanted Library","DreamBook Library","Wisdom's Retreat","Inkwell Collective","LibraryLabs Consultancy","Thinkers' Library","Quietude Quarters Library",
            "Paper Palace","Paperbacks Coffee","Mindful Library Studio","Literary Visions","PageTurner Library Solutions","Bookshelf Sanctuary","Creative Words Library","Page Turner Collective","Book Buff's Bolthole","Infiniti Library Services","Curiosity Library","Wisdom Whisper Library",
            "Bookworm's Cove","Bookshelf Corner","Novel Niche","Textscape Library","Novelshelf","Storyteller's Hub","Imagine Infinity Library","Read Relax Lounge","Bibliophilic Retreat","Virtual Bookshelf Solutions","Mindful Readings","Quiet Reflections Library",
            "Story Sanctuary","Chapter One Books","Storybound Sanctuary","Bookstacks Library","Boundless Pages Library","Quiet Corner Library","Mindful Library","Word Whimsy Corner","Book Bonanza","Insightful Library Resources","Enlightenment Embassy","Bookworm's Hideaway Library",
            "Chapter Corner","Word Wizardry","Infinite Wisdom Books","Word Realm Library","Open Minds Library","Paper Trail Library","Epic Tales Library","Word Wizardry Haven","Readify","Literati Innovations","Storyline Spot","Prose And Poetry Library",
            "Imaginary Isles","Library Revival","Pagemaster's Palace","Scroll Sanctuary","Beyond Words Repository","Wisdom Whispers Library","Open Book Oasis Library","Storyteller's Emporium","PageTurners","Pages Pixels Business Services","Story Quest","Word Wonders Library",
            "Verse Voyage","Word Alchemy","Curated Chapters","Page Palace Library","Enlighten Reads","Enchanted Books Library","Learning Legacy Library","ReadNook","BookQuest","Literary Link Consulting","Knowledge Oasis Resources","Inkwell Insights Library",
            "Literature Hideaway","Knowledge Hub","Tranquil Tales Library","Open Pages Library","Paperweight Library","The Folio Foundation","Intrepid Pages Library","Page Turn Alley","Story Haven","Mindscape Library Solutions","Modern Bookshelf Solutions","Literary Harbor Library",
            "Bookish Retreat","Shelf Savvy","ChapterVerse Library","Knowledge Nexus Library","Book Haven Archive","Infinite Minds Library","Enlightened Echo Library","Plot Point Place","Mindful Reads","Imagineer Library Services","Literature Locale Lab","Bookshelf Sanctuary Library",
            "Readers' Refuge","Chapter Chasers","StoryVault Library","Meta Minds Library","Literary Odyssey","Learning Lighthouse","Infinite Intellect Library","Cover To Cover Cafe","Bookshelf Central","OpenBook Innovations","Library Loft Ideas","Dreamer's Delight Library",
            "Fiction Oasis","Storytime Stop","WordWise Library","Wisdom Grove Library","Literary Legacy Haven","Idea Emporium","Knowledge Keepers","Text Trove","Papyrus Pages","Wisdom Depot Solutions","Reading Retreat Resources","The Knowledge Nook Library",
            "Novel Nostra","Bibliophile Boulevard","PageTurner Library","Enlighten Me Library","Dreamy Chapters","Peak Of Pages","Paper Trails Library","Storyline Square","Readwell Retreat","Sunrise Library Services","Literary Lounge Launch","Noveltrove",
            "Page Pursuit","Adventure Awaits","Phoenix Books","Infinite Reading Room","Sage Spines Library","Wisdom Junction","Visionary Reads","Title Tale Tavern","Shelf Success","Storyscape Business Solutions","Bookworm Bliss Co.","Page Portfolio",
            "The Book Haven","Cover To Cover","Verse Vision Library","Paperback Palace Library","Reader's Refuge","Luminary Library","Aisle Of Inspiration","Riddle Reads","Librarian's Lair","Chapter Hub","Creative Commons Corner","Fable Forge",
            "Knowledge Center","Prose Corner","Inkwell Collection","Brainwave Library","Knowledge Depot","Novel Nook Ventures","Dream Pages Library","Explore Editions","Page Turner Plaza","The Literary Globe","Bibliophile Beacon","Tale Tower",
            "The Literary Loft","Inked Imagination","Fiction Foundry","The Literary Sanctuary","Literary Gateway","Chapter One Collaborative","Insightful Pages","Aisle Of Adventure","Quill Quest","Page Prism","Literary Legacy Labs","Verse Vista",
            "The Reading Sanctuary","Quiet Zone","PagePulse Library","Browsing Oasis Library","Literary Nexus","Page Turner Enterprise","Bibliophile's Dream","Page Prodigy Plaza","Novel Nook Network","Wisdom Hive Library","Prose Paradise Co.","Reading Ridge",
            "Bookshelf Co.","Literary Land","Literary Luminary","The Literary Lighthouse","Bookmarked Library","Prose Palace Innovations","Cornerstone Library","Novel Nook Library","The Reading Refuge","Knowledge Krate Library","Knowledge Kingdom Enterprises","Mega Manuscripts",
            "The Word Warehouse","Language Lair","Dreamweaver Books","Explore Learn Library","Sage Shelf Library","Bibliophile Blueprint","The Bookish Haven","WordSmith Library","Wordsmith's World","Narrative Nook Library","Reading Room Resources","Epic Epistles",
            "Quiet Haven","Literary Gem","Wisdom Wells Library","The Learning Loft Library","Page Palooza","Script Shrine Syndicate","Literary Treasures Library","Cornerstone Library","Insightful Impressions","Enlighten Express Library","Insightful Ideas Innovations","Ink Island",
            "Bibliophile's Den","Literary Lair","Cover To Cover Library","Book Haven Enterprises","Reading Respite Library","Literary Lounge Labs","The Open Book","The Reading Room Library","Enlightened Epilogues","Word Whirl Library","Literary Link Lab","Storybook Sphere",
            "Papyrus Ink","Word Wise","Novel Nest","Knowledge Emporium","Plot Point Library","Verse Vault Ventures","The Enchanted Library","Literary Legacy Library","Inkwell Insights","Narrative Nexus Library","Story Sanctuary Strategies","Read Rendezvous",
            "Paper Trails","Story Corner","Muse Meeting Library","Storybind Co.","Novel Nectar","Reading Haven Nexus","Novel Vortex","The Storyteller's Library","Literary Legacy Lane","Imaginarium Inn Library","Novel Nook Enterprise","Shelf Serenity",
            "Literary Retreat","Printed Paradise","Bookworm Haven","Page Turner Ventures","Imagination Island","Bookshelf Brigade","The Bookshelf Emporium","Bookworm's Den Library","Tale Trailblazers","Storyscape Sanctuary","Reading Retreat Co.","Hardcover Hideaway",
            "The Word Vault","Novelty Library","Chapters Chatter","Literati Oasis","Page Portal","Literary Legacy League","Sage Bookstore","The Literary Loft Library","Curated Chronicles","Page Retreat","Prose Paradise Group","Genre Galore",
            "Word Cartel","Literary Escapades","Book Bliss Library","Readwell Collective","Bookbound Haven","Wordcraft Collective","Tome Treasures","Paperback Palace Library","Whispering Words Workshop","Idea Sanctuary","Chapter Verse Corporation","Book Buff's Paradise",
            "Read It Forward","Fiction Junction","Story Seeker's Library","Chapter Verse Enterprises","Leafy Pages Library","Plot Twist Partners","Prose Poetry Place","Bookshelf Bliss Library","Chapters Unlimited Library","Poet's Paradise","Literature Legacy Innovations","Novel Nexus Library",
            "Literary Junction","Bookworm's Delight","Boundless Knowledge Library","Prose Portal Partners","Enchanted Shelf Library","Fiction Forge Syndicate","Quill Scroll Emporium","Plot Twist Library","Library Of Legends","Story Seeker's Spot","Word Wonderland Enterprises","Chapter Verse Collection",
            "Virtual Bookshelf","Book Buffs","Pages Of Wisdom Library","Wordcraft Industries","Dreamland Books Library","Literary Lighthouse Solutions","Epic Page Retreat","Mind's Eye Library","Wisdom Wells","Curiosity Corner","Bibliophile Bridge Solutions","Bookworm Haven",
            "Enlightenment Express","Endless Chapters","Reading Radiance","Literary Sanctuary Solutions","Verse Vortex Library","Chapter Quest Enterprise","Reading Rainbow Emporium","Library Luxe","Chapters Corner","Bibliophile's Bower","Literary Lighthouse Partners","Literary Oasis",
            "The Story Arc","Wisdom Warehouse","Book Buff's Hideout","Cultural Capitals Co.","Muse Manor Library","The Reading Room Hub","Serene Stories Library","The Book Binder Library","Enlightened Exchange","Imagine Nation Library","Literary Luxe Collective","The Reading Room",
            "Prose Parlor","Page Turner Paradise","The Literary Corner","Noveltree Enterprises","Hidden Wisdom Library","Bookish Blessings","The Storytelling Place","The Reading Rainbow Library","Wordsmith’s Retreat","The Page Pilgrim","Bookish Bliss Enterprises","Page Turner Library",
            "Knowledge Nook","Bibliophile's Retreat","Whimsical Words Library","Paper Trail Ventures","Word Whispers Library","Storyteller's Sphere","Storybook Nook","Fuse Fiction Library","Plot Twist Emporium","Lexicon Legacy","Read 'N' Relax Corporation","Literary Lounge",
            "Tales Chronicles","Fiction Fables","Chapter Verse Libraries","Quill Scroll Enterprises","Knowledge Kiosk Library","Page Perfection Collaborative","Envision Library","Page Turner Central","Genre Gem","Novel Approach Library","Literary Haven Ventures","Plot Twist Repository",
            "Literary Labyrinth","Novel Knowledge","Literary Legacy Hub","Papyrus Palace Partners","Pages Of Wonder Library","Library Launchpad","The Bookworm's Hideout","Bibliophile Bazaar","Literary Hub","Scholar's Corner Library","Bookworm Emporium Group","Book Haven Hub",
            "Novel Retreat","Wonder Words","Knowledge Korners","Inkblot Innovations","Lexicon Lounge Library","Book Haven Express","Tale Teller Library","Tale Terrace","Beyond Pages Library","Literary Voyage Library","Novel Nest Solutions","Word Wizard Library",
            "Bookshelf Chronicles","Storyline Sanctuary","Bookshelf Oasis","Folio Foundry","Beyond Boundaries Library","Chapter 1 Library Services","The Literature Lounge","Reading Rendezvous","Boundless Stories","Adventure Awaits Library","The Reading Room Company","Storybook Sanctuary",
            "Literary Landmark","Wisdom Willow","Mindful Measures Library","Textopia Enterprises","Bookworm Boulevard Library","Novel Escape Hub","Knowledge Haven Library","Intellectual Hub","Bookworm's Hideout","Information Infinity","Literary Zen Enterprises","Chapter Chat Library",
            "Literary Nirvana.","Sage's Sanctuary","The Storyteller's Sanctuary","Libris Luxe Co.","Enlighten Express","Literary Oasis Network","Think Tank Library","Knowledge Kiosk","Modern Manuscripts","Curiosity Cove","Bibliophile Hub Corporation","Inkwell Library",
            "Smart Reads","Wordsmith's Wonderland","Novelty Niche","Wordplay Enterprises","Discovery Den Library","Page Turner Junction","Wisdom Wing Library","Bookworm Hideout","The Novel Niche","Novel Knowledge Hub","Page Perfection Partners","Verse Vault Collection",
            "Knowledge Corner","Open Pages","Page Palate","Narrative Nook Ventures","Dreamy Pages Library","Renaissance Bookshelves","Intellectual Oasis Library","Book Buff Bazaar","The Book Boutique","Wisdom Repository","Readvolution Innovations","Bookshelf Bliss",
            "PageTurn","Storylines","Prose Pavilion","Page Palate Partners","The Bookshelf Company","Storyline Emporium","Enlighten Hub Library","Book Lover's Den","Dream Escape Library","Discover Dive Library","Story Spectra Co.","The Literary Loft",
            "Imagineland","Bookshelf Bliss","Storyscape Library","Literary Loft Solutions","Insightful Institute","Knowledge Portal Library","Scholar's Sanctuary Library","Knowledge Keep","Knowledge Kin Library","The Bookmarks Library","Library Lounge Collective","Library Lane",
            "Book Oasis","The Readery","Bibliophile Bay Library","Epic Reads Library","Lively Libraries","Literary Legacy Commons","Genre Garden Library","Story Seeker Sanctuary","Paper Perfection Library","Wise Words Warehouse","Page Turner Library Collective","Read 'N Relax Retreat",
            "Story Hub","Papyrus Library","Bookworm Retreat Library","Bookshelf Haven","Infinite Inspiration Library","Storybook Harbor","Verse Vista Library","Enlighten Library Co.","Silent Sanctuary Library","Reading Realm Resources","Wanderlust Library Hub","Plotline Library",
            "Bookworm Boulevard","Storybook Central","Beyond Words Library","Page Turner Emporium","Novel Oasis Library","Wisdom Hardcover Hub","Infinite Imaginarium","Literary Quarters","Storybook Shack Library","Infinite Imagination Institute","Lexicon Library Lounge","The Reading Nook",
            "The Shelf","Book Boulevard","Fiction Forge Library","Read Aloud Retreat","The Learning Library","Bibliophile Bliss Center","Wisdom Wave Library","Dreambound Library","Muse Mosaic Library","Mindful Reading Hub","Storyteller’s Haven Library","Literature Lair",
            "The Book Stop","Knowledge Chronicle","Literary Junction Library","Bookworm’s Hideaway","Story Seekers Library","Enlightenment Library Hub","Concept Corner Library","The Reading Nook Hub","Virtual Voyage Library","Enlightened Pages Emporium","Papyrus Pages Library","Bookish Bliss",
            "Wordcraft","Reader's Oasis","Prose Palace Library","Wordsmith Haven","Creative Chronicler Library","Literary Passage","Idea Oasis Library","Renaissance Libraries","Plot Point","Infinite Ideas Institute","Inkwell Library Oasis","Page Palooza Library",
            "EnlightenEd","The Book Exchange","Bookshelf Oasis Library","Narrative Nook","The Book Buffet","Novel Discovery Depot","Chapter One Library","Book Haven Exchange","Ink Institute","Genius Gems Library","Boundless Imagination Library","Book Bunker",
            "Book Bliss","Literary Legacy","Literary Lounge Library","Adventure Bound Books","Page Turner Haven","Page Master Library","Novel Escape Library","Literary Vault Co.","Textopolis","Wisdom Words Warehouse","Arcane Knowledge Library","The Storyteller's Stop",
            "The Book Bazaar","Pages Pen","Turning Page Library","The Bookish Den","Brainy Bibliotheca","Story Central Station","Storyteller Library","Imagineers Library","Read Realm","Edulink Library","Odyssey Library Collective","Insight Junction",
            "The Literary Den","Quiet Reads","Storybook Haven Library","The Creative Word","Creative Chronicles Library","Boundless Bookshelf","Bookworm Retreat Library","The Quiet Corner Library","Poetry Perch","Kaleido Books Library","Manifest Destiny Library","Innovation Shelf",
            "Bookish Delight","Imaginary Worlds","Pages Places Library","Wisdom Junction Library","Literati Lounge","Literary Trove Gateway","Reading Oasis Library","Midnight Readers Library","Literary Library","Bookshelf Junction","Storyline Library Retreat","Wisdom Waypoint",
            "The Bookworm's Retreat","The Learning Lounge","Bookend Escape Library","Novel Nexus Library","Enlightened Escapade Library","Prose Paradise Junction","Imagination Station Library","Virtual Bookshelf Library","Page Turner Libraries","Insight Oasis Library","Ethereal Volumes Library","Journeys Library",
            "Wordsmith Wharf","Boundless Knowledge","Novel Horizon Library","Literati Library","Infinite Insights Library","Book Haven Co.","Literary Hideaway Library","Wisdom Pages Library","Novel Nook Libraries","Horizon Reads Library","Written Reverie Library","Enlighten Depot",
            "The Book Lounge","The Storyteller's Haven","Read Relax Library","Imagineer Library","Bookworm Hideaway","Readify Library","Word Boutique Library","Storyteller's Nook","Word Wizard Libraries","Lumina Learning Library","Muse's Library Nook","Wisdom Wharf",
            "The Knowledge Hub","Endless Pages","Infinite Pages Library","Wisdom Wellspring Library","Simply Stories Library","Novel Nook Inc.","Whispering Pages Library","Knowledge Kernel Library","The Book Nook Collective","Clarity Cove Library","The Bookworm's Haven","Brainwaves Library",
            "Storybook Emporium","Geeky Reads","Wisdom Beacon Library","Dreamer's Den Library","Literary Legends","Storyline Central","Book Nook Library","The Reading Oasis","Imagination Inn Library","Vista Verse Library","Creative Corner","Perspective Portal",
            "Words Wisdom","Fine Print","Enchanted Bookshelf Library","Bookworm's Paradise Library","Open Book Library","Literature Lair LLC","Inkwell Library","Page Turner's Library","Story Sanctuary Libraries","Visionary Books Library","Pages Paradise","Logic Library",
            "Quiet Corner","Storybook Sanctuary","The Literary Haven","Thought Oasis Library","Sparking Stories Library","Chapter Verse Ventures","The Reading Room","Infinite Wisdom Repository","Bookworm Central","Genius Grove Library","Enchanted Reads Library","Redwood Reading Room",
            "Shelf Life","Tome Town","Knowledge Oasis Library","Novella Nook Library","Enlightened Escape Library","Librarian's Loft","Story Sanctuary Library","Adventure Alcove Library","Prose Palace Libraries","Evolve Reads Library","Quiet Wisdom Library","Ivory Tower Library",
            "The Reading Den","Midnight Library","Adventure Bound Library","Synthesis Library","Infinite Inspiration","Bookish Bliss Boutique","Literature Lounge Library","Chapter Discover","Novel Voyage Library","Chronicle Corner Library","The Reading Escape","Echoes Of Enlightenment Library",
            "Dream Pages","Booklandia","Pages Of Serenity Library","Poetry Perch Library","Bookshelf Essence","The Reading Room Collective","Quiet Corner Library","Narrative Niche","Creative Corner Libraries","IQ Ink Library","PageTurners Collective","Atlas Archives Library",
            "Bibliophile Haven","Plot Place","Bibliophile's Bliss Library","Wonder Woods Library","Prose Potency","Poetic Pages Hub","Serene Shelf Library","Paper Pages Place","Talesmith Libraries","Curiosity Cabin Library","Storybound Solutions","Phoenix Pages Library",
            "Literary Treasures","Bookshelf Retreat","Literary Gem Library","Insightful Pages Library","Title Treasure","Library Lane Enterprises","Narrative Nest Library","The Bookshelf Brigade","Wordplay Haven","Enlight Books Library","Reading Oasis Enterprises","Sanctuary Of Stories Library",
            "Open Book Oasis","Reading Rainbow Library","The Chronicle Hub","StoryBook Library","Word Whisperer","Literary Legacy Co.","The Literary Haven","Scribble Square","Literary Lounge Libraries","Nexus Knowledge Library","Bookmark Ventures","Beacon Of Books Library",
            "Word Magic","Storybook Oasis","Enlightened Reads Library","Infinite Chapters Library","Plot Point Palace","Wordplay Warehouse","Cover To Cover Library","Poet's Corner","Storybook Symphony","Knowledge Corner Library","Wordsmith Works","Serenity Scrolls Library",
            "Bound To Read","Chapter Chateau","Blissful Books Library","Enlightenment Library","Cover To Cover Collective","Classic Cornerstone","The Storytelling Spot","Enchanted Pages Place","Book Alcove","Reader's Refuge Library","Novelty Nook Enterprises","Nova Novels Library",
            "Literary Delight","Creative Collab Library","Passage To Prose Library","Bibliophile Haven Library","Inkwell Sanctuary","The Bookshelf Society","PageTurner Library Services","Papyrus Pavilion","Imagination Oasis","Bibliophile's Paradise Library","Read Flourish Ventures","Portal To Prose Library",
            "The Quiet Study","Word Wanderer Library","BookBridges","Magic Bookshelf Library","Chapter Verse Venue","Novelty Junction","Novel Approach Library Solutions","Bookworm Bower","Tome Terrace","Pen Paper Palace Library","Bookworm's Paradise Ventures","Prism Pages Library",
            "Novel Nexus","Bookworm's Bliss","Knowledge Haven","Readery Library","Pen Paper Paradise","Inkwell Inc.","BookWorm Business Resources","Inkwell Island","Book Bungalow","LitLounge","Reading Renewal Co.","Whispering Woods Library",
            "Reading Oasis","Wisdom Well Library","StoryScrolls","Library Nook","Scroll Savor","Book Bridge Business","StoryLine Library Management","Publication Plaza","Pages Place","Bookstack Co.","Bookish Innovations","Aurora Avenue Library",
            "Open Book Emporium","Enchanted Pages Library","PagePalace","Bookish Oasis Library","Wonder Words Library","Whispering Pages Group","ChapterOne Consultancy","Brainy Bookshelf","Fictional Hideaway","PageTurner Hub","Storyline Strategies","Horizon Heights Library",
            "Bookworm Depot","Plot Twist Library","ThinkTank Library","Infinite Wisdom Library","Bookworm's Sanctuary","Chapter One Collective","ReadingRoom Advisory","Word Works","Novel Universe","PaperTrail Place","Classic Collective Enterprises","Ink Escape",
            "Study Nook","Infinite Imagination Library","WordWells","Book Haven Services","LibraStory Library","Literary Lagoon","LibraLink Business Services","Storybook Exchange","Prose Perks","StoryScape","Literary Light Co.","Spellbound Stacks",
            "Shelf Universe","Enlightened Reads","Wisdom Wellspring","Future Pages Library","Poetry Palace","Story Spectacle","MagaZine Solutions","Codex Corner","Chapters Cafe","Chapters Charms","Chapters Ahead Business Solutions","Read Retreat",
            "Chapter Quest","Cultural Chronicle Library","Luminous Library","Boundless Books Collection","Library Legends","Pages Bean Library","Literary Loft Consultants","Magnolia Reading Room","Storyline Cafe","Bookworm Bunker","Information Oasis","Knowledge Oasis",
            "Read It Right","Mindful Reading Retreat","Adventure Annex","Wisdom Shelf","Bookland Library","The Literary Oasis","Bookmark Strategies","Prose Parlor Library","Visionary Volumes","VerseVault","Creative Collection","Readify Services",
            "Wisdom Word Repository","The Reading Rainbow","Librarian's Legacy","Harmony Histories","Frontier Frontier Library","Tome Tower","Wordsmith Library Solutions","Dreamland Library","ReadQuest Library","WordWise Warehouse","Bibliophile's Boutique","PageTurner Innovations"

    };
}
